--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- Cities
--========================================================================================================================
			("LOC_CITY_NAME_SUK_SWAHILI_KILWA_KISIWANI",
			"Kilwa Kisiwani"),
			("LOC_CITY_NAME_SUK_SWAHILI_ZANZIBAR",
			"Zanzibar"),
			("LOC_CITY_NAME_SUK_SWAHILI_MOMBASA",
			"Mombasa"),
			("LOC_CITY_NAME_SUK_SWAHILI_LAMU",
			"Lamu"),
			("LOC_CITY_NAME_SUK_SWAHILI_MALINDI",
			"Malindi"),
			("LOC_CITY_NAME_SUK_SWAHILI_SOFALA",
			"Sofala"),
			("LOC_CITY_NAME_SUK_SWAHILI_PATE",
			"Pate"),
			("LOC_CITY_NAME_SUK_SWAHILI_MZIZIMA",
			"Mzizima"),
			("LOC_CITY_NAME_SUK_SWAHILI_BAGAMOYO",
			"Bagamoyo"),
			("LOC_CITY_NAME_SUK_SWAHILI_GEDI",
			"Gedi"),
			("LOC_CITY_NAME_SUK_SWAHILI_QUELIMANE",
			"Quelimane"),
			("LOC_CITY_NAME_SUK_SWAHILI_MOZAMBIQUE",
			"Mozambique"),
			("LOC_CITY_NAME_SUK_SWAHILI_FAZA",
			"Faza"),
			("LOC_CITY_NAME_SUK_SWAHILI_ANGOCHE",
			"Angoche"),
			("LOC_CITY_NAME_SUK_SWAHILI_LINDI",
			"Lindi"),
			("LOC_CITY_NAME_SUK_SWAHILI_MKUMBULU",
			"Mkumbulu"),
			("LOC_CITY_NAME_SUK_SWAHILI_SHANGA",
			"Shanga"),
			("LOC_CITY_NAME_SUK_SWAHILI_SONGO_MNARA",
			"Songo Mnara"),
			("LOC_CITY_NAME_SUK_SWAHILI_MERCA",
			"Merca"),
			("LOC_CITY_NAME_SUK_SWAHILI_KISIMANI_MAFIA",
			"Kisimani Mafia"),
			("LOC_CITY_NAME_SUK_SWAHILI_FAZA",
			"Faza"),
			("LOC_CITY_NAME_SUK_SWAHILI_IBO",
			"Ibo"),
			("LOC_CITY_NAME_SUK_SWAHILI_PANGANI",
			"Pangani"),
			("LOC_CITY_NAME_SUK_SWAHILI_TANGA",
			"Tanga"),
			("LOC_CITY_NAME_SUK_SWAHILI_MUTSAMUDU",
			"Mutsamudu"),
			("LOC_CITY_NAME_SUK_SWAHILI_BRAVA",
			"Brava"),
			("LOC_CITY_NAME_SUK_SWAHILI_SIYU",
			"Siyu"),
			("LOC_CITY_NAME_SUK_SWAHILI_KIZIMKAZI",
			"Kizimkazi"),
			("LOC_CITY_NAME_SUK_SWAHILI_VANGA",
			"Vanga"),
			("LOC_CITY_NAME_SUK_SWAHILI_TAKAUNGU",
			"Takaungu"),
			("LOC_CITY_NAME_SUK_SWAHILI_MOGADISHU",
			"Mogadishu"),
			("LOC_CITY_NAME_SUK_SWAHILI_UNGUJA_UKUU",
			"Unguja Ukuu"),
			("LOC_CITY_NAME_SUK_SWAHILI_KILWA_KIVINJE",
			"Kilwa Kivinje"),
--========================================================================================================================
-- Citizens
--========================================================================================================================
		("LOC_CITIZEN_SUK_SWAHILI_MALE_1",
		"Hamed"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_2",
		"Sulaiman"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_3",
		"Dawud"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_4",
		"Khalid"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_5",
		"Ali"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_6",
		"Muhammad"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_7",
		"Ibrahim"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_8",
		"Sabhat"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_9",
		"Daud"),
		("LOC_CITIZEN_SUK_SWAHILI_MALE_10",
		"Hussein"),

		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_1",
		"Siti"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_2",
		"Aisha"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_3",
		"Mishi"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_4",
		"Afiya"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_5",
		"Bahati"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_6",
		"Eshe"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_7",
		"Fatima"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_8",
		"Chiku"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_9",
		"Habiba"),
		("LOC_CITIZEN_SUK_SWAHILI_FEMALE_10",
		"Jaha"),

		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_1",
		"Yusuf"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_2",
		"Zuberi"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_3",
		"Salehe"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_4",
		"Omar"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_5",
		"Salim"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_6",
		"Juma"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_7",
		"Idi"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_8",
		"Daudi"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_9",
		"Abdu"),

		("LOC_CITIZEN_SUK_SWAHILI_MODERN_MALE_10",
		"Asim"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_1",
		"Shukura"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_2",
		"Shani"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_3",
		"Salma"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_4",
		"Zainabu"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_5",
		"Waseme"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_6",
		"Kesi"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_7",
		"Hawa"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_8",
		"Aziza"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_9",
		"Ashura"),
		("LOC_CITIZEN_SUK_SWAHILI_MODERN_FEMALE_10",
		"Dalili"),
--========================================================================================================================
-- Named Places
--========================================================================================================================
		('LOC_NAMED_RIVER_RUVUMA_NAME',				'Ruvuma River'),
		('LOC_NAMED_RIVER_RUFIJI_NAME',				'Rufiji River'),
		('LOC_NAMED_RIVER_TANA_NAME',				'Tana River'),
		('LOC_NAMED_RIVER_PANGANI_NAME',			'Pangani River'),
		('LOC_NAMED_RIVER_SHEBELLE_NAME',			'Shebelle River'),

		('LOC_NAMED_MOUNTAIN_USAMBARA_NAME',		'Usambara Mountains'),
		('LOC_NAMED_MOUNTAIN_NGURU_NAME',			'Nguru Mountains'),
		('LOC_NAMED_MOUNTAIN_ULUGURU_NAME',			'Uluguru Mountains'),

		('LOC_NAMED_VOLCANO_KARTHALA_NAME',			'Mount Karthala'),

		("LOC_NAMED_LAKE_MALAWI_NAME",				"Lake Malawi"),

		("LOC_NAMED_SEA_SOMALI_NAME",				"Somali Sea"),
		("LOC_NAMED_SEA_OF_ZANJ_NAME",				"Sea of Zanj"),
		("LOC_NAMED_SEA_MENAI_BAY_NAME",			"Menai Bay"),
		("LOC_NAMED_SEA_CHAKE_CHAKE_BAY_NAME",		"Chake-Chake Bay"),
		("LOC_NAMED_SEA_CHWAKA_BAY_NAME",			"Chwaka Bay"),
		("LOC_NAMED_SEA_MANZA_BAY_NAME",			"Manza Bay"),
		("LOC_NAMED_SEA_WINAM_GULF_NAME",			"Winam Gulf"),
--========================================================================================================================
-- Pedia
--========================================================================================================================
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_SWAHILI_LOCATION",
		"Africa"),
		("LOC_CIVINFO_SUK_SWAHILI_SIZE",
		"Est. 426 thousand square miles (1,104.3 thousand square km)"),
		("LOC_CIVINFO_SUK_SWAHILI_POPULATION",
		"99.4 million (2015 est.)"),
		("LOC_CIVINFO_SUK_SWAHILI_CAPITAL",
		"Not a unified state with a capital, but major cities include  Kilwa, Malindi, Mombasa, Pate, Sofala and Zanzibar."),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_1",
		"The medieval sites along the Swahili Coast represent a single cultural tradition with diverse local traditions that can be traced to the ninth century, which is considered to have developed into the modern Swahili culture. Currently, there are 173 identified settlements that flourished along the Swahili Coast and nearby Islands from the ninth to the seventeenth centuries, which include the sites of Kilwa, Malindi, Gedi, Pate, Comoros and Zanzibar."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_2",
		"Wa-swahili, or “shore people”, designates the inhabitants of the East African coastline, and signifies above all a culture with a common language, Kiswahili, and the same religion, Islam. Arab-Persian geographers referred to the inhabitants of the East African coast as the Zanj. It was at the beginning of the nineteenth century that the first use of the term “Swahili” appeared, with settlers trying to classify and differentiate the different populations of Africa. The Swahilis have defined themselves as such since the colonial period, but differentiate between themselves according to their region, island or town of origin. Despite some common ground, Swahili identity remains multiple, incorporating populations of diverse background, both Cushitic and Bantu."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_3",
		"At the beginning of the first millenium CE, the discovery of the monsoon winds and the means to use them created a nautical revolution, allowing for major water crossings toward India and Ceylon. From the ninth century onward, Muslim geographers mention regular trade relations with East Africa, Zanzibar, Pemba and Sofala. These sources indicate that as early as the ninth century, there were major shipping routes between Asia and Africa."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_4",
		"As a result of this burgeoning trade, the transition between the eleventh and twelfth century was a period of change. A number of urban East African centers developed at this time as did architecture in stone, used for public buildings, mosques and enclosure walls. The Swahili city-states were established. By the thirteenth century, a new balance of power had developed. The Swahili coast was divided into several independent sultanates, including Kilwa, Mombasa, Malindi, Pate and Mogadishu."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_5",
		"Kilwa was supposedly one of the most beautiful towns in the world with stone houses covered with palm-leaf roofs or makuti; only certain mosques and the palace had hard flat roofs. From the fourteenth to fifteenth century, Kilwa continued to hold the monopoly for gold, trading gold from Yufi, situated a one-month walk from the coast. Sofala, a vassal of Kilwa city, maintained commercial relations with the Shona kingdom of Great Zimbabwe; the rise of Great Zimbabwe was intimately linked to the trading of gold with Islamized peoples."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_6",
		"The arrival of the Portuguese explorer Vasco da Gama in 1498 signaled a new era of foreign rule on the Swahili Coast. On a mission to economically control and Christianize the Swahili coast, the Portuguese attacked Kilwa first in 1505 and other cities later. Because of Swahili resistance, the Portuguese attempt at establishing commercial control was never successful. By the late 17th century, Portuguese authority on the Swahili coast began to diminish. With the help of Omani Arabs, by 1729 the Portuguese presence had been removed. The Swahili coast eventually became part of the Sultanate of Oman. Trade recovered, but it did not regain the levels of the past."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SWAHILI_CHAPTER_HISTORY_PARA_7",
		"The Swahili civilization stands at the periphery of the Muslim and African worlds, resulting in the development of a unique coastal culture based on trade. In fact, its marginal position is linked to our vision of the Indian Ocean, which separates Africa, Arabia and Asia. But the ocean also provides a connection between these very different cultures: the Swahilis are thus dynamic players, equal to Arab, Persian and Indian traders. Swahili archaeology is at the crossroads of Islamic archaeology and African archaeology.");
--========================================================================================================================
--========================================================================================================================