--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- GAUL
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_GAUL_NAME",  
		"Gaul"	),
		("LOC_CIVILIZATION_SUK_GAUL_DESCRIPTION",  
		"Gallic Empire"	),
		("LOC_CIVILIZATION_SUK_GAUL_ADJECTIVE",  
		"Gallic"	),
		-- RWF
		("LOC_CIVILIZATION_SUK_GAUL_DESCRIPTION_JFD_CIVILIZATION",
		"Gallic Civilization"),
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_TORCS_AND_CARNYXES_NAME",  
		"Torcs and Carnyxes"	),
		("LOC_TRAIT_CIVILIZATION_SUK_TORCS_AND_CARNYXES_DESCRIPTION",  
		"Cities founded on mineable resources provide that resource’s yield modifier to adjacent tiles. When adjacent to mineable resources, Encampments provide +2 [ICON_Production] Production, +1 [ICON_Housing] Housing, and Commercial Hubs provide +2 [ICON_Gold] Gold, +1 [ICON_Amenities] Amenity."),				
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------	
		("LOC_CITY_NAME_SUK_GAUL_BIBRACTE",
		"Bibracte"),
		("LOC_CITY_NAME_SUK_GAUL_VIENNE",
		"Vienne"),
		("LOC_CITY_NAME_SUK_GAUL_ALESIA",
		"Alesia"),
		("LOC_CITY_NAME_SUK_GAUL_GERGOVIA",
		"Gergovia"),
		("LOC_CITY_NAME_SUK_GAUL_NEMOSSOS",
		"Nemossos"),
		("LOC_CITY_NAME_SUK_GAUL_LUTETIA",
		"Lutetia"),
		("LOC_CITY_NAME_SUK_GAUL_CENABUM",
		"Cenabum"),
		("LOC_CITY_NAME_SUK_GAUL_DUROCORTORUM",
		"Durocortorum"),
		("LOC_CITY_NAME_SUK_GAUL_LEMONUM",
		"Lemonum"),
		("LOC_CITY_NAME_SUK_GAUL_NAMNETUM",
		"Namnetum"),
		("LOC_CITY_NAME_SUK_GAUL_CONDATE",
		"Condate"),
		("LOC_CITY_NAME_SUK_GAUL_BURDIGALA",
		"Burdigala"),
		("LOC_CITY_NAME_SUK_GAUL_VESONTIO",
		"Vesontio"),
		("LOC_CITY_NAME_SUK_GAUL_ROTOMAGUS",
		"Rotomagus"),
		("LOC_CITY_NAME_SUK_GAUL_SAMAROBRIVA",
		"Samarobriva"),
		("LOC_CITY_NAME_SUK_GAUL_DIVODURUM",
		"Divodurum"),
		("LOC_CITY_NAME_SUK_GAUL_SEGODUNUM",
		"Segodunum"),
		("LOC_CITY_NAME_SUK_GAUL_NEMETOCENNA",
		"Nemetocenna"),
		("LOC_CITY_NAME_SUK_GAUL_AUTRICUM",
		"Autricum"),
		("LOC_CITY_NAME_SUK_GAUL_SUINDINUM",
		"Suindinum"),
		("LOC_CITY_NAME_SUK_GAUL_AVARICON",
		"Avaricon"),
		("LOC_CITY_NAME_SUK_GAUL_DARIORITUM",
		"Darioritum"),
		("LOC_CITY_NAME_SUK_GAUL_AGEDINCUM",
		"Agedincum"),
		("LOC_CITY_NAME_SUK_GAUL_ARGENTORATE",
		"Argentorate"),
		("LOC_CITY_NAME_SUK_GAUL_NOVIOMAGUS",
		"Noviomagus"),
		("LOC_CITY_NAME_SUK_GAUL_BAGACUM",
		"Bagacum"),
		("LOC_CITY_NAME_SUK_GAUL_GESORIACUM",
		"Gesoriacum"),
		("LOC_CITY_NAME_SUK_GAUL_GABILLONUM",
		"Gabillonum"),
		("LOC_CITY_NAME_SUK_GAUL_TOLOSA",
		"Tolosa"),
		("LOC_CITY_NAME_SUK_GAUL_LUGDUNUM",
		"Lugdunum"),
		("LOC_CITY_NAME_SUK_GAUL_UXELLODUNUM",
		"Uxellodunum"),
		("LOC_CITY_NAME_SUK_GAUL_DUROTINCON",
		"Durotincon"),
		("LOC_CITY_NAME_SUK_GAUL_BRATUSPANTION",
		"Bratuspantion"),
		("LOC_CITY_NAME_SUK_GAUL_NOVIODUNUM",
		"Noviodunum"),
		("LOC_CITY_NAME_SUK_GAUL_DIVONA",
		"Divona"),
		("LOC_CITY_NAME_SUK_GAUL_KARNAG",
		"Karnag"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_GAUL_MALE_1",
		"Segomāros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_2",
		"Brennos"),
		("LOC_CITIZEN_SUK_GAUL_MALE_3",
		"Dubnorīx"),
		("LOC_CITIZEN_SUK_GAUL_MALE_4",
		"Brogimaros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_5",
		"Kintugnātos"),
		("LOC_CITIZEN_SUK_GAUL_MALE_6",
		"Katurīx"),
		("LOC_CITIZEN_SUK_GAUL_MALE_7",
		"Gāromāros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_8",
		"Adyantumāros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_9",
		"Albiorix"),
		("LOC_CITIZEN_SUK_GAUL_MALE_10",
		"Wirogalos"),

		("LOC_CITIZEN_SUK_GAUL_FEMALE_1",
		"Dēwognātā"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_2",
		"Kunopennos"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_3",
		"Luguselwā"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_4",
		"Paulla"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_5",
		"Boudilatis"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_6",
		"Rufena"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_7",
		"Severa"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_8",
		"Banona"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_9",
		"Auctiona"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_10",
		"Vlatucia"),

		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_1",
		"Martialis"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_2",
		"Vectitos"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_3",
		"Essandecottos"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_4",
		"Andareuiseos"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_5",
		"Cerethrius"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_6",
		"Vitalstatistix"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_7",
		"Boduognatus"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_8",
		"Taranis"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_9",
		"Dumnorix"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_10",
		"Katurīx"),

		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_1",
		"Andarta"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_2",
		"Eskenga"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_3",
		"Rosmerta"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_4",
		"Epona"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_5",
		"Sirona"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_6",
		"Arduinna"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_7",
		"Venitouta"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_8",
		"Vlatuca"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_9",
		"Adiega"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_10",
		"Abesa"),	
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_GAUL_LOCATION",
		"Europe"),
		("LOC_CIVINFO_SUK_GAUL_SIZE",
		"Est. 191 thousand square miles (494 thousand square km)"),
		("LOC_CIVINFO_SUK_GAUL_POPULATION",
		"Est. 5 million people (at the time of the Roman conquest)"),
		("LOC_CIVINFO_SUK_GAUL_CAPITAL",
		"None (the Gallic tribes were not unified, and each tribe had their own capital)"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_1",
		"In 58 BC, Julius Caesar’s year as consul had come to an end, and he was appointed proconsul of Cisalpine Gaul, a place whose history is a much-debated topic among historians both modern and ancient; a place which some argue did not exist until Caesar’s arrival. Gallic tribes have been in the region referred to as Gaul for as long as historians have recorded the history of the area, and even before."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_2",
		"Gallic culture developed out of the Celtic cultures over the first millennia BC. The Urnfield culture (c. 1300 BC – c. 750 BC) represents the Celts as a distinct cultural branch of the Indo-European-speaking people. The spread of iron working led to the Hallstatt culture in the 8th century BC; the Proto-Celtic (Liguro-Venetic) may have been spoken around this time. The Hallstatt culture evolved into the La Tène culture in around the 5th century BC. The Greek and Etruscan civilizations and colonies began to influence the Gauls especially in the Mediterranean area."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_3",
		"Gallic groups, originating from the various La Tène chiefdoms, began a southeastern movement into the Balkan peninsula from the 4th century BC. Although Celtic settlements were concentrated in the western half of the Carpathian basin, there were notable incursions, and settlements, within the Balkan peninsula itself. From their new bases in northern Illyria and Pannonia, the Gallic invasions climaxed in the early 3rd century BC, with the invasion of Greece. The 279 BC invasion of Greece proper was preceded by a series of other military campaigns waged toward the southern Balkans and against the kingdom of Macedonia, favoured by the state of confusion ensuing from the intricated succession to Alexander. A part of the invasion crossed over to Anatolia and eventually settled in the area that came to be named after them, Galatia."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_4",
		"In 278 BC Gallic settlers in the Balkans were invited by Nicomedes I of Bithynia to help him in a dynastic struggle against his brother. They numbered about 10,000 fighting men and about the same number of women and children, divided into three tribes, Trocmi, Tolistobogii and Tectosages. They were eventually defeated by the Seleucid king Antiochus I (275 BC), in a battle where the Seleucid war elephants shocked the Galatians. While the momentum of the invasion was broken, the Galatians were by no means exterminated and continued to demand tribute from the Hellenistic states of Anatolia to avoid war. 4,000 Galatians were hired as mercenaries by the Ptolemaic Egyptian king Ptolemy II Philadelphus in the 270 BC. According to Pausanias, soon after arrival the Celts plotted “to seize Egypt,” and so Ptolemy marooned them on a deserted island in the Nile River. Galatians also participated at the victorious in 217 BC Battle of Raphia under Ptolemy IV Philopator, and continued to serve as mercenaries for the Ptolemaic Dynasty until its demise in 30 BC. They sided with the renegade Seleucid prince Antiochus Hierax, who reigned in Asia Minor. Hierax tried to defeat king Attalus I of Pergamum (241–197 BC), but instead, the Hellenized cities united under Attalus’s banner, and his armies inflicted a severe defeat upon the Galatians at the Battle of the Caecus River in 241 BC. After the defeat, the Galatians continued to be a serious threat to the states of Asia Minor. In fact, they continued to be a threat even after their defeat by Gnaeus Manlius Vulso in the Galatian War (189 BC). Galatia declined and fell at times under Pontic ascendancy. They were finally freed by the Mithridatic Wars, during which they supported Rome. In the settlement of 64 BC, Galatia became a client-state of the Roman empire, the old constitution disappeared, and three chiefs (wrongly styled ’tetrarchs’) were appointed, one for each tribe. But this arrangement soon gave way before the ambition of one of these tetrarchs, Deiotarus, the contemporary of Cicero and Julius Caesar, who made himself master of the other two tetrarchies and was finally recognized by the Romans as ’king’ of Galatia. The Galatian language continued to be spoken in central Anatolia until the 6th century."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_5",
		"During the Second Punic War the famous Carthaginian general Hannibal Barca utilized Gallic mercenaries in his invasion of Italy. They played a part in some of his most spectacular victories including the battle of Cannae. The Gauls were prosperous enough by the 2nd century that the powerful Greek colony of Massilia had to appeal to the Roman Republic for defense against them. The Romans intervened in southern Gaul in 125 BC, and conquered the area eventually known as Gallia Narbonensis by 121."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_6",
		"The end of the Gauls as an independent people was marked by the Gallic War. It was the conflict in which Julius Caesar first emerged as a great military leader, after an earlier career as an impoverished populist politician. Only after putting down three major Gallic revolts, the last and most famous being led by Vercingetorix, could Caesar claim to have pacified Gaul. Perhaps the most unusual feature of the Gallic War is that in Caesar’s commentaries on the war we have a first hand account of all but the last year of the war, written at the time by the most important figure in that war. After this, Gaul became a province of the Roman Empire, and the Gauls were ethnically and culturally largely assimilated into Latin (Roman settlers) majority, losing their tribal identities by the end of the 1st century AD."),
--========================================================================================================================
-- Unique Unit
--========================================================================================================================
		("LOC_UNIT_SUK_OATHSWORN_NAME",  
		"Oathsworn"	),
		("LOC_UNIT_SUK_OATHSWORN_DESCRIPTION",  
		"Gallic unique Classical Era unit that replaces the Swordsman. +5 [ICON_Strength] Combat Strength in Hills and Woods. When an Oathsworn is killed in combat, all friendly adjacent land combat units heal for 40 HP."),
		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_OATHSWORN_CHAPTER_HISTORY_PARA_1",  
		"The longsword was a weapon of high worth and status within the Celtic community. A warrior had to prove himself in battle many times before he was permitted to wield one. The two-handed longsword was first developed during the 8th century BC, but fell from favour before re-emerging around 450BC. It is possible that Celtic ironwork was significantly behind that of the Romans, as apparently their longswords bent very easily and had to be straightened against the ground. On the other hand, since Celtic ironworking was several centuries old, some believe that Roman accounts of this practice mistook this practise, and it was actually a ritual to ’decommission’ defeated, dishonoured or damaged weapons."),

		("LOC_ABILITY_SUK_OATHSWORN_COMBAT_BONUS_DESCRIPTION",  
		"+{1_Amount} Combat Strength bonus in Hills and Forest"),			
--========================================================================================================================
-- Unique Infrastructure
--========================================================================================================================
		("LOC_IMPROVEMENT_SUK_DUNON_NAME",  
		"Dūnon"	),
		("LOC_IMPROVEMENT_SUK_DUNON_DESCRIPTION",  
		"Unlocks the Builder ability to construct a Dūnon, unique to Gaul.[NEWLINE][NEWLINE]+1 [ICON_Food] Food, +1 [ICON_Housing] Housing. +1 [ICON_Production] Production if built on a Hill. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification.[NEWLINE][NEWLINE]The Dūnon must be built on a Camp or Pasture resource and provides that resource’s yield modifier to adjacent tiles. One per City. Tiles with Dūnons cannot be swapped."),
		("LOC_PEDIA_DISTRICTS_PAGE_IMPROVEMENT_SUK_DUNON_CHAPTER_HISTORY_PARA_1",  
		"An oppidum, or a dūnon is a large fortified Iron Age settlement. Most were built on fresh sites, usually on an elevated position. Such a location would have allowed the settlement to dominate nearby trade routes and may also have been important as a symbol of control of the area. While some dūnons grew from hill forts, by no means all of them had significant defensive functions. The development of dūnons was a milestone in the urbanisation of the continent as they were the first large settlements north of the Alps that could genuinely be described as towns. continued in use until the Romans began conquering Iron Age Europe. Even in the lands north of the River Danube that remained unconquered by the Romans, dūnons were abandoned by the late 1st century AD. In conquered lands, the Romans used the infrastructure of the dūnons to administer the empire, and many became full Roman towns. This often involved a change of location from the hilltop into the plain."),	
--========================================================================================================================
-- Leader
--========================================================================================================================
		("LOC_LEADER_SUK_VERCINGETORIX_NAME",  
		"Vercingetorix"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_GALLIC_WAR_NAME",  
		"Gallic Confederation"	),
		("LOC_TRAIT_LEADER_SUK_GALLIC_WAR_DESCRIPTION",  
		"Your units receive +1 [ICON_Strength] Combat Strength for each type of City-State you are Suzerain of. Receive a free [ICON_Envoy] Envoy whenever you recruit a [ICON_GreatGeneral] Great General. When an Encampment or Dūnon is built, receive Ancient Walls in that City."	),

		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_DESCRIPTION",  
		"+1 [ICON_Strength] Combat Strength for each type of City-State you are Suzerain of (Gallic Confederation)"	),

		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_TRADE_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_TRADE})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_SCIENTIFIC_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_SCIENTIFIC})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_RELIGIOUS_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_RELIGIOUS})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_MILITARISTIC_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_MILITARISTIC})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_INDUSTRIAL_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_INDUSTRIAL})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_CULTURAL_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_CULTURAL})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_CSE_AGRICULTURAL_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_CSE_AGRICULTURAL})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_CSE_CONSULAR_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_CSE_CONSULAR})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_CSE_ENTERTAINMENT_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_CSE_ENTERTAINMENT})"),
		("LOC_ABILITY_SUK_GALLIC_WAR_COMBAT_STRENGTH_LEADER_MINOR_CIV_CSE_MARITIME_DESCRIPTION",  
		"+{1_Amount} [ICON_Strength] (Gallic Confederation, {LOC_CITY_STATES_TYPE_CSE_MARITIME})"),		
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_KING_OVER_WARRIORS_NAME",  
		"King Over Warriors"	),
		("LOC_AGENDA_SUK_KING_OVER_WARRIORS_DESCRIPTION",  
		"Likes civilizations with strong armies, but only if they don’t own any captured cities."	),

		("LOC_DIPLO_MODIFIER_SUK_KING_OVER_WARRIORS_KUDO",  
		"Vercingetorix admires your strong armies"	),

		("LOC_DIPLO_MODIFIER_SUK_KING_OVER_WARRIORS_WARNING",  
		"Vercingetorix thinks your army is a threat to his civilization"	),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		-- ("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SUK_GAUL",
		-- "Goði"),
		-- ("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_SUK_GAUL",
		-- "Warchief"),
		-- ("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_SUK_GAUL",
		-- "Bæjarstjóri"),
		-- ("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_SUK_GAUL",
		-- "Lawspeaker"),
		-- ("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_NORWAY",
		-- "Jarl"),
		-- ("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SUK_GAUL",
		-- "Thegn"),
		-- ("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_SUK_GAUL",
		-- "Councillor"),	
		-- ("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_SUK_GAUL",
		-- "King"),
		-- ("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_GAUL",
		-- "High King"),
		-- ("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SUK_GAUL",
		-- "High Councillor"),
		-- ("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_SUK_GAUL",
		-- "Forseti"),
		-- ("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_SUK_GAUL",
		-- "Inspector General"),
		-- ("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_SUK_GAUL",
		-- "General Secretary"),	
		-- ("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SUK_GAUL",
		-- "Emperor"),									
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_VERCINGETORIX",  
		"Proud Vercingetorix, be ever vigilant of those who would threaten Gaul. Unite your disparate people and rally your loyal oathsworn. Fortify your cities and settlements and let your walls stand strong. Keep your people safe and prosperous, and your name will live on in legend."),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"This is unfortunate."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"Yes, good."),
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Let us announce our mutual friendship, and give the tyrants of the world pause."),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Gaul does not recognise a friendship with you"),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Your honor us. Thank you."),
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"You are a threat to all of Gaul. For the sake of our freedom, you must be stopped! Prepare to meet your end!"), 
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Do you think we fear you? Every man and woman shall fight to their last."), 
		-- ("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                      
		-- "We fought to our last—and lost. I surrender my arms to you and await your judgement."),
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"We fought to our last—and lost. I surrender my arms to you and await your judgement."),
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"I am sending you a gift that befits your station as a leader and a warrior—a golden torc weighing 100 libra."),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Unfortunately, I am currently occupied with a dispute amongst my chieftains and have no time to entertain a delegation"),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Your delegation and the gifts they bear, are welcome. Thank you."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"You are nothing but a tyrant who would see the world in chains!"),
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"My friends and fellow Gauls will rally to my defense. Who do you have to back your foul words?"),
		("LOC_DIPLO_FIRST_MEET_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Hail! I am Vercingetorix. I was chosen to lead the Gallic people and defend them against their foes."),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Come and see our proud settlements. See how well they are protected!"),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"On behalf of my chieftains, yes!"),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Tell me of your capital, and I will tell you of mine."),
		("LOC_DIPLO_GREETING_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Hail!"),
		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Will you turn that sword of yours against the Gallic people too? Tyrants such as you are not to be trusted."),
		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"A strong army and a strong peoples. It appears we see eye to eye when it comes to leadership."),
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"My people seek an allience against the dangers of this world. Will you join us?"),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"This is not acceptable."),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"A fine proposal. Agreed!"),
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"Agreed. This futile war has gone on long enough."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"This war must continue. My people demand it!"),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"I weary of this war. Let us seek peace."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"Very well. I don’t imagine we have much to fear from you."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"No, I will not have enemy soldiers meandering across Gallic lands."),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_VERCINGETORIX_ANY",                                     
		"My chieftains suggest that open borders will improve relations between us."),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_VERCINGETORIX_ANY",                                      
		"Our dūnons are well defend from any threats, as your soldiers can see. Are you satisfied with your army’s scouting?"),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_VERCINGETORIX_QUOTE",  
		"You want to fight? You want to live forever? Then I will lead you."  	), -- Yes, I know this is from a movie, but I can’t even find a Gallic proverb to use so *shrugs*
		("LOC_PEDIA_LEADERS_PAGE_SUK_VERCINGETORIX_TITLE",
		"Vercingetorix"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_VERCINGETORIX_SUBTITLE",
		"Verrix of the Gauls"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_CAPSULE_BODY",
		"Gaul’s main strength lies in their unique interaction with the resources nature provides them. With the aid of the Oathsworn, the Dūnon, and Vercingetorix’s leadership, Gaulish lands will be unconquerable—as long as the people stay loyal."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_DETAILED_BODY",
		"Gaul’s main question is one of where to settle. The bulk of their unique ability relies on settling on mineable resources, but this may mean you will have to settle a tile to two away from a river or a more advantageous spot. This is further complicated by the Dūnon, which is likewise powerful but has similarly stringent requirements. Finding spots where you can take full advantage of both of these abilities will be key to a successful game. Vercingetorix’s abilities help keep your empire safe: allowing you to quickly erect walls wherever they are needed, and providing a significant combat boost while everyone stays loyal."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_1",
		"Revered in France as its first national hero, Vercingetorix managed to unite several sovereign Celtic tribes to do battle against the aggressive Romans. Vercingetorix was an Arverni, one of the many Celtic tribes who ruled over what is France today, northern Germany, the Benelux countries, and the British Isles."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_2",
		"The Celtic world into which Vercingetorix was born in about 75 BC had evolved into a complex society which made military success and economic stability dependent on peasant agricultural labour, and vice versa. This system was the precursor of feudalism, a noble-peasant economic dependency that would dominate Europe for much of the Middle Ages. Vercingetorix hailed from a noble ruling family likely situated in what is now the town of Auvergny-a name reflecting its Celtic Arverni origins-in south-central Gaul, as France was then called. He inherited the chieftainship of the Arverni from his father, Celtillus, who had attempted to ascend to a kingship over several other Celtic tribes during a time of political uncertainty in central France. As a result, Celtillus was likely slain by a conspiracy of nobles and chiefs in opposition to him. Ironically, his son would advance to the position of leader of several Celtic tribes, but only when the necessity of an alliance became apparent, when a determined Roman army threatened."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_3",
		"As befitting the son of a Celtic noble and member of the warrior class, Vercingetorix was likely provided with military training from an early age. He was probably schooled in Druid beliefs and rites as well. During his lifetime, the Druids had become a powerful force in Celtic civilization, and were an adamantly conservative element very much opposed to Roman encroachment. Other Celtic tribes, such as the Boii, were more receptive to the economic promise and infrastructure development that Roman conquest offered. In southern Italy, the Roman republic was evolving, through a series of wars, conquests, and personal betrayals, into an empire. Julius Caesar was a popular democratic leader, one of the men of the first Triumvirate who ruled around 60 BC, but departed from the comforts of the urbanized and highly developed capital to conquer Gaul. This decade-long military campaign is chronicled in his De Bello Gallico (“The Gallic Wars”), from which the story survives as an account of Vercingetorix and his times."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_4",
		"Varying tribes of Celts had been long threatened by the menace of Germanic peoples like the Suevi. The Germans periodically emerged from what was a vast and, to the Romans, mysterious forest that spread across Central Europe. At first Caesar helped the Celts of central Gaul repel German encroachments, and also acted as arbitrator between Celtic tribes and their enemy, but began attacking central Gaul’s tribes such as the Arverni. Because of the harsh treatment Romans sometimes unleashed on those they conquered, Celtic uprisings in northern Gaul began in 54 BC and continued through the following year. During the winter of 53-52 BC, Caesar returned to Rome, but left a garrison of soldiers stationed in central Gaul.An uprising of Celts, led by the Carnutes, slaughtered several Roman officials and traders at Cenabum (now Orleans, France) that winter. According to Caesar’s chronicle, the news of the victory was shouted from Celtic settlement to settlement, and reached the borders of Vercingetorix’s Arverni lands by the morning light. In his early twenties at that time, Vercingetorix wished to command a legion of Arverni and join with the Celts of central Gaul; his uncle, Gobannito, and several other elders thought this unwise, and so Vercingetorix was cast out of his capital, Gergovia, near what is today Clermont, France."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_5",
		"Caesar wrote respectfully of his Celtic foe in The Gallic Wars, noting that the exiled but determined Vercingetorix then gathered a militia of beggars and outcasts, and began convincing Arverni nobles to listen to his plan. Eventually he staged a coup in Gergovia and cast out those leaders who had rejected an offensive attack on the well-equipped, well-organized Romans.Vercingetorix then sent out emissaries to secure an allegiance, via the enforced handover of hostages, with several other Celtic tribes who ruled over sections of Gaul. These included the Senones, Parisii, Pictones, Cadurci, Turoni, Aulerci, Lemovice, and Andi, among others. He was named commander-in-chief. That winter, with Caesar still in Rome, Vercingetorix and Celtic armies began battling Roman garrisons in northern France. Caesar returned immediately upon learning of the attacks, though crossing over the Alps with an army, horses, and supplies was no easy task during the winter months. Roman legions began attacking Celtic settlements in vulnerable southern Gaul, many of whose men and arms had been sent north with Vercingetorix. Meanwhile, Vercingetorix had launched an assault on Gorgorbina, a town of Celtic Boii already loyal to Rome.Vercingetorix and his army were defeated at Vallaunodunum (modern Montargis), and then Caesar re-took Cenabum from the Celts, and burnt it to the ground. Caesar was in the process of taking the town of Noviodunum, whose Celtic Bituriges were handing over tribute and men, when the army of Vercingetorix was spotted in the distance. The Bituriges quickly shut their gates on the Romans, and a battle with Roman cavalry followed. Noviodunum then fell to the Romans, who planned to take the city of Avaricum (Bourges) next."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_6",
		"As a result of these setbacks, Vercingetorix called a summit at Bibracte, the stronghold of the Aedui, another great Celtic tribe who ruled over the lands to the north and east of the Arverni. The Aedui, according to the classical historian Plutarch in Lives of the Noble Grecians and Romans, ’had styled themselves brethren to the Romans, and had been much honoured by them.’ This last great alliance in effect made Vercingetorix the first-and last-leader of a unified Celtic nation.Vercingetorix and his followers decided to burn their own settlements along the way, making it impossible for the Romans to obtain food in hostile territory. Twenty cities across the land of the Bituriges were set afire, and some in other areas as well. They decided not to burn Avaricum and defend it instead. But the Romans laid siege to Avaricum for several months, and eventually defeated the Celts in a bloody battle.Next on the Roman agenda was Gergovia. Vercingetorix recovered sufficiently from the setback of Avaricum to defend his hometown with renewed troops and determination. When the situation degenerated into a stalemate, Caesar’s armies began marching toward Lutetia (Paris), burning everything Celtic they encountered along the way. Vercingetorix was forced to move against this, suffered an attack by the Roman cavalry, and had to retreat to Alesia. The walled center of the Celtic Mandubi tribe, Alesia was set on a hill and was theoretically easy to defend. The Romans built a massive fortification around it, however, with their usual marvels of defensive engineering constructed-towers, battering rams, screens on wheels-on the side facing the hill. They also constructed walls at the rear to protect it from Celts arriving as reinforcements, for Vercingetorix had sent out emissaries in the middle of the night back to their own home states for additional men, arms, and horses. Caesar wrote that a quarter-million Celts arrived to do battle at Alesia. Plutarch places this number at 300,000, and notes that inside Alesia’s walls was already a Celtic force of about 170,000."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_VERCINGETORIX_CHAPTER_HISTORY_PARA_7",
		"But the Romans, who also had dug deep trenches, simply waited for Vercingetorix and the Celtic army to run out of provisions. Vercingetorix sent out sorties to battle the Roman soldiers, but poor communication and coordination of efforts plagued the poorly-organized Celts, and they suffered numerous reverses. Vercingetorix’s cousin, Vercassivellaunus, battled from the rear in one coordinated attack, but failed to break the Roman line. The Celtic troops facing the Romans from outside saw the futility of the effort, and abandoned Alesia.When Alesia surrendered, Caesar demanded not just all arms of the Celts but their leader as well. Vercingetorix told his colleagues that they could either deliver him dead or alive to the Romans, according to their wishes. Alive, it was decreed. According to Plutarch, Vercingetorix prepared by “putting his best armour on, and adorning his horse, [then] rode out of the gates, and made a turn about Caesar as he was sitting, then quitting his horse, threw off his armour, and remained quietly sitting at Caesar’s feet until he was led away to be reserved for the triumph.” It was his last act as a free man as he was then taken into custody and returned with Caesar to Rome, where a 20-day public thanksgiving was called for the not-insignificant conquest of Gaul. Vercingetorix was allegedly dragged behind Caesar’s chariot in the official victory parade. He died in Rome about 46 BC.");
--------------------------------------------------------------------
--------------------------------------------------------------------