/*
	Civilization
	Credits: ChimpanG, SeelingCat
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
		(Type,								Kind				)
VALUES	('CIVILIZATION_CVS_SWITZERLAND',	'KIND_CIVILIZATION'	);
		
-----------------------------------------------
-- Civilizations
-----------------------------------------------

INSERT INTO	Civilizations
		(CivilizationType,					Name,										Description,									Adjective,										StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CIVILIZATION_CVS_SWITZERLAND_NAME',	'LOC_CIVILIZATION_CVS_SWITZERLAND_DESCRIPTION',	'LOC_CIVILIZATION_CVS_SWITZERLAND_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_EURO' 	);

-----------------------------------------------
-- CityNames
-----------------------------------------------

INSERT INTO	CityNames
		(CivilizationType,				 CityName )
VALUES	('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_BERN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_ZURICH'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LUCERNE'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_GENEVA'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_BASEL'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_ALTDORF'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_SCHWYZ'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LAUSANNE'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_NEUCHATEL'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_ST_GALLEN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_SARNEN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_STANS'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_GLARUS'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_ZUG'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_FRIBOURG'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_SOLOTHURN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LIESTAL'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_SCHAFFHAUSEN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_HERISAU'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_APPENZELL'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_CHUR'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_AARAU'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_FRAUENFELD'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_BELLINZONA'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_SION'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_DELEMONT'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_WINTERTHUR'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LUGANO'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_BIEL'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_THUN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_KONIZ'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LA_CHAUX_DE_FONDS'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_VERNIER'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_USTER'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LANCY'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_EMMEN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_YVERDON_LES_BAINS'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_DUBENDORF'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_KRIENS'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_DIETIKON'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_RAPPERSWIL_JONA'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_MONTREUX'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_FRAUENFELD'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_WETZIKON'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_BAAR'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_MEYRIN'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_GRUYERES'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_BULLE'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_LA_TOUR_DE_TREME'),
		('CIVILIZATION_CVS_SWITZERLAND', 'LOC_CITY_NAME_CAROUGE');
			
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------

INSERT INTO	CivilizationCitizenNames
		(CivilizationType,					CitizenName,								Female	)
VALUES	('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_1',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_2',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_3',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_4',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_5',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_6',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_7',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_8',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_9',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_MALE_10',		0 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_1',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_2',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_3',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_4',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_5',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_6',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_7',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_8',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_9',		1 		),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CITIZEN_CVS_SWITZERLAND_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------

INSERT INTO	CivilizationInfo
		(CivilizationType,					Header,						Caption,									SortIndex	)
VALUES	('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_CVS_SWITZERLAND_LOCATION',		10			),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_CVS_SWITZERLAND_SIZE',			20			),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_CVS_SWITZERLAND_POPULATION',	30			),
		('CIVILIZATION_CVS_SWITZERLAND',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_CVS_SWITZERLAND_CAPITAL',		40			);
		
-----------------------------------------------
-- Start Bias
-----------------------------------------------

INSERT INTO	StartBiasTerrains
		(CivilizationType,					TerrainType,				Tier	)
VALUES	('CIVILIZATION_CVS_SWITZERLAND',	'TERRAIN_GRASS_MOUNTAIN',	2		),
		('CIVILIZATION_CVS_SWITZERLAND',	'TERRAIN_GRASS_HILLS',		3		);


INSERT INTO	StartBiasRivers
		(CivilizationType,					Tier)
VALUES	('CIVILIZATION_CVS_SWITZERLAND',	5	);

-----------------------------------------------
-- RequirementSets
-----------------------------------------------

INSERT INTO RequirementSets
        (RequirementSetId,						RequirementSetType			)
VALUES	('REQSET_CVS_PLAYER_IS_SWITZERLAND',	'REQUIREMENTSET_TEST_ALL'	),
		('REQSET_CVS_LEADER_IS_SWITZERLAND',	'REQUIREMENTSET_TEST_ANY'	);

-----------------------------------------------
-- RequirementSetRequirements
-----------------------------------------------

INSERT INTO RequirementSetRequirements
        (RequirementSetId,						RequirementId					)
VALUES	('REQSET_CVS_PLAYER_IS_SWITZERLAND',	'REQ_CVS_PLAYER_IS_SWITZERLAND'	);

-----------------------------------------------
-- Requirements
-----------------------------------------------

INSERT INTO Requirements
		(RequirementId,						RequirementType						)
VALUES	('REQ_CVS_PLAYER_IS_SWITZERLAND',	'REQUIREMENT_REQUIREMENTSET_IS_MET'	);

-----------------------------------------------
-- RequirementArguments
-----------------------------------------------

INSERT INTO RequirementArguments
		(RequirementId,						Name,				Value								)
VALUES	('REQ_CVS_PLAYER_IS_SWITZERLAND',	'RequirementSetId', 'REQSET_CVS_LEADER_IS_SWITZERLAND'	);