--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- Burma
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_BURMA_NAME",  
		"Burma"	),
		("LOC_CIVILIZATION_SUK_BURMA_DESCRIPTION",  
		"Burmese Empire"	),
		("LOC_CIVILIZATION_SUK_BURMA_ADJECTIVE",  
		"Burmese"	),
		-- RWF
		("LOC_CIVILIZATION_SUK_BURMA_DESCRIPTION_JFD_CIVILIZATION",
		"Burmese Civilization"),		
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_AHMUDAN_CONSCRIPTION_NAME",  
		"Ahmudan Conscription"	),
		("LOC_TRAIT_CIVILIZATION_SUK_AHMUDAN_CONSCRIPTION_DESCRIPTION",  
		"Gain [ICON_Culture] Culture and [ICON_Faith] Faith on building Encampments, Holy Sites, and Theater Squares. These districts provide +5% [ICON_Production] towards melee, anti-cavalry, and cavalry units in the cities they are built."), 
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------
		("LOC_CITY_NAME_SUK_BURMA_PEGU",
		"Pegu"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGOO",
		"Taungoo"),
		("LOC_CITY_NAME_SUK_BURMA_BASSEIN",
		"Bassein"),
		("LOC_CITY_NAME_SUK_BURMA_MARTABAN",
		"Martaban"),
		("LOC_CITY_NAME_SUK_BURMA_MERGUI",
		"Mergui"),
		("LOC_CITY_NAME_SUK_BURMA_PROME",
		"Prome"),
		("LOC_CITY_NAME_SUK_BURMA_MYAUNGMYA",
		"Myaungmya"),
		("LOC_CITY_NAME_SUK_BURMA_THAN_HLYIN",
		"Than Hlyin"),
		("LOC_CITY_NAME_SUK_BURMA_RANGOON",
		"Rangoon"),
		("LOC_CITY_NAME_SUK_BURMA_MANDALAY",
		"Mandalay"),
		("LOC_CITY_NAME_SUK_BURMA_PAGAN",
		"Pagan"),
		("LOC_CITY_NAME_SUK_BURMA_TAVOY",
		"Tavoy"),
		("LOC_CITY_NAME_SUK_BURMA_SANDOWAY",
		"Sandoway"),
		("LOC_CITY_NAME_SUK_BURMA_MYOHAUNG",
		"Myohaung"),
		("LOC_CITY_NAME_SUK_BURMA_SHWEBO",
		"Shwebo"),
		("LOC_CITY_NAME_SUK_BURMA_AKYAB",
		"Akyab"),
		("LOC_CITY_NAME_SUK_BURMA_NAYPYIDAW",
		"Naypyidaw"),
		("LOC_CITY_NAME_SUK_BURMA_MOULMEIN",
		"Moulmein"),
		("LOC_CITY_NAME_SUK_BURMA_MYITKYINA",
		"Myitkyina"),
		("LOC_CITY_NAME_SUK_BURMA_SAGAING",
		"Sagaing"),
		("LOC_CITY_NAME_SUK_BURMA_HSENWI",
		"Hsenwi"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGGYI",
		"Taunggyi"),
		("LOC_CITY_NAME_SUK_BURMA_KENGTUNG",
		"Kengtung"),
		("LOC_CITY_NAME_SUK_BURMA_MOHNYIN",
		"Mohnyin"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGYO",
		"Taungyo"),
		("LOC_CITY_NAME_SUK_BURMA_WIZAYAPURA",
		"Wizayapura"),
		("LOC_CITY_NAME_SUK_BURMA_THATON",
		"Thaton"),
		("LOC_CITY_NAME_SUK_BURMA_MONYWA",
		"Monywa"),
		("LOC_CITY_NAME_SUK_BURMA_NYAUNG_U",
		"Nyaung-U"),
		("LOC_CITY_NAME_SUK_BURMA_HANLIN",
		"Hanlin"),
		("LOC_CITY_NAME_SUK_BURMA_YE",
		"Ye"),
		("LOC_CITY_NAME_SUK_BURMA_HSIPAW",
		"Hsipaw"),
		("LOC_CITY_NAME_SUK_BURMA_MOMEIK",
		"Momeik"),
		("LOC_CITY_NAME_SUK_BURMA_MONG_NAI",
		"Mong Nai"),
		("LOC_CITY_NAME_SUK_BURMA_MOGAUNG",
		"Mogaung"),
		("LOC_CITY_NAME_SUK_BURMA_KALAYMYO",
		"Kalaymyo"),
		("LOC_CITY_NAME_SUK_BURMA_KYAUKSE",
		"Kyaukse"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGDWINGYI",
		"Taungdwingyi"),
		("LOC_CITY_NAME_SUK_BURMA_THARRAWADDY",
		"Tharrawaddy"),
		("LOC_CITY_NAME_SUK_BURMA_CHAUK",
		"Chauk"),
		("LOC_CITY_NAME_SUK_BURMA_DONWUN",
		"Donwun"),
		("LOC_CITY_NAME_SUK_BURMA_NYAUNGSHWE",
		"Nyaungshwe"),
		("LOC_CITY_NAME_SUK_BURMA_MINBU",
		"Minbu"),
		("LOC_CITY_NAME_SUK_BURMA_SALIN",
		"Salin"),
		("LOC_CITY_NAME_SUK_BURMA_BHAMO",
		"Bhamo"),
		("LOC_CITY_NAME_SUK_BURMA_MONG_YANG",
		"Mong Yang"),
		("LOC_CITY_NAME_SUK_BURMA_INGAPU",
		"Ingapu"),
		("LOC_CITY_NAME_SUK_BURMA_YAMETHIN",
		"Yamethin"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_BURMA_MALE_1",
		"Nu"),
		("LOC_CITIZEN_SUK_BURMA_MALE_2",
		"Thant"),
		("LOC_CITIZEN_SUK_BURMA_MALE_3",
		"Maung"),
		("LOC_CITIZEN_SUK_BURMA_MALE_4",
		"Thura"),
		("LOC_CITIZEN_SUK_BURMA_MALE_5",
		"Thiha"),
		("LOC_CITIZEN_SUK_BURMA_MALE_6",
		"Zeya"),
		("LOC_CITIZEN_SUK_BURMA_MALE_7",
		"Wunna"),
		("LOC_CITIZEN_SUK_BURMA_MALE_8",
		"Aung"),
		("LOC_CITIZEN_SUK_BURMA_MALE_9",
		"Arun"),
		("LOC_CITIZEN_SUK_BURMA_MALE_10",
		"Nyunt"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_1",
		"Sanda"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_2",
		"Thanda"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_3",
		"Thiri"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_4",
		"Kay"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_5",
		"Yadanar"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_6",
		"Htay"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_7",
		"Myitzu"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_8",
		"Marlar"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_9",
		"Thinzar"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_10",
		"Phone"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_1",
		"Aung Min"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_2",
		"Myint Nyan"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_3",
		"Khin Nyunt"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_4",
		"Than Paing"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_5",
		"Swe Lin Aung"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_6",
		"Than Toe Aung"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_7",
		"Aung Kyaw Oo"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_8",
		"Win Min Htut"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_9",
		"Maung Maung Lwin"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_10 ",
		"Hlaing Bo Bo"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_1",
		"Ye Lay"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_2",
		"Khin Kyi"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_3",
		"Thynn Lei Nwe"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_4",
		"Aye Aye Thant"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_5",
		"Thein Tin"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_6",
		"May Myat Noe"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_7",
		"San San Htwe"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_8",
		"Aye Thiri"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_9",
		"Khin Phyu"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_10",
		"May Htun"),
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_BURMA_LOCATION",
		"Asia"),
		("LOC_CIVINFO_SUK_BURMA_SIZE",
		"Est. 261 thousand square miles (676 thousand square km)"),
		("LOC_CIVINFO_SUK_BURMA_POPULATION",
		"51.5 million (2014 est.)"),
		("LOC_CIVINFO_SUK_BURMA_CAPITAL",
		"Various, including Pagan, Pegu, Ava, Rangoon and Naypyidaw"),
--------------------------------------------------------------------
-- Named Places
--------------------------------------------------------------------
		("LOC_NAMED_RIVER_CHINDWIN_NAME",			"Chindwin River"),
		("LOC_NAMED_RIVER_N_MAI_NAME",				"N'Mai River"),
		("LOC_NAMED_RIVER_SITTAUNG_NAME",			"Sittaung River"),
		("LOC_NAMED_MOUNTAIN_PEGU_NAME",			"Pegu Range"),
		("LOC_NAMED_MOUNTAIN_SHAN_HILLS_NAME",		"Shan Hills"),
		("LOC_NAMED_MOUNTAIN_KAREN_HILLS_NAME",		"Karen Hills"),
		("LOC_NAMED_MOUNTAIN_NAGA_HILLS_NAME",		"Naga Hills"),
		("LOC_NAMED_MOUNTAIN_TENASSERIM_NAME",		"Tenasserim Range"),
		("LOC_NAMED_MOUNTAIN_KACHIN_HILLS_NAME",	"Kachin Hills"),
		("LOC_NAMED_MOUNTAIN_DAWNA_NAME",			"Dawna Range"),
		("LOC_NAMED_VOLCANO_POPA_NAME",				"Mount Popa"),
------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_1",
		"This is Burma', wrote Rudyard Kipling. 'It will be quite unlike any land you know about.' This statement has rung too true over the years as Burma's history blazed a trail of glorious dynasties, colonial struggles and political conflict over the centuries of its existence."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_2",
		"Between the 1st century BC and the 9th century AD, speakers of Tibeto-Burman languages known as the Pyu established city-kingdoms in Burma at Binnaka, Mongamo, Shri Kshetra, and Halingyi. At the time, a long-standing trade route between China and India passed through northern Burma and then across the Chindwin River valley to the west. Chinese historical records noted that the Pyu claimed sovereignty over 18 kingdoms, many of them in the southern portions of Burma."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_3",
		"To the south of the Pyu lived the Mon, who were speakers of an Austroasiatic language. The Mon were closely related to the Khmer, who lived to the east of the Mon in what is now Cambodia. The capital of the Mon probably was the port of Thaton, which was located northwest of the mouth of the Salween River and not far from the portage routes of the Malay Peninsula."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_4",
		"A kingdom grew out of a small 9th-century settlement at Pagan by the Mranma, who had recently entered the Irrawaddy. Over the next two hundred years, the small principality gradually grew to absorb its surrounding regions until the 1050s and 1060s when King Anawrahta founded the Pagan Empire, for the first time unifying under one polity the Irrawaddy valley and its periphery."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_5",
		"Anawrahta greatly expanded his empire, with campaigns in the Shan Hills, and extended conquests to Lower Burma down to the Tenasserim coast to Phuket and North Arakan. Estimates of the extent of his empire vary greatly. The Burmese and Siamese chronicles report an empire which covered the present-day Burma and northern Thailand."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_6",
		"By the late 12th century Anawrahta's successors had extended their influence farther to the south into the upper Malay peninsula, to the east at least to the Salween river, in the farther north to below the current China border, and to the west, in northern Arakan and the Chin Hills. In the 12th and 13th centuries, Pagan, alongside the Khmer Empire, was one of two main empires in mainland Southeast Asia. The Burmese language and culture gradually became dominant in the upper Irrawaddy valley, eclipsing the Pyu, Mon and Pali norms by the late 12th century. By then, the Burman leadership of the kingdom was unquestioned. The Pyu had largely assumed the Burman ethnicity in Upper Burma. The Burmese language, once an alien tongue, was now the lingua franca of the kingdom. The Mongols began their invasion of Burma in 1277, and sacked Pagan, ending the Pagan kingdom's 250-year rule of the Irrawaddy valley and its periphery. Pagan's rule of central Burma came to an end ten years later when it was toppled by Myinsaing."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_7",
		"After the fall of Pagan, the Mongols left the searing Irrawaddy valley but the Pagan Kingdom was irreparably broken up into several small kingdoms. By the mid-14th century, the country had become organized along four major power centers: the Ava, Hanthawaddy Pegu, Shan States and Arakan. Many of the power centres were themselves made up of (often loosely held) minor kingdoms or princely states. This era was marked by a series of wars and switching alliances. Smaller kingdoms played a precarious game of paying allegiance to more powerful states, sometimes simultaneously."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_8",
		"Beginning in the 1480s, Ava faced constant internal rebellions and external attacks from the Shan States, and began to disintegrate. In 1510, Toungoo, located in the remote southeastern corner of the Ava kingdom, also declared independence. When the Confederation of Shan States conquered Ava in 1527, many Burmans fled southeast to Toungoo, the only kingdom remaining under Burman rule, and one surrounded by larger hostile kingdoms. Toungoo, led by Tabinshwehti and Bayinnaung, would go on to reunify the petty kingdoms that had existed since the fall of the Pagan Empire, and found the largest empire in the history of Southeast Asia. Conquering Hanthawaddy, Ava, the Shan States, Siam, Manipur, Lan Xang and Lanna; bringing much of western and central mainland Southeast Asia under his rule."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_9",
		"The overextended empire unraveled soon after Bayinnaung's death in 1581. Siam broke away in 1584 and went to war with Burma. By 1593, the kingdom had lost its possessions in Siam, Lang Xang and Manipur. By 1597, all internal regions, including the city of Toungoo had revolted. In 1599, the Arakanese forces aided by Portuguese mercenaries and the rebellious Toungoo forces sacked Pegu. The country fell into chaos, with each region claiming a king. Portuguese mercenary Filipe de Brito e Nicote promptly rebelled against his Arakanese masters, and established Goa-backed Portuguese rule at Thanlyin in 1603."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_10",
		"The Taungoo rulers withdrew from southern Burma and founded a second dynasty at Ava, the Nyaungyan dynasty or Restored Taungoo dynasty (1597–1752). Bayinnaung's grandson, Anaukpetlun, once again reunited Burma in 1613 and decisively defeated Portuguese attempts to take over Burma, but the empire gradually disintegrated. Anaukpetlun's successor Thalun rebuilt the war torn country. The Taungoo dynasty survived for another century and a half, until the death of Mahadammayaza in 1752. Encouraged by the French in India, Hanthawaddy rebelled against Taungoo, further weakening the state, which fell in 1752."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_11",
		"Soon after the fall of the Taungoo Dynasty, a new dynasty rose in Shwebo to challenge the authority of Hanthawaddy. Over the next 70 years, the highly militaristic Konbaung dynasty went on to create the largest Burmese empire, second only to the empire of Bayinnaung. By 1759, King Alaungpaya's Konbaung forces had reunited all of Burma (and Manipur), extinguished the Mon-led Hanthawaddy dynasty once and for all, and driven out the European powers who provided arms to Hanthawaddy. The Konbaung Dynasty proceeded to go to war and subdue Siam; however they soon found themselves defending against Qing China; holding their own and resulting in ""the most disastrous frontier war the Qing dynasty had ever waged"". The Siamese used the Burmese preoccupation with China to recover their lost territories by 1770, and in addition, went on to capture much of Lan Na by 1776, ending over two centuries of Burmese suzerainty over the region. Burma and Siam went to war again in 1785–1786, 1787, 1792, 1803–1808, 1809–1812 and 1849–1855 but all resulted in a stalemate. After decades of war, the two countries essentially exchanged Tenasserim (to Burma) and Lan Na (to Siam)."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_12",
		"Faced with a powerful China in the northeast and a resurgent Siam in the southeast, King Bodawpaya turned westward for expansion. He conquered Arakan in 1785, annexed Manipur in 1814, and captured Assam, leading to a long ill-defined border with British India. Bodawpaya's successor King Bagyidaw was left to put down British instigated rebellions in Manipur and Assam. Cross-border raids by rebels from the British protected territories and counter-cross-border raids by the Burmese led to the First Anglo-Burmese War. The war was the longest and most expensive war in British Indian history, but ended in a decisive British victory. Burma ceded all of Bodawpaya's western acquisitions (Arakan, Manipur and Assam) plus Tenasserim. Burma was crushed for years by repaying a large indemnity of one million pounds. In 1852, the British unilaterally and easily seized the Pegu province in the Second Anglo-Burmese War. After the war, King Mindon tried to modernize the Burmese state and economy, and made trade and territorial concessions to stave off further British encroachments. Nonetheless, the British, alarmed by the consolidation of French Indochina, annexed the remainder of the country in the Third Anglo-Burmese War in 1885, and sent the last Burmese king Thibaw and his family to exile in India."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_13",
		"Britain made Burma a province of India in 1886, with its capital at Rangoon, and ushered in a new period of economic growth. Traditional Burmese society was drastically altered by the demise of the monarchy and the separation of religion and state. Though war officially ended after only a couple of weeks, resistance continued in northern Burma until 1890, with the British finally resorting to a systematic destruction of villages and appointment of new officials to finally halt all guerrilla activity. Intermarriage between Europeans and Burmese gave birth to an indigenous Eurasian community known as the Anglo-Burmese who would come to dominate the colonial society, hovering above the Burmese but below the British. The economic nature of society also changed dramatically. After the opening of the Suez Canal, the demand for Burmese rice grew and vast tracts of land were opened up for cultivation. However, in order to prepare the new land for cultivation, farmers were forced to borrow money from Indian moneylenders called chettiars at high interest rates and were often foreclosed on and evicted losing land and livestock. Most of the jobs also went to indentured Indian labourers, and whole villages became outlawed as they resorted to 'dacoity' (armed robbery). While the Burmese economy grew, all the power and wealth remained in the hands of several British firms and migrants from India. The civil service was largely staffed by Anglo-Burmese and Indians, and Burmese were excluded almost entirely from military service, which was staffed primarily with Indians, Anglo-Burmese, Karens and other Burmese minority groups. Though the country prospered, the Burmese people failed to reap the rewards."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_14",
		"During the 1920s, the first protests by Burma's intelligentsia and Buddhist monks were launched against British rule. By 1935, the Students Union at Rangoon University was at the forefront of what would evolve into an active and powerful movement for national independence. A young law student Aung San, executive-committee member and magazine editor for the Students Union, emerged as the potential new leader of the national movement. In the years that followed, he successfully organized a series of student strikes at the university, gaining the support of the nation. At the outbreak of the Second World War, Aung San seized the opportunity to bring about Burmese independence. He and 29 others, known as the Thirty Comrades, left Burma to undergo military training in Japan. In 1941, they fought alongside the Japanese who invaded Burma. The Japanese promised Aung San that if the British were defeated, they would grant Burma her freedom. When it became clear that the Japanese would not follow through with their promise, Aung San quickly negotiated an agreement with the British to help them defeat the Japanese. Hailed as the architect of Burma's new-found independence by the majority of Burmese, Aung San was able to negotiate an agreement in January 1947 with the British, under which Burma would be granted total independence from Britain. Although a controversial figure to some ethnic minorities, he also had regular meetings with ethnic leaders throughout Burma in an effort to bring about reconciliation and unity for all Burmese."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_15",
		"As the new leader drafted a constitution with his party's ministers in July 1947, the course of Burmese history was dramatically and tragically altered. Aung San and members of his newly-formed cabinet were assassinated when an opposition group with machine guns burst into the room. A member of Aung San's cabinet, U Nu, was delegated to fill the position suddenly left vacant by Aung San's death. Burma was finally granted independence on January 4, 1948, at 4:20am. For the next ten years, Burma's fledging democratic government was continuously challenged by communist and ethnic groups who felt under-represented in the 1948 constitution. Periods of intense civil war destabilized the nation. Although the constitution declared that minority states could be granted some level of independence in ten years, their long-awaited day of autonomy never arrived. As the economy floundered, U Nu was removed from office in 1958 by a caretaker government led by General Ne Win, one of Aung San's fellow thakins. In order to ""restore law and order"" to Burma, Ne Win took control of the whole country including the minority states, forcing them to remain under the jurisdiction of the central government. Although he allowed U Nu to be re-elected Prime Minister in 1960, two years later he staged a coup and solidified his position as Burma's military dictator."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_16",
		"Ne Win's new Revolutionary Council suspended the constitution and instituted authoritarian military rule. Full attention turned to the military defeat of communist and ethnic-minority rebel groups. The country was closed off from the outside world as the new despot promoted an isolation ideology based on what he called the Burmese Way to Socialism. For the next three decades Ne Win set a thriving nation on a disastrous path of cultural, environmental and economic ruin. Outside visitors were few and restricted to Rangoon, Mandalay and a handful of other tightly controlled towns close to the central plains. Insurgency remained endemic and in many areas of Burma armed struggle became a way of life. In July 1988 Ne Win suddenly announced that he was preparing to leave the stage. Seeing at last a possible escape from military rule, economic decline and routine human rights abuses, thousands of people took to the streets of Rangoon. Demonstrations broke out across the country during the so-called ""Democracy Summer"" that followed. But on August 8, 1988 troops began a four day massacre, firing into crowds of men, women and children gathered in Rangoon. At least 10,000 demonstrators were killed across the country. Thousands of students and democracy advocates fled to the border regions under ethnic control and forged alliances with ethnic resistance movements. Some of these groups include the National Coalition Government of the Union of Burma (NCGUB), the All Burma Student Democratic Front, the Democratic Alliance of Burma, and the longstanding National Democratic Front situated in Manerplaw (the former headquarters of the Karen National Union which fell to SLORC in January 1995). Together these groups formed the National Council of the Union of Burma, an umbrella organization representing all the groups."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_17",
		"During this time of unrest in 1988, Aung San Suu Kyi, daughter of independence hero Aung San, who had been living abroad, returned to Burma to care for her ailing mother. Her devotion kept her there and brought her into the political foray. Attempting to quell international condemnation for its violence, the military announced it would hold multi-party elections. Under the persuasion of students and others opposed to the regime, Aung San Suu Kyi and like-minded colleagues founded the National League for Democracy (NLD). Her party quickly gathered country-wide support. Just when democratic changes seemed imminent Ne Win commandeered the army from behind the scenes to take over the country in a staged ""coup"". On September 18, 1988, control of the country was handed to a 19-member State Law and Order Restoration Council (SLORC) and a vicious crackdown followed. Although committed to non-violence, Aung San Suu Kyi was placed under house arrest in July 1989 for ""endangering the state"" and kept there for the next six years. Desperate to improve their image and generate foreign investment, the SLORC went ahead on May 27, 1990 and held the multi-party elections they had promised. Despite the SLORC's severe repression against members of opposition parties (Aung San Suu Kyi was kept under house arrest) and the complete lack of freedom of expression throughout the country, Suu Kyi's NLD party won with 82% of the vote. Surprised and outraged, the SLORC refused to acknowledge the election results and has retained its repressive grip on power."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_18",
		"Even though Aung San Suu Kyi was released from house arrest in May of 2002, the military has refused to relinquish power. The generals have not engaged in any sort of dialogue. The humanitarian situation in Burma is disastrous and civil war still ravages the border areas. The effect of military rule has been a severely impoverished and underdeveloped nation, Burma has been rated as the second least developed nation on the United Nations Development Index. Peace, democracy and the most basic human rights do not exist. Millions have been forced to flee due to military rule and are scattered all over the world, longing for the day when they can return to their homeland and be re-united with the families and live in peace."),				
--========================================================================================================================
-- Myinsi
--========================================================================================================================
		("LOC_UNIT_SUK_MYINSI_NAME",  
		"Myinsi"	),
		("LOC_UNIT_SUK_MYINSI_DESCRIPTION",  
		"Burmese unique Renaissance Era heavy cavalry unit. +3 [ICON_Strength] Combat Strength while it is occupying or is adjacent to a district, and an additional +3 [ICON_Strength] if that district is a City Center or an Encampment."),
		("LOC_UNIT_SUK_MYINSI_DESCRIPTION_XP2",  
		"Burmese unique Renaissance Era unit that replaces the Cuirassier. Slightly weaker than the Cuirassier, but unlocks earlier, and requires no resources. +3 [ICON_Strength] Combat Strength while it is occupying or is adjacent to a district, and an additional +3 [ICON_Strength] if that district is a City Center or an Encampment."),

		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_MYINSI_CHAPTER_HISTORY_PARA_1",  
		"A Myinsi is a Burmese Cavalry officer, typically in charge of a group of 50 or so cavalrymen. From the 17th century onward, cavalry troops made up about 10% of a typical regiment. The men of the cavalry were drawn mainly from hereditary villages in Upper Burma."),

		("LOC_ABILITY_MYINSI_DISTRICT_COMBAT_MODIFIER_DESCRIPTION",  
		"+{1_Amount} Combat Strength when occupying or adjacent to a district"	),
		("LOC_ABILITY_MYINSI_ENCAMPMENT_OR_CITY_COMBAT_MODIFIER_DESCRIPTION",  
		"+{1_Amount} Combat Strength when occupying or adjacent a City Center or an Encampment"	),		
--========================================================================================================================
-- Paya
--========================================================================================================================
		("LOC_IMPROVEMENT_SUK_PAYA_NAME",  
		"Paya"	),
		("LOC_IMPROVEMENT_SUK_PAYA_DESCRIPTION",  
		"Unlocks the Builder ability to construct a Paya, unique to Burma.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture, +1 [ICON_PRODUCTION] Production. +1 [ICON_Culture] Culture if adjacent to a Farm. Newly trained land units in the city gain +1 [ICON_Strength] Combat Strength for each Paya. Can only be built on Grassland, Grassland Hills, Plains, or Plains Hills. Cannot be built next to another Paya."),
		("LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_SUK_PAYA_CHAPTER_HISTORY_PARA_1",  
		"Pagodas feature prominently in Myanmar's landscape, earning the country the moniker ""Land of Pagodas."" Several cities in the country, including Mandalay and Bagan, are known for their abundance of pagodas. In the Burmese language, pagodas are known by a number of various terms, prominently the umbrella term Paya, which derives from Sanskrit vara, refers to pagodas, images of the Buddha, as well as royal and religious personages, including the Buddha, kings, and monks."),		
		("LOC_IMPROVEMENT_SUK_PAYA_COMBAT_MODIFIER_DESCRIPTION",  
		"+{1_Amount} Combat Strength from a Paya"	),	
--========================================================================================================================
-- Bayinnaung
--========================================================================================================================
		("LOC_LEADER_SUK_BAYINNAUNG_NAME",  
		"Bayinnaung"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_ALLEGIANCE_AND_OBLIGATION_NAME",  
		"Allegiance and Obligation"	),
		("LOC_TRAIT_LEADER_SUK_ALLEGIANCE_AND_OBLIGATION_DESCRIPTION",  
		"+3 [ICON_Gold] Gold from all city-states you're Suzerain of, and city-states provide a free heavy cavalry unit the first time you become their Suzerain."), 
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_VICTOR_OF_TEN_DIRECTIONS_NAME",  
		"Victor of Ten Directions"	),
		("LOC_AGENDA_SUK_VICTOR_OF_TEN_DIRECTIONS_DESCRIPTION",  
		"Wants to conquer all civilizations he shares a continent with, unless they own cities captured from other civilizations. Respects civilizations with captured cities."	),

		("LOC_DIPLO_KUDO_LEADER_SUK_BAYINNAUNG_REASON_ANY",  
		"(You own captured cities.)"	),
		("LOC_DIPLO_MODIFIER_SUK_VICTOR_OF_TEN_DIRECTIONS_KUDOS",  
		"Bayinnaung respects your imperial ambitions"	),

		("LOC_DIPLO_WARNING_LEADER_SUK_BAYINNAUNG_REASON_ANY",  
		"(You are on the same continent and don't own any captured cities.)"	),
		("LOC_DIPLO_MODIFIER_SUK_VICTOR_OF_TEN_DIRECTIONS_WARNING",  
		"Bayinnaung believes you are in the way of Burmese expansion"	),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SUK_BURMA",
		"U"),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_SUK_BURMA",
		"Sawbwa"),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_SUK_BURMA",
		"Min"),

		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_SUK_BURMA",
		"Boh"),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SUK_BURMA",
		"Wungyi"),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_SUK_BURMA",
		"Thămăda"),

		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_SUK_BURMA",
		"Thămăda"),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_BURMA",
		"Min"),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SUK_BURMA",
		"Hmumet"),

		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_SUK_BURMA",
		"Thămăda"),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_SUK_BURMA",
		"Okkăhta"),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_SUK_BURMA",
		"Bogyoke"),			
		
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SUK_BURMA",
		"Sekyawaddy"),																					
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_BAYINNAUNG",  
		"Step forth King Bayinnaung! Bend the nations around you into submission! Through diplomacy and stength of arms you will force the kings of the world into loyalty, and the tribute they pay you will spur your soldiers ever onwards. With their allegiance and obligation you will spread Burma's glory across the globe!"  	),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"That's rather disappointing."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"I am honored."),
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"You show great potential. Let us work together in friendship!"),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"No, first you must prove yourself."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"I am honored."),
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"I have thought long and hard. It is time you join the ranks of my many vassals."),
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Another betrayal? This is proof I am too trusting"),
		("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"My vassals seem to have failed me. I congratulate you on your victory."),
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"My vassals seem to have failed me. I congratulate you on your victory."),
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"I send an image of the lord Buddha for your people, and a longyi for yourself."),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"I cannot accept."),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Thank you. Tribute for Burma is always welcome."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"I really should come in and depose you. You are not fit to rule. (Denounces You)"),
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"Another betrayal. This is proof I am too trusting."),
		("LOC_DIPLO_FIRST_MEET_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"You have the honour of meeting the King of Burma, Bayinnaung Kyawhtin Nawratha. Prove to me your strength, and perhaps we can be allies."),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"I have a city nearby, although come to think of it I'm unsure if it's mine or my vassal's city."),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Wonderful."),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Workmen are just putting the finishing touches on my palace. I invite you to see its splendour."),
		("LOC_DIPLO_GREETING_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Hail."),
		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Be warned. Your puny nation stands in the way of Burma's glory."),
		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"I have been watching your conquests with great interest. They are impressive indeed."),
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"Ally with me! Your strength is admirable!"),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"{LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY}"),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"{LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY}"),
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"Well fought. We have both earned this peace."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"No. I cannot accept."),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"Enough, you have proven your mettle. Let us end this."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"You may, but do not linger."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"What general would permit such a liability?"),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"I demand passage through your lands. It is a matter of vital importance."),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"If you are trying to intimidate us with your army, it’s not working. Move them, or face the consequences."),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_BAYINNAUNG_QUOTE",  
		"As long as they have the four white elephants, Burma and Ayutthaya will be like water and earth."  	),
		("LOC_PEDIA_LEADERS_PAGE_SUK_BAYINNAUNG_TITLE",
		"Bayinnaung"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_BAYINNAUNG_SUBTITLE",
		"King of Burma"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_CAPSULE_BODY",
		"The Burmese empire is one where culture and faith work to support a army without parallel. Bayinnaung bends city-states to his will to enhance Burma's military might."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_DETAILED_BODY",
		"Burma is an initially very flexible civ, building Holy Sites, Theater Squares, or Encampments will provide a small boost to [ICON_Faith] Faith and [ICON_Culture] Culture that scales to your current output, helping you from lagging behind when you use the second part of their unique ability to quickly build up an army. Payas further boost your culture and military might, providing [ICON_Culture] Culture and increasing your army's strength. Under Bayinnaung, city-states will quickly prove valuable vassals, providing a Heavy Cavalry unit as a levy and providing [ICON_Gold] as tribute in addition to the usual bonuses they provide."),		
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_1",
		"Considered one of the three greatest kings of Burma, along with Anawrahta and Alaungpaya, Bayinnaung Kyawhtin Nawrahta was king of Toungoo Dynasty of Burma from 1550 to 1581. During his 31-year reign, which has been called the “greatest explosion of human energy ever seen in Burma”, Bayinnaung assembled the largest empire in the history of Southeast Asia, which included much of modern-day Burma, Chinese Shan states, Lan Na, Lan Xang, Manipur and Siam."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_2",
		"On 30 April 1550, Bayinnaung’s predecessor and brother-in-law Tabinshwehti was assassinated by his own bodyguards on the order of Smim Htaw, one of the king’s close advisers. Smim Htaw naturally proclaimed himself king. But so did all other major governors and viceroys—including Bayinnaung’s own brother Minkhaung II. Although Bayinnaung had been Tabinshwehti’s chosen heir apparent since 1542, none of them acknowledged Bayinnaung as the rightful successor. The Toungoo Empire, which Bayinnaung had helped forge for the last 16 years, lay in ruins. Bayinnaung, as a colonial era historian noted, was “a king without a kingdom”."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_3",
		"Bayinnaung marched south, captured the city of Pegu, and executed the rebel leader, Smim Htaw. The other Mon rulers then surrendered, and the revolt was at an end. Bayinnaung made Pegu his capital, as Tabinshwehti had. Bayinnaung then set out against Shan chiefs, who occupied the ancient Burmese capital of Ava. He captured it the following year. The Shans were placed under Burmese suzerainty, and Bayinnaung was consequently in a position to attack his most powerful enemy, Siam."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_4",
		"In 1563 Bayinnaung took as a pretext for war the refusal of the Siamese to acknowledge his suzerainty. The following year he captured the Siamese capital of Ayutthaya and brought the Siamese royal family to Burma as hostages. In 1568, when a revolt flared up, Bayinnaung again invaded Siam. Because the Siamese put up fierce resistance, Ayutthaya was not captured until August 1569. Bayinnaung installed a new vassal on the throne and deported thousands of Siamese into Burma as slaves. The Burmese would dominate Siam for more than 15 years."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_5",
		"The year was 1576 and the states Bayinnaung had conquered had all quieted down and stabilised. Many rival kingdoms in the area were eager to have his support. Bayinnaung saw himself as the protector of Theravada Buddhism and had assembled the largest empire in Indochinese history spanning from Manipur to Cambodian and Yunnan. It was entirely possible that he had also been continuously receiving homage from Vietnam and Cambodia. Bayinnaung started his reign as a king without a kingdom, and ruled as an emperor without an empire. He did not annex lands, but simply conquered their kings. The empire was held together not by any formal institution of power, but by personal relationships with the vassal kings and queens. He presented himself as the Sekyawaddy, the Universal Ruler and ruled the empire on the basis of Thitsa and Kyaezu: Allegiance and Obligation. Bayinnaung personally only ever ruled Pegu directly."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_6",
		"This decentralised system meant that Bayinnaung only introduced reforms at the margins and let the local rulers rule as they had before. From the sheer size of the empire, this was the only way Bayinnaung could retain power. Perhaps the most important reform that Bayinnaung introduced was that of administering the Shan Saophas. He regularly removed the Saopha (king) for gross misconducts and chose a successor from the Saopha’s family. He also required that the sons of all his vassal rulers be taught and trained in Pegu. This served both to create a hostage situation should a rebellion occur, but also to introduce Burmese court culture to their vassal states in the future. Although the empire would quickly fall apart after his death, the system continued with the Shan states so much so that it brought an end to the constant Shan raids that had plagued prior kings."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_7",
		"Bayinnaung also standardised the legal code in much of his empire by prescribing an official collection of law books: the Dhammathat Kyaw and Kothaungchok. The new legal system was adopted and modified to be compatible with local practices, but was ultimately a large standardisation in law. Bayinnaung also promoted a standardised set of measurements: using the Burmese customary units across the empire. To this day, Burma still uses many of Bayinnaung’s units. The Burmese Calendar was also adopted in Siam and some regions of other parts of Southeast Asia until the 19th century."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_8",
		"Another enduring legacy of Bayinnaung was his introduction of a more orthodox Theravada Buddhism to Upper Burma and the Shan states. He propagated the religious reforms begun by King Dhammazedi in the late 1470s. Viewing himself as the “model Buddhist king,” the king distributed copies of the scriptures, fed monks, and built pagodas at every new conquered state from Upper Burma and Shan states to Lan Na and Siam. He prohibited all human and animal sacrifices throughout the kingdom. In particular, he forbade the Shan practice of killing the slaves and animals belonging to a saopha at his funeral. His attempts to rid of animist nat worship from Buddhism, however, failed."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_9",
		"By 1580, not only had the Bayinnaung subdued all the countries which had occupied his attention for the last three decades but he also had the respect from neighboring states. He faced no internal or external threats. Instead of resting, he turned his gaze on Arakan, the kingdom he and Tabinshwehti unsuccessfully tried to conquer in 1545–1547. He determined that it was now time to reduce the western coastal kingdom to the vassal status it held under the Pagan kings once more. The king sent an 8000-strong naval invasion force on 15 October 1580. The naval fleet, which consisted of 200 ships, went on to occupy Sandoway in November 1580. The king had probably planned to lead the assault on the Arakanese capital Mrauk-U by himself but could not because of his failing health. The invasion force remained inactive at Sandoway for a year. The king sent additional land and naval forces (29,000 troops, 1600 horses, 120 elephants) on 28 August 1581 in preparation for the coming dry season campaign. But the king died six weeks later, and the invasion forces withdrew soon after."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_10",
		"His eldest son and heir-apparent Nanda took over the throne without incident. But the empire, which Bayinnaung had built on military conquests and maintained by both military power and personal relationships with the vassal rulers, was to crumble soon after. The first crack appeared in the far north in September 1582 when Chinese Shan states of Sanda and Thaungthut revolted. The rebellion was put down in March 1583. Much more serious cracks followed. Ava (Upper Burma) revolted in October 1583, and the rebellion was put down on 24 April 1584. Siam revolted on 3 May 1584. Nanda would spend the rest of his reign fighting Siam and other former vassals and would lose the entire empire in the process by 1599.");			
--------------------------------------------------------------------
--------------------------------------------------------------------