--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- ETHIOPIA
--========================================================================================================================
-- Cities
--------------------------------------------------------------------
		("LOC_CITY_NAME_ETHIOPIA_ADDIS_ABABA",
		"Addis Ababa"),
		("LOC_CITY_NAME_ETHIOPIA_AXUM",
		"Axum"),
		("LOC_CITY_NAME_ETHIOPIA_LALIBELA",
		"Lalibela"),
		("LOC_CITY_NAME_ETHIOPIA_GONDAR",
		"Gondar"),
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_BERHAN",
		"Debre Berhan"),
		("LOC_CITY_NAME_ETHIOPIA_HARAR",
		"Harar"),
		("LOC_CITY_NAME_ETHIOPIA_DIRE_DAWA",
		"Dire Dawa"),
		("LOC_CITY_NAME_ETHIOPIA_ADWA",
		"Adwa"),
		("LOC_CITY_NAME_ETHIOPIA_BAHIR_DAR",
		"Bahir Dar"),
		("LOC_CITY_NAME_ETHIOPIA_ADAMA",
		"Adama"),
		("LOC_CITY_NAME_ETHIOPIA_MEKELE",
		"Mek’ele"),
		("LOC_CITY_NAME_ETHIOPIA_ADULIS",
		"Adulis"),
		("LOC_CITY_NAME_ETHIOPIA_AWASA",
		"Awasa"),
		("LOC_CITY_NAME_ETHIOPIA_JIMMA",
		"Jimma"),
		("LOC_CITY_NAME_ETHIOPIA_JIJIGA",
		"Jijiga"),
		("LOC_CITY_NAME_ETHIOPIA_DESSIE",
		"Dessie"),
		("LOC_CITY_NAME_ETHIOPIA_SHASHAMANE",
		"Shashamane"),
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_ZEYIT",
		"Debre Zeyit"),
		("LOC_CITY_NAME_ETHIOPIA_HOSAENA",
		"Hosaena"),
		("LOC_CITY_NAME_ETHIOPIA_SODO",
		"Sodo"),
		("LOC_CITY_NAME_ETHIOPIA_ASELLA",
		"Asella"),
		("LOC_CITY_NAME_ETHIOPIA_NEKEMTE",
		"Nekemte"),
		("LOC_CITY_NAME_ETHIOPIA_DILA",
		"Dila"),
		("LOC_CITY_NAME_ETHIOPIA_ADIGRAT",
		"Adigrat"),
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_MARKOS",
		"Debre Markos"),
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_TABOR",
		"Debre Tabor"),
		("LOC_CITY_NAME_ETHIOPIA_SHIRE",
		"Shire"),
		("LOC_CITY_NAME_ETHIOPIA_SEBETA",
		"Sebeta"),
		("LOC_CITY_NAME_ETHIOPIA_AMBO",
		"Ambo"),
		("LOC_CITY_NAME_ETHIOPIA_NEGELE_ARSI",
		"Negele Arsi"),
		("LOC_CITY_NAME_ETHIOPIA_GAMBELA",
		"Gambela"),
		("LOC_CITY_NAME_ETHIOPIA_ZIWAY",
		"Ziway"),
		("LOC_CITY_NAME_ETHIOPIA_WELDIYA",
		"Weldiya"),
		("LOC_CITY_NAME_ETHIOPIA_KOMBOLCHA",
		"Kombolcha"),
		("LOC_CITY_NAME_ETHIOPIA_ASAITA",
		"Asaita"),
		("LOC_CITY_NAME_ETHIOPIA_DELGHI",
		"Delghi"),
		("LOC_CITY_NAME_ETHIOPIA_ADDIS_ZEMEN",
		"Addis Zemen"),
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_WERQ",
		"Debre Werq"),
		("LOC_CITY_NAME_ETHIOPIA_DEJEN",
		"Dejen"),
		("LOC_CITY_NAME_ETHIOPIA_ARBOYE",
		"Arboye"),
		("LOC_CITY_NAME_ETHIOPIA_BICHENA",
		"Bichena"),
		("LOC_CITY_NAME_ETHIOPIA_BATI",
		"Bati"),
		("LOC_CITY_NAME_ETHIOPIA_DABAT",
		"Dabat"),
		("LOC_CITY_NAME_ETHIOPIA_MOJO",
		"Mojo"),
		("LOC_CITY_NAME_ETHIOPIA_NEGASH",
		"Negash"),
		("LOC_CITY_NAME_ETHIOPIA_KOBO",
		"Kobo"),
		("LOC_CITY_NAME_ETHIOPIA_DANGILA",
		"Dangila"),
		("LOC_CITY_NAME_ETHIOPIA_GORGORA",
		"Gorgora"),
		("LOC_CITY_NAME_ETHIOPIA_CHENCHA",
		"Chencha"),
		("LOC_CITY_NAME_ETHIOPIA_GELEMSO",
		"Gelemso"),
		("LOC_CITY_NAME_ETHIOPIA_SOKORU",
		"Sokoru"),
		("LOC_CITY_NAME_ETHIOPIA_IRGALEM",
		"Irgalem"),
		("LOC_CITY_NAME_ETHIOPIA_KEBRI_MANGEST",
		"Kebri Mangest"),
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_MARQOS",
		"Debre Marqos"),
		("LOC_CITY_NAME_ETHIOPIA_FINOTE_SELAM",
		"Finote Selam"),
		("LOC_CITY_NAME_ETHIOPIA_MOTA",
		"Mota"),
		("LOC_CITY_NAME_ETHIOPIA_KONSO",
		"Konso"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_1",
		"Zoskales"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_2",
		"Datawnas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_3",
		"Aphilas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_4",
		"Gersem"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_5",
		"Ousanas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_6",
		"Eon"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_7",
		"Tazena"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_8",
		"Wazena"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_9",
		"Beygat"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_10",
		"Sahama"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_1",
		"Gudit"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_2",
		"Makeda"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_3",
		"Berhane"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_4",
		"Masoba"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_5",
		"Bilén Saba"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_6",
		"Berhane"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_7",
		"Abebech"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_8",
		"Merima"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_9",
		"Mare"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_10",
		"Amane"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_1",
		"Yohannes"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_2",
		"Dawit"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_3",
		"Yaqob"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_4",
		"Tewodros"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_5",
		"Eskender"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_6",
		"Andreyas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_7",
		"Gelawdewos"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_8",
		"Giyorgis"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_9",
		"Salomon"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_10",
		"Mikael"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_1",
		"Maryam"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_2",
		"Yohanna"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_3",
		"Tereza"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_4",
		"Eleni"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_5",
		"Abebech"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_6",
		"Senedu"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_7",
		"Hibret"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_8",
		"Tirunesh"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_9",
		"Dina"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_10",
		"Israela"),
--------------------------------------------------------------------
-- Named Places
--------------------------------------------------------------------
		("LOC_NAMED_RIVER_TEKEZE_NAME",						"Tekezé River"),
		("LOC_NAMED_RIVER_OMO_NAME",						"Omo River"),
		("LOC_NAMED_RIVER_BARO_NAME",						"Baro River"),
		("LOC_NAMED_RIVER_AWASH_NAME",						"Awash River"),
		("LOC_NAMED_RIVER_SHEBELLE_NAME",					"Shebelle River"),
		("LOC_NAMED_RIVER_ANGEREB_NAME",					"Angereb River"),
		("LOC_NAMED_RIVER_GANALE_DORIA_NAME",				"Ganale Doria River"),
		("LOC_NAMED_RIVER_ABAY_NAME",						"Abay River"),
		("LOC_NAMED_RIVER_LESSER_ABAY_NAME",				"Lesser Abay River"),
		("LOC_NAMED_RIVER_DAWA_NAME",						"Dawa River"),
		("LOC_NAMED_RIVER_WEYIB_NAME",						"Weyib River"),

		("LOC_NAMED_MOUNTAIN_ETHIOPIAN_HIGHLANDS_NAME",		"Ethiopian Highlands"),
		("LOC_NAMED_MOUNTAIN_SEMIEN‎_NAME",					"Semien Mountains‎"),
		("LOC_NAMED_MOUNTAIN_BALE‎_NAME",					"Bale Mountains‎"),
		("LOC_NAMED_MOUNTAIN_AHMAR_NAME",					"Ahmar Mountains"),
		("LOC_NAMED_MOUNTAIN_AMARO_NAME",					"Amaro Mountains"),
		("LOC_NAMED_MOUNTAIN_ENTOTO_NAME",					"Entoto Mountains"),
		("LOC_NAMED_MOUNTAIN_DANAKIL_ALPS_NAME",			"Danakil Alps"),

		("LOC_NAMED_VOLCANO_FENTALE_NAME",					"Mount Fentale"),
		("LOC_NAMED_VOLCANO_DABBAHU_NAME",					"Dabbahu Volcano"),
		("LOC_NAMED_VOLCANO_ALE_BAGU_NAME",					"Ale Bagu"),
		("LOC_NAMED_VOLCANO_AFDERA_NAME",					"Afderà Volcano"),
		("LOC_NAMED_VOLCANO_ALAYTA_NAME",					"Mount Alayta"),
		("LOC_NAMED_VOLCANO_AYALU_NAME",					"Mount Ayalu"),
		("LOC_NAMED_VOLCANO_GADA_ALE_NAME",					"Gada Ale"),
		("LOC_NAMED_VOLCANO_BORALE_ALE_NAME",				"Borale Ale"),
		("LOC_NAMED_VOLCANO_ASAVYO_NAME",					"Asavyo Volcano"),
		("LOC_NAMED_VOLCANO_BORAWLI_NAME",					"Borawli Volcano"),
		("LOC_NAMED_VOLCANO_ADWA_NAME",						"Adwa Volcano"),
		("LOC_NAMED_VOLCANO_TAT_ALI_NAME",					"Tat Ali"),
		("LOC_NAMED_VOLCANO_HAYLI_GUBBI_NAME",				"Hayli Gubbi"),
		("LOC_NAMED_VOLCANO_ASAVYO_NAME",					"Asavyo Volcano"),
		("LOC_NAMED_VOLCANO_WONCHI_NAME",					"Wonchi Volcano"),

		("LOC_NAMED_LAKE_ABAYA_NAME",						"Lake Abaya"),
		("LOC_NAMED_LAKE_ZWAY_NAME",						"Lake Zway"),
		("LOC_NAMED_LAKE_CHEW_BAHIR_NAME",					"Lake Chew Bahir"),
		("LOC_NAMED_LAKE_SHALA_NAME",						"Lake Shala"),
		("LOC_NAMED_LAKE_ABBE_NAME",						"Lake Abbe"),
		("LOC_NAMED_LAKE_CHAMO_NAME",						"Lake Chamo"),
		("LOC_NAMED_LAKE_LANGANO_NAME",						"Lake Langano"),
		("LOC_NAMED_LAKE_ABIJATTA_NAME",					"Lake Abijatta"),
		("LOC_NAMED_LAKE_HASHENGE_NAME",					"Lake Hashenge"),
		("LOC_NAMED_LAKE_HAYQ_NAME",						"Lake Hayq"),

		("LOC_NAMED_SEA_GULF_OF_ZULA_NAME",					"Gulf of Zula"),
		("LOC_NAMED_SEA_BAY_OF_BEYLUL_NAME",				"Bay of Beylul"),
		("LOC_NAMED_SEA_BAY_OF_HAWAKIL_NAME",				"Bay of Hawakil"),
		("LOC_NAMED_SEA_BAY_OF_ANFILE_NAME",				"Bay of Anfile"),
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_ETHIOPIA_LOCATION",
		"Africa"),
		("LOC_CIVINFO_SUK_ETHIOPIA_SIZE",
		"Est. 426 thousand square miles (1,104.3 thousand square km)"),
		("LOC_CIVINFO_SUK_ETHIOPIA_POPULATION",
		"99.4 million (2015 est.)"),
		("LOC_CIVINFO_SUK_ETHIOPIA_CAPITAL",
		"Various, with an iterant court in the Medieval period, but most prominently Axum, Lalibela, Gondar, and currently Addis Ababa."),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_1",
		"Home to ancient empires dating back to the waning centuries of the first millennium BC, Ethiopia has a storied history driven by the rule of great kings and emperors. As one of the few African nations to avoid the colonial ambitions of Europe, Ethiopia maintained its sovereignty into the 21st century, only briefly coming under Italian occupation for 8 years during WWII and its prelude."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_2",
		"Ethiopia, Africa's tenth largest nation, covers the majority of the Horn of Africa, nestled along the continent's northeastern coast. Bisected by the Great Rift Valley, Ethiopia's geography is dominated by highly elevated plateaus and disjointed mountain ranges. Sitting atop the African tectonic plate, which has been in the process of splitting apart for millions of years, Ethiopia has found itself on the receiving end of frequent earthquakes throughout history. The country is also home to several dozen active and dormant volcanoes, including Erta Ale, one of the few volcanoes in the world with an ever-present lake of lava on its summit. The climate of Ethiopia varies greatly, although the nation as a whole is part of a tropical zone with heavy rainfall during the summer monsoon season followed by a dry, moderate winter."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_3",
		"As the most advanced of the early Ethiopian kingdoms, the powerful Axumite Empire is well documented in history, but also steeped in legend. Founded in roughly the 4th century BC, Axum grew to become a powerful center of trade over the next five hundred years. The valuable commodities of frankincense and myrrh, harvested from trees prevalent in Ethiopia, brought great wealth to the city of Axum and its people. Through the exportation of these goods, plus lucrative trades in ivory and various precious metals, Axum became an integral part of the trade routes connecting Egypt, Rome, and India, enough so to facilitate the minting of currency within Axum to support the flourishing local economy."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_4",
		"Christianity was introduced into the country by Frumentius, who was consecrated first bishop of Ethiopia by Saint Athanasius of Alexandria about 330. Frumentius converted Ezana, who left several inscriptions detailing his reign both before and after his conversion. One inscription found at Axum, states that he conquered the nation of the Bogos, and returned thanks to his father, the god Mars, for his victory. Later inscriptions show Ezana's growing attachment to Christianity, and Ezana's coins bear this out, shifting from a design with disc and crescent to a design with a cross. Expeditions by Ezana into the Kingdom of Kush at Meroe in Sudan may have brought about its demise, though there is evidence that the kingdom was experiencing a period of decline beforehand. As a result of Ezana's expansions, Aksum bordered the Roman province of Egypt."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_5",
		"However, after centuries of prosperity, legends say the expansive empire's downfall came at the hands of a rebellious queen named Gudit. As the story goes, Axum had long been a stronghold of Christianity, and the Jewish queen Gudit sought the throne by way of conquest, purportedly devastating the countryside before murdering the royal family of Axum. Although the story of Gudit's life and brief reign is mysterious and controversial, it can be said with certainty that the decline of Axum did coincide with her speculated arrival in the 10th century AD."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_6",
		"The Zagwe Dynasty, established in the early 12th century after the fall of Axum, was the first dynasty of the Ethiopian Empire, which would control the nation well into the 20th century. Although the Zagwe Dynasty was only in power for little more than a century, they contributed greatly to the spread of Christianity throughout Ethiopia, which would play a major role in the future of the country."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_7",
		"In 1270 AD, the monarchy that would control Ethiopia for the coming centuries arose under the leadership of Emperor Yekuno Amlak, founder of the Solomonic Dynasty. The rulers of the Solomonic Dynasty attributed their lineage to the great biblical king Solomon and his queen, Makeda. As legend has it, in the 10th century BC, Queen Makeda travelled from her kingdom in Sheba (thought to have formed part of modern Ethiopia) to Israel in an effort to learn from the wisdom of revered king Solomon. Although accounts differ as to her relationship with Solomon, Makeda later gave birth to a son, Menelik. Said to have been educated in the court of Solomon before returning to Ethiopia, Menelik brought with him the legendary Ark of the Covenant as a gift from Solomon. Ruling sometime around 950 BC, Menelik I was the originator of the biblical ancestry held sacred by later Emperors of Ethiopia."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_8",
		"Nearly 2,000 years after the reign of Menelik, Yekuno Amlak claimed to have traced his ancestry through a long line of relatives to establish a clear connection to the legendary emperor and his parents. This newly formed Solomonic Dynasty maintained its rule over Ethiopia for more than five centuries, lasting until the reign of Haile Selassie in the 1970s. Fully supported by the influential Ethiopian Orthodox Church (which to this day still claims to be holding the legendary Ark of the Covenant), the Solomonic emperors enjoyed relative stability during their reign, despite several attempted incursions from outside the country."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_9",
		"During the mid-16th century, Ethiopia was bordered by the increasingly powerful Islamic Kingdom of Adal, led by Imam Ahmad Gargn, known colloquially as ""The Conqueror."" Initiating a holy war against the Christians of Ethiopia in 1529, Imam Ahmad spurred the great conflict that came to be known as the Ethiopian-Adal War. As battles raged for nearly 15 years, Ahmad was nearly successful in wiping out the entire kingdom, laying claim to vast swaths of Ethiopian territory."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_10",
		"After suffering such great losses, the Ethiopian Empire was forced to call on the assistance of Portuguese reinforcements to help in repelling the Islamic armies. Explorers and missionaries from Portugal had reached Ethiopia in the prior decades, intent on converting the populace to Roman Catholicism, and were fighting a war of their own against the Islamic Ottomans. After a prolonged conflict that eventually drew the Ottomans in to aid the Adals, the war was settled in 1543 following the deaths of both Imam Ahmad and the Portuguese general Cristovao da Gama. Ethiopia was left to recover from the war, but the rapid spread of Catholicism in the surrounding regions led to internal strife as the Ethiopian Orthodox Church struggled to maintain a firm grip on the nation."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_11",
		"The following period is known as the Zamana Mesafent, or ""Age of Princes"". Occuring in the 18th century, this period was marked by near constant turmoil within Ethiopia. The development of opposing religious factions, along with constant regional disputes, led to the collapse of central government control. As battles erupted between the princes, warlords, and nobility, each attempting to divide the region and increase their own power, the common people of Ethiopia were forced to endure the ravages of these futile conflicts."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_12",
		"The Emperor who finally brought an end to the Age of Princes, Kassa Hailu, first gained notoriety as an outlaw and highwayman. Assembling an army and amassing great wealth through his smuggling operations, Kassa Hailu gained popular support by sharing his riches with the poor. After uniting several of the decentralized provinces and gaining a strong following, Hailu was eventually crowned as Emperor Twedoros II in 1855. Following his coronation, Ethiopia as a whole stabilized, and his reign is considered by many to mark the beginnings of modern Ethiopia."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_13",
		"Ethiopia was never colonized by a European power, and the highlight of Ethiopia's stuggle to maintain its sovereignty during the colonial period is the reign of Menelik II. Emperor Menelik II reigned from 1889 to 1913, fending off the encroachment of European powers. Italy posed the greatest threat, having begun to colonize part of what would become its future colony of Eritrea in the mid 1880s. In 1896 Ethiopia defeated Italy at the Battle of Adwa, which remains famous today as the first victory of an African nation over a colonial power."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_14",
		"Perhaps the best remembered of Ethiopia's great emperors, Haile Selassie, ascended the throne in 1930 and quickly gained recognition throughout the world for Ethiopia and its people. During his reign he made a strong push for the abolition of slavery, a prospect that had been suggested, but never fulfilled, by his many predecessors. Emperor Selassie was also deeply concerned with modernizing his nation and ending many of the feudal policies that still held sway in Ethiopia."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_15",
		"In 1935, the Fascist Italian regime led by Benito Mussolini invaded Ethiopia in an attempt to claim the territory as a province of Italy. Facing a superior military force, Ethiopia was unable to repel the invasion, and by 1936, Mussolini had declared the establishment of an Italian Empire including the occupied Ethiopian territory. During this period, Haile Selassie was forced into exile, taking refuge in Great Britain throughout the occupation. Selassie made his case for the defense of Ethiopia to the League of Nations, including a stern reproach of Italy's use of mustard gas against Ethiopian soldiers and citizens alike. Despite his plea, international assistance was not forthcoming, and years passed before the British East African Campaign of World War II was successful in ending the Italian occupation. Haile Selassie returned to his throne as Emperor of Ethiopia following Italy's defeat, and he would rule successfully for nearly 40 years before the arrival of a new threat."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_16",
		"In 1974, a Communist-led military coup resulted in Haile Selassie's removal from power and imprisonment within the royal palace. The group deposing him, known as the Derg, formed the Provisional Military Government of Socialist Ethiopia and ruled with an iron fist. Selassie died mysteriously while imprisoned, a controversial subject that continues to stir debate today. As the Derg and their communist ideals were not universally supported, their military coup also marked the beginning of the Ethiopian Civil War. This great conflict claimed the lives of several hundred thousand innocent bystanders as fighting continued for over 15 years. In 1991, the Ethiopian People's Revolutionary Democratic Front was finally successful in overthrowing the government, leading to the creation of a new constitution and a democratically elected government."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_17",
		"Known today as the Federal Democratic Republic of Ethiopia, the nation faces a number of major socio-economic issues as the second most populous country in Africa. The wide-ranging geographic isolation facing some groups within the country has made it increasingly difficult to provide education, healthcare, and, in many cases, the basic necessities of life. Although the nation currently holds multiparty elections, corruption within the government is a constant concern, and crackdowns in recent years have led to international condemnation over the killing of protesters and opposition party members.");
--========================================================================================================================
--========================================================================================================================