--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- TIBET
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_TIBET_NAME",  
		"Tibet"	),
		("LOC_CIVILIZATION_SUK_TIBET_DESCRIPTION",  
		"Tibetan Empire"	),
		("LOC_CIVILIZATION_SUK_TIBET_ADJECTIVE",  
		"Tibetan"	),
		-- RWF
		("LOC_CIVILIZATION_SUK_TIBET_DESCRIPTION_JFD_CIVILIZATION",
		"Tibetan Civilization"),
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_DHARMA_KINGS_NAME",
		"Dharma Kings"),
		("LOC_TRAIT_CIVILIZATION_SUK_DHARMA_KINGS_DESCRIPTION",
		"When built next to a Mountain within your borders, Specialty Districts provide +2 of the appropriate yield and their buildings may be purchased with [ICON_Faith] Faith. Cities with an established Governor receive +5% [ICON_Faith] Faith for each promotion that Governor has."),				

		("LOC_TRAIT_CIVILIZATION_SUK_DHARMA_KINGS_NAME_XP2",  
		"Roof of the World"),
		("LOC_TRAIT_CIVILIZATION_SUK_DHARMA_KINGS_DESCRIPTION_XP2",  
		"Citizens may work Mountain tiles. Mountain tiles receive yields from districts within 2 tiles: +2 [ICON_Food] Food from City Centres, and +1 of the appropriate yield from other districts. May purchase buildings with [ICON_Faith] Faith in specialty districts next to Mountains. Cities with an established Governor receive +5% [ICON_Faith] Faith for each promotion that Governor has."),

		("LOC_CITY_YIELD_MODIFIER_PER_GOVERNOR_TITLE_TOOLTIP",  
		"{Value : number +#;-#}% ({ActualValue : number +#.#;-#.#}) from [ICON_Governor] Governor with {1} {1 : plural 1?Promotion; other?Promotions;}"),		
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------	
		("LOC_CITY_NAME_SUK_TIBET_LHASA",
		"Lhasa"),	
		("LOC_CITY_NAME_SUK_TIBET_ZHIKATSE",
		"Zhikatsé"),	
		("LOC_CITY_NAME_SUK_TIBET_GYANTSE",
		"Gyantsé"),	
		("LOC_CITY_NAME_SUK_TIBET_CHAMDO",
		"Chamdo"),	
		("LOC_CITY_NAME_SUK_TIBET_TSETANG",
		"Tsétang"),	
		("LOC_CITY_NAME_SUK_TIBET_SENGGE_KHABAP",
		"Senggé Khabap"),	
		("LOC_CITY_NAME_SUK_TIBET_PARO",
		"Paro"),	
		("LOC_CITY_NAME_SUK_TIBET_NAKCHU",
		"Nakchu"),	
		("LOC_CITY_NAME_SUK_TIBET_KYEGUDO",
		"Kyégudo"),	
		("LOC_CITY_NAME_SUK_TIBET_KHYUNGLUNG",
		"Khyunglung"),	
		("LOC_CITY_NAME_SUK_TIBET_DARTSEDO",
		"Dartsédo"),	
		("LOC_CITY_NAME_SUK_TIBET_NYINGTRI",
		"Nyingtri"),	
		("LOC_CITY_NAME_SUK_TIBET_NEDONG",
		"Nédong"),	
		("LOC_CITY_NAME_SUK_TIBET_TSOCHEN",
		"Tsochen"),	
		("LOC_CITY_NAME_SUK_TIBET_BARKHAM",
		"Barkham"),	
		("LOC_CITY_NAME_SUK_TIBET_SAKYA",
		"Sakya"),	
		("LOC_CITY_NAME_SUK_TIBET_KARDZE",
		"Kardzé"),	
		("LOC_CITY_NAME_SUK_TIBET_PEMBAR",
		"Pembar"),	
		("LOC_CITY_NAME_SUK_TIBET_LHATSE",
		"Lhatsé"),	
		("LOC_CITY_NAME_SUK_TIBET_GANGGA",
		"Gangga"),	
		("LOC_CITY_NAME_SUK_TIBET_MACHEN",
		"Machen"),	
		("LOC_CITY_NAME_SUK_TIBET_NAGORMO",
		"Nagormo"),	
		("LOC_CITY_NAME_SUK_TIBET_TAWANG",
		"Tawang"),	
		("LOC_CITY_NAME_SUK_TIBET_LE",
		"Lé"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_TIBET_MALE_1",
		"Tenzin"),
		("LOC_CITIZEN_SUK_TIBET_MALE_2",
		"Lhalu"),
		("LOC_CITIZEN_SUK_TIBET_MALE_3",
		"Yarphel"),
		("LOC_CITIZEN_SUK_TIBET_MALE_4",
		"Tenpa"),
		("LOC_CITIZEN_SUK_TIBET_MALE_5",
		"Tseten"),
		("LOC_CITIZEN_SUK_TIBET_MALE_6",
		"Rigzing"),
		("LOC_CITIZEN_SUK_TIBET_MALE_7",
		"Chhime"),
		("LOC_CITIZEN_SUK_TIBET_MALE_8",
		"Namgang"),
		("LOC_CITIZEN_SUK_TIBET_MALE_9",
		"Thondup"),
		("LOC_CITIZEN_SUK_TIBET_MALE_10",
		"Gyalo"),

		("LOC_CITIZEN_SUK_TIBET_FEMALE_1",
		"Machig"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_2",
		"Tsewang"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_3",
		"Chökyi"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_4",
		"Yeshe"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_5",
		"Nyendrak"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_6",
		"Orgyen"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_7",
		"Dechen"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_8",
		"Tubten"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_9",
		"Kelzang"),
		("LOC_CITIZEN_SUK_TIBET_FEMALE_10",
		"Ngapoi"),

		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_1",
		"Jigme"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_2",
		"Phuntsok"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_3",
		"Sangay"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_4",
		"Lobsang"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_5",
		"Karjam"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_6",
		"Choegyal"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_7",
		"Dondrup"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_8",
		"Tashi"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_9",
		"Dorjee"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_MALE_10",
		"Tobgyal"),

		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_1",
		"Sonam"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_2",
		"Wangmo"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_3",
		"Tsering"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_4",
		"Choden"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_5",
		"Ani"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_6",
		"Öser"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_7",
		"Phuntsog"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_8",
		"Choenyi"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_9",
		"Jetsun"),
		("LOC_CITIZEN_SUK_TIBET_MODERN_FEMALE_10",
		"Pema"),
--------------------------------------------------------------------
-- Named Places
--------------------------------------------------------------------
		("LOC_NAMED_RIVER_YARLUNG_TSANGPO_NAME",				"Yarlung Tsangpo River"),
		("LOC_NAMED_RIVER_PARLUNG_TSANGPO_NAME",				"Parlung Tsangpo River"),
		("LOC_NAMED_RIVER_LHASA_NAME",							"Lhasa River"),
		("LOC_NAMED_RIVER_NYANG_NAME",							"Nyang River"),
		("LOC_NAMED_MOUNTAIN_DANGLA_NAME",						"Dangla Mountains"),
		("LOC_NAMED_MOUNTAIN_TANIANTAWENG_NAME",				"Taniantaweng Mountains"),
		("LOC_NAMED_MOUNTAIN_NYENCHEN_TANGLHA_NAME",			"Nyenchen Tanglha Mountains"),
		("LOC_NAMED_MOUNTAIN_NALAKANKAR_HIMAL_NAME",			"Nalakankar Himāl"),
		("LOC_NAMED_MOUNTAIN_ROLWALING_HIMAL_NAME",				"Rolwāling Himāl"),
		("LOC_NAMED_MOUNTAIN_GANESH_HIMAL_NAME",				"Ganesh Himāl"),
		("LOC_NAMED_MOUNTAIN_NAMCHA_BARWA_HIMAL_NAME",			"Namcha Barwa Himāl"),
		("LOC_NAMED_MOUNTAIN_MAHALANGUR_HIMAL_NAME",			"Mahālangūr Himāl"),
		("LOC_NAMED_MOUNTAIN_KANGRI_GARPO_NAME",				"Kangri Garpo"),
		("LOC_NAMED_VOLCANO_ASHIKULE_VOLCANIC_FIELD_NAME",		"Ashikule Volcanic Field"),
		("LOC_NAMED_VOLCANO_BAMAOQIONGZONG_NAME",				"Bamaoqiongzong Volcano"),
		("LOC_NAMED_VOLCANO_YONGBOHU_NAME",						"Yongbohu Volcano"),
		("LOC_NAMED_VOLCANO_QIANGBAQIAN_NAME",					"Qiangbaqian Volcano"),	
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_TIBET_LOCATION",
		"Asia"),
		("LOC_CIVINFO_SUK_TIBET_SIZE",
		"Est. 474 thousand square miles (1.228 million square km)"),
		("LOC_CIVINFO_SUK_TIBET_POPULATION",
		"Est. 3.18 million (Dec 2014)"),
		("LOC_CIVINFO_SUK_TIBET_CAPITAL",
		"Lhasa"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_1",
		"The history of a unified Tibet begins with the rule of Songtsen Gampo (604–650 CE), who united parts of the Yarlung River Valley and founded the Tibetan Empire. He also brought in many reforms, and Tibetan power spread rapidly, creating a large and powerful empire. It is traditionally considered that his first wife was the Princess of Nepal, Bhrikuti, and that she played a great role in the establishment of Buddhism in Tibet. In 640 he married Princess Wencheng, the niece of the powerful Chinese emperor Taizong of Tang China, who herself was also Buddhist. The faith grew when an influx of Central Asian Buddhists flooded Tibet early in the eighth century, fleeing from advancing armies of Arab and Kazakh Muslims. Songtsen Gampo’s descendants would also conquer the vast region that is now the Chinese provinces of Qinghai, Gansu, and Xinjiang between 663 and 692. Control of these border regions would change hands back and forth for centuries to come."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_2",
		"Chinese power waxed strong in the early decades of the eighth century, and Imperial forces under General Gao Xianzhi conquered much of Central Asia, until their defeat by the Arabs and Karluks at the Battle of Talas River in 751. China's power quickly waned, and Tibet resumed control of much of Central Asia. Led by Trisong Detsen, the ascendant Tibetans pressed their advantage, conquering much of northern India and even seizing the Tang Chinese capital city of Chang’an (now Xi’an) in 763. Tibet and China signed a peace treaty in 821 or 822, which delineated the border between the two empires. The Tibetan Empire would concentrate on its Central Asian holdings for the next several decades, before splitting into several small, fractious kingdoms."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_3",
		"Canny politicians, the Tibetans befriended Genghis Khan just as the Mongol leader was conquering the known world in the early 13th century. As a result, though the Tibetans paid tribute to the Mongols after the Hordes had conquered China, they were allowed much greater autonomy than the other Mongol-conquered lands. Over time, Tibet came to be considered one of the thirteen provinces of the Mongolian-ruled nation of Yuan China. During this period, the Tibetans gained a high degree of influence over the Mongols at court. The great Tibetan spiritual leader, Sakya Pandita, became the Mongol's representative to Tibet. Sakya's nephew, Chana Dorje, married one of the Mongol Emperor Kublai Khan's daughters. The Tibetans transmitted their Buddhist faith to the eastern Mongols; Kublai Khan himself studied Tibetan beliefs with the great teacher Drogon Chogyal Phagpa."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_4",
		"When the Mongols' Yuan Empire fell in 1368 to the ethnic-Han Chinese Ming, Tibet reasserted its independence and refused to pay tribute to the new Emperor. In 1474, the abbot of an important Tibetan Buddhist monastery, Gendun Drup, passed away. A child who born two years later was found to be a reincarnation of the abbot, and was raised to be the next leader of that sect, Gendun Gyatso. After their lifetimes, the two men were called the First and Second Dalai Lamas. Their sect, the Gelug or “Yellow Hats”, became the dominant form of Tibetan Buddhism. The Third Dalai Lama, Sonam Gyatso (1543-1588), was the first to be so named during his life. He was responsible for converting the Mongols to Gelug Tibetan Buddhism, and it was the Mongol ruler Altan Khan who probably gave the title “Dalai Lama” to Sonam Gyatso. While the newly-named Dalai Lama consolidated the power of his spiritual position, though, the Gtsang-pa Dynasty assumed the royal throne of Tibet in 1562. The Kings would rule the secular side of Tibetan life for the next 80 years."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_5",
		"During the 1630s, China was embroiled in power struggles between the Mongols, Han Chinese of the fading Ming Dynasty, and the Manchu people of north-eastern China (Manchuria). The Manchus would eventually defeat the Han in 1644, and establish China's final imperial dynasty, the Qing (1644-1912). Tibet got drawn into this turmoil when the Mongol warlord Ligdan Khan, a Kagyu Tibetan Buddhist, decided to invade Tibet and destroy the Yellow Hats in 1634. Ligdan Khan died on the way, but his follower Tsogt Taij took up the cause. The great general Gushi Khan, of the Oirad Mongols, fought against Tsogt Taij and defeated him in 1637. The Khan killed the Gtsang-pa Prince of Tsang, as well. With support from Gushi Khan, the Fifth Dalai Lama, Lobsang Gyatso, was able to seize both spiritual and temporal power over all of Tibet in 1642."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_6",
		"The Potala Palace in Lhasa was constructed as a symbol of this new synthesis of power. The Dalai Lama made a state visit to the Qing Dynasty's second Emperor, Shunzhi, in 1653. The two leaders greeted one another as equals; the Dalai Lama did not kowtow. Each man bestowed honors and titles upon the other, and the Dalai Lama was recognized as the spiritual authority of the Qing Empire. Lobsang Gyatso died in 1682, but his Prime Minister concealed the Dalai Lama's passing until 1696 so that the Potala Palace could be finished and the power of the Dalai Lama's office consolidated."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_7",
		"In 1697, fifteen years after the death of Lobsang Gyatso, the Sixth Dalai Lama was finally enthroned. Tsangyang Gyatso (1683-1706) was a maverick who rejected the monastic life, growing his hair long, drinking wine, and enjoying female company. He also wrote great poetry, some of which is still recited today in Tibet. The Dalai Lama’s unconventional lifestyle prompted Lobsang Khan of the Khoshud Mongols to depose him in 1705. Lobsang Khan seized control of Tibet, named himself King, sent Tsangyang Gyatso to Beijing (he “mysteriously” died on the way), and installed a pretender Dalai Lama."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_8",
		"King Lobsang would rule for 12 years, until the Dzungar Mongols invaded and took power. They killed the pretender to the Dalai Lama’s throne, to the joy of the Tibetan people, but then began to loot monasteries around Lhasa. This vandalism brought a quick response from the Qing Emperor Kangxi, who sent troops to Tibet. The Dzungars destroyed the Imperial Chinese battalion near Lhasa in 1718. In 1720, the angry Kangxi sent another, larger force to Tibet, which crushed the Dzungars. The Qing army also brought the proper Seventh Dalai Lama, Kelzang Gyatso (1708-1757) to Lhasa. Qing China had its hands full trying to control Tibet. The Emperor sent a commissioner to Lhasa, but he was killed in 1750. The Imperial Army then defeated the rebels, but the Emperor recognized that he would have to rule through the Dalai Lama rather than directly. Day-to-day decisions would be made on the local level."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_9",
		"Qing Chinese power waned throughout the eighteenth century, as evidenced by its defeat in the Opium Wars with Britain (1839-1842 and 1856-1860), as well as the Taiping Rebellion (1850-1864) and the Boxer Rebellion (1899-1901). The actual relationship between China and Tibet had been unclear since the early days of the Qing Dynasty, and China's losses at home made the status of Tibet even more uncertain. The ambiguity of control over Tibet lead to problems. In 1893, the British in India concluded a trade and border treaty with Beijing concerning the boundary between Sikkim and Tibet. However, the Tibetans flatly rejected the treaty terms. The British invaded Tibet in 1903 with 10,000 men, and took Lhasa the following year. Thereupon, they concluded another treaty with the Tibetans, as well as Chinese, Nepalese and Bhutanese representatives, which gave the British themselves some control over Tibet’s affairs."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_10",
		"The 13th Dalai Lama, Thubten Gyatso, fled the country in 1904 at the urging of his Russian disciple, Agvan Dorzhiev. He went first to Mongolia, then made his way to Beijing. The Chinese declared that the Dalai Lama had been deposed as soon as he left Tibet, and claimed full sovereignty over not only Tibet but also Nepal and Bhutan. The Dalai Lama went to Beijing to discuss the situation with the Emperor Guangxu, but he flatly refused to kowtow to the Emperor. He returned to Lhasa in 1909, disappointed by Chinese policies towards Tibet. China sent a force of 6,000 troops into Tibet, and the Dalai Lama fled to Darjeeling, India later that same year. The Chinese Revolution swept away the Qing Dynasty in 1911, and the Tibetans promptly expelled all Chinese troops from Lhasa. The Dalai Lama returned home to Tibet in 1912."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_11",
		"Representatives of Great Britain, China, and Tibet met in 1914 to negotiate a treaty marking out the boundary lines between India and its northern neighbors. China walked out of the conference without signing the treaty after Britain laid claim to the Tawang area of southern Tibet, which is now part of the Indian state of Arunachal Pradesh. Tibet and Britain both signed the treaty. Soon, China would be too distracted to concern itself with the issue of Tibet. The new government of the Republic of China would hold nominal power over the majority of Chinese territory for only four years before war broke out between numerous armed factions. Under such circumstances, the Chinese showed little interest in Tibet. The 13th Dalai Lama ruled independent Tibet in peace until his death in 1933."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_12",
		"Following Thubten Gyatso's death, the new reincarnation of the Dalai Lama was born in Amdo in 1935. Tenzin Gyatso, the current Dalai Lama, was taken to Lhasa in 1937 to begin training for his duties as the leader of Tibet. In 1950, the newly-formed People's Republic of China invaded Tibet. With stability reestablished in Beijing for the first time in decades, Mao Zedong sought to assert China's right to rule over Tibet as well. The PLA inflicted a swift and total defeat on Tibet's small army, and China drafted the “Seventeen Point Agreement” incorporating Tibet as an autonomous region of the People's Republic of China. Representatives of the Dalai Lama's government signed the agreement under protest, and the Tibetans repudiated the agreement nine years later."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_TIBET_CHAPTER_HISTORY_PARA_13",
		"On March 1, 1959, the Dalai Lama received an odd invitation to attend a theater performance at PLA headquarters near Lhasa. PLA officers notified the Dalai Lama's bodyguards that they would not accompany the Tibetan leader to the performance, nor were they to notify the Tibetan people that he was leaving the palace. (Ordinarily, the people of Lhasa would line the streets to greet the Dalai Lama each time he ventured out.) The guards immediately publicized this rather ham-handed attempted abduction, and the following day an estimated crowd of 300,000 Tibetans surrounded Potala Palace to protect their leader. The PLA moved artillery into range of major monasteries and the Dalai Lama's summer palace, Norbulingka. Both sides began to dig in, although the Tibetan army was much smaller than its adversary, and poorly armed. Tibetan troops were able to secure a route for the Dalai Lama to escape into India on March 17. Actual fighting began on March 19, and lasted only two days before the Tibetan troops were defeated."),
--========================================================================================================================
-- Unique Unit
--========================================================================================================================
		("LOC_UNIT_SUK_TIBET_RTA_PA_NAME",  
		"Rta Pa"	),
		("LOC_UNIT_SUK_TIBET_RTA_PA_DESCRIPTION",  
		"Tibetan unique Renaissance era ranged cavalry unit. Has a a [ICON_Range] Range of 1, but can move after attacking. No Movement penalty in hill terrain. Unlocks with Astronomy."),
		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_TIBET_RTA_PA_CHAPTER_HISTORY_PARA_1",  
		"Rta Pa is the Tibetan word for a Horseman. Horses and horsemanship were very important in Tibet, as they were among other nomadic peoples of Central Asia. As with the other people of the steppe, Tibet has a long tradition of mounted archery, but this evolved into mounted gunmanship as gunpowder was introduced during the sixteenth century. In Europe, the matchlock was primarily an infantry weapon, but in Tibet and Central Asia it was also used on horseback in the same way as the bow. As essential military training, and as part of various ceremonies and festivals, riders would shoot at targets while riding past them at a gallop. Tibetan government officials were periodically required to demonstrate proficiency on horseback with musket, bow and arrow, and spear until as late as the mid twentieth century."),

		("LOC_ABILITY_SUK_TIBET_RTA_PA_NAME",  
		"Windhorse"	),
		("LOC_ABILITY_SUK_TIBET_RTA_PA_DESCRIPTION",  
		"Can move after attacking. No Movement penalty in hill terrain."),				
--========================================================================================================================
-- Unique Infrastructure
--========================================================================================================================
		("LOC_DISTRICT_SUK_DZONG_NAME",  
		"Dzong"	),
		("LOC_DISTRICT_SUK_DZONG_DESCRIPTION",  
		"A district unique to Tibet for religious activity. Replaces the Holy Site district and cheaper to build.[NEWLINE][NEWLINE]Awards +1 [Icon_Governor] Governor Title when built adjacent to at least 3 Mountains. Buildings in the Dzong district are 20% cheaper to purchase with [ICON_GOLD] Gold and [ICON_FAITH] Faith.[NEWLINE][NEWLINE]Occupying unit receives +10 [ICON_Strength] Defense Strength. Must be built on a Hill."),
		("LOC_DISTRICT_SUK_DZONG_DESCRIPTION_XP2",  
		"A district unique to Tibet for religious activity. Replaces the Holy Site district and cheaper to build.[NEWLINE][NEWLINE]Awards +1 [Icon_Governor] Governor Title when built adjacent to at least 4 Mountains. Buildings in the Dzong district are 20% cheaper to purchase with [ICON_GOLD] Gold and [ICON_FAITH] Faith.[NEWLINE][NEWLINE]Occupying unit receives +10 [ICON_Strength] Defense Strength. Must be built on a Hill."),
		("LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_SUK_DZONG_CHAPTER_HISTORY_PARA_1",  
		"Dzongs are type of fortress found in Tibet and Bhutan. These towering structures are characterised by their enormity, with towering exterior walls surrounding a complex of courtyards, temples, administrative offices, and monks’ accommodations. Frequently located on a hilltop or mountain spur, Dzongs are constructed without the use of architectural plans. Instead construction proceeds under the direction of a high lama who establishes each dimension by means of spiritual inspiration."),	
		("LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_SUK_DZONG_CHAPTER_HISTORY_PARA_2",  
		"In Tibet, Dzongs were integrated into the administration of the country. According to some sources it was Jangchub Gyaltsen (1302-73) who pioneered the Tibetan system of dividing vast territorial holdings into districts, each administered from a Dzong. When Jangchub Gyaltsen replaced the “thirteen myriarchies”, he divided the land into numerous districts (also called Dzong). He appointed those men among his followers, who were of unquestioned loyalty, to be masters (Dzongpon) of the districts. In modern Tibet, most Dzongs are lost or in ruins, with only a few restored as museums. It is only in Bhutan that we find the Dzongs still alive today as administration centers and monasteries."),
--========================================================================================================================
-- Leader
--========================================================================================================================
		("LOC_LEADER_SUK_TRISONG_DETSEN_NAME",  
		"Trisong Detsen"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_CAPTURE_OF_CHANGAN_NAME",  
		"Capture of Chang’an"	),
		("LOC_TRAIT_LEADER_SUK_CAPTURE_OF_CHANGAN_DESCRIPTION",  
		"+1 [ICON_GreatGeneral] Great General points in cities with both an Encampment and a Dzong. Land combat units in those cities begin with a free promotion if the city has a Worship Building."),
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_ENLIGHTENED_LORD_NAME",  
		"Great Enlightened, Miraculous, Divine Lord"	),
		("LOC_AGENDA_SUK_ENLIGHTENED_LORD_DESCRIPTION",  
		"Aims to achieve Golden Ages and high levels of [ICON_Faith] Faith, and respects those who do the same. Dislikes civilizations in a Dark Age, or who are low in [ICON_Faith] Faith"	),

		("LOC_DIPLO_MODIFIER_SUK_ENLIGHTENED_LORD_KUDO",  
		"Trisong Detsen admires your high Faith and your Golden Age"	),

		("LOC_DIPLO_MODIFIER_SUK_ENLIGHTENED_LORD_WARNING",  
		"Trisong Detsen is disgusted by your lack of Faith and ambition"	),
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_TRISONG_DETSEN",  
		"You rule the windswept steppes, Trisong Detsen. You rule the soaring mountains. Let bells ring in lofty monasteries as monks pray for your glory. Let the earth tremble as your mighty horsemen ride to war. Enlightened Lord, may you find wisdom in the Dharma and strength in the bow, that Tibet may climb to eternity."),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"A shame."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"May our friendship blossom!"),
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Join me in friendship! Together we will be a spiritual paragon for the world!"),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"No. I don't think so."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Yes, this is a worthy suggestion."),
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"My horsemen will trample your fields. Prepare for your doom!"), 
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Surely our bows and our devotion to the Dharma shall protect us from harm! We do not fear you."), 
		-- ("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		-- "We fought to our last—and lost. I surrender my arms to you and await your judgement."),
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"I do not fear the end. My good Karma will ensure a auspicious rebirth."),
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"I have sent a trade delegation. They come bearing butter tea. Drink up!"),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Ah, you have unfortunate timing. I am currently preoccupied with overseeing the construction of a Stupa. Perhaps next time."),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Thank you for your fine gifts. We will cherish them."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Truly pathetic. Spiritually dull, and with no worldly accomplishments of note."),
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"Such foul words. They reveal your foul heart."),
		("LOC_DIPLO_FIRST_MEET_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Blessings, and welcome to Tibet. I am Trisong Detsen, lord and Emperor of these lands."),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"A famed monk is holding a lecture on the Dharma. Please come join us."),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"I thank you for your hospitality."),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"My capital is hidden, high in the mountains. I will tell you more if you tell me about your capital."),
		("LOC_DIPLO_GREETING_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Welcome."),
		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"No devotion and no ambition. How can you rule with neither spiritual or worldly excellence?"),
		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"Your achievements on this earth are no doubt the fruits of your great Karma. Truly worthy of praise."),
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"I am loath to tie Tibet to other nations, but this seems a wise course of action for us both. What say you?"),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"This is not acceptable."),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"I will have my monks bless this agreement."),
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"Peace. And a respite to all this death."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"No! Tibet is not ready to make peace."),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"My monks suggest I seek peace for my people's spiritual well-being."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"You may pass. Good luck making your way through our mountains."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Passage through Tibet shall remain closed to you."),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_TRISONG_DETSEN_ANY",                                     
		"Let our borders be open to each other! What do you say?"),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_TRISONG_DETSEN_ANY",                                      
		"We have spied your soldiers from our Dzongs. Is there something you are trying to tell me?"),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_TRISONG_DETSEN_QUOTE",  
		"A kind shepherd is the flock’s parent, a good horse is the lord’s trust"  	),
		("LOC_PEDIA_LEADERS_PAGE_SUK_TRISONG_DETSEN_TITLE",
		"Trisong Detsen"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_TRISONG_DETSEN_SUBTITLE",
		"Emperor of Tibet"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_CAPSULE_BODY",
		"Tight compact mountainous cities: this is how Tibet should build. And with the aid of some religious devotion, they will excel. Trisong Detsen takes Tibet’s religious infrastructure and readies it for war."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_DETAILED_BODY",
		"Tibet is a nation of mountain strongholds and monasteries: building districts near mountains not only provides extra yields, but also allows you to purchase buildings in those districts with [ICON_Faith] Faith. With help from your [ICON_Governor] Governors and your Dzong, you should have plenty of [ICON_Faith] Faith to do just that. Trisong Detsen takes Tibet’s formidable religious infrastructure and readies it for war. Build Encampment districts wherever you have Dzongs to earn [ICON_GreatGeneral] Great Generals faster and train stronger units."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_HISTORY_PARA_1",
		"Among the most celebrated figures in Tibetan history are the “Dharma Kings” (Chögyal in Tibetan) who supported Buddhism and helped it to take root in Tibet. And probably the most important of all the Dharma Kings is Trisong Detsen. The Tibetan empire that the young Trisong Detsen inherited was in serious decline. After the glorious reign of King Songtsen Gampo, the first Dharma King of Tibet, the empire was disintegrating as Tibet lost several cities in Turkestan, Nepal became embroiled in a rebellion, and the Arabs began encroaching on the Western front of the Tibetan empire."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_HISTORY_PARA_2",
		"Trisong Detsen reversed this tide, and undertook military campaigns to ensure Tibet’s expansion. In 763 Trisong Detsen sent an army of 200,000 men to the border with Tang China, defeating the forces there and then continuing on to take Chang'an, the Tang Chinese capital, forcing Emperor Daizong of Tang to flee the capital. In 783 a peace treaty was negotiated between China and Tibet giving Tibet all lands in Qinghai. Trisong Detsen also sought to expand westward, reaching the Amu Darya and threatening the Abbasid Caliph, Harun ar-Rashid. The Caliph was concerned enough to establish an alliance with the Chinese emperor. King Trisong Detsen would be preoccupied with Arab wars in the west, taking pressure off his Chinese opponents to the east and north, until his rule ended in 797."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_HISTORY_PARA_3",
		"However, he is best remembered by later generations of Tibetan Buddhists for his great patronage of Buddhism. When Trisong Detsen became emperor in 755 and, he invited Padmasambhava, Śāntarakṣita, Vimalamitra, and various other Indian teachers to come to Tibet to spread the latest understanding of the teaching. The two pandits began by establishing Samye as the first Buddhist monastery in Tibet. Several Tibetans were eventually initiated as monks and a vast translation project was undertaken translating the Buddhist scriptures from Sanskrit into Classical Tibetan."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_HISTORY_PARA_4",
		"It was not just the Indian branch of Buddhism that made its way into Tibet during Trisong Detsen’s reign. The first documented dissemination of Chan Buddhism to Tibet, chronicled in what has become known as the Statements of the Sba Family, occurred in about 761 when Trisong Detsen sent a party to the Yizhou region to receive the teachings of Kim Hwasang, a Korean Chan master, who they encountered in Sichuan. The party received teachings and three Chinese texts from Kim, who died soon after. Trisong Detsen patronised a second party to China in 763. This second expedition was headed by a high minister, Sba Gsalsnan. There is scholarly dissent about whom Gsalsnan encountered in Yizhou. Early scholarship considered Kim, but this had been revised to Baotang Wuzhu (714-774), head and founder of Baotang Monastery in Chengdu."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_HISTORY_PARA_5",
		"The two branches of Buddhism finally came to a head. Trisong Detsen, hosted a famous two-year debate from 792-794, known in Western scholarship as the “Council of Lhasa” (although it took place at Samye at quite a distance from Lhasa) outside the capital. He sponsored a Dharma debate between the Chan Buddhist Moheyan, who represented the third documented wave of Chan dissemination in Tibet, and the scholar Kamalaśīla, a student of Śāntarakṣita. Effectively the debate was between the Chinese and Indian Buddhist traditions as they were represented in Tibet. Sources differ about both the nature of the debate as well as the victor."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_TRISONG_DETSEN_CHAPTER_HISTORY_PARA_6",
		"Trisong Detsen retired to live at the palace at Zungkar and handed power to his second son, Muné Tsenpo, in 797. From this point there is much confusion in the various historical sources. It seems there was a struggle for the succession after the death of Trisong Detsen. It is not clear when Trisong Detsen died, or for how long Mune Tsenpo reigned. The Testament of Ba, a Tibetan historical text which may date back to the 9th century, claims that Muné Tsenpo insisted that his father's funeral be performed according to Buddhist rather than traditional rites.");
--------------------------------------------------------------------
--------------------------------------------------------------------