--------------------------------------------------------------------------------------------------------------------------
-- LocalisedText
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Tag, 								Language,	Text)
VALUES
-- English US ------------------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"en_US",	"Enhanced Mod Manager v1.7.5 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"en_US",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"en_US",	"MANAGER"),
		("LOC_FF16_SORTBY_AUTHOR",  		"en_US",	"Sort By: Author"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"en_US", 	"Sort By: Dependency"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"en_US", 	"Sort By: Update Time"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"en_US", 	"Sort By: Compatibility"),
		("LOC_FF16_CUSTOM_FILTER",  		"en_US", 	"Custom Filter:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"en_US", 	"Off"),
		("LOC_FF16_BY_AUTHOR",				"en_US", 	"By: "),
		("LOC_FF16_ENABLED_MODS",  			"en_US", 	"ENABLED MODS"),
		("LOC_FF16_DISABLED_MODS",  		"en_US", 	"DISABLED MODS"),
		("LOC_FF16_OFFICIAL_FILTER",  		"en_US", 	"DLC"),
		("LOC_FF16_COMMUNITY_FILTER",  		"en_US", 	"Mods"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"en_US", 	"Gameplay"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"en_US", 	"Cosmetic"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"en_US", 	"Filter official DLC by Firaxis."),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"en_US", 	"Filter community made mods."),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"en_US", 	"Filter mods that affect save games."),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "en_US", 	"Filter mods that do not affect save games."),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","en_US", 	"Search for content based on title, teaser or mod author."),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"en_US", 	"Enable all mods currently listed below."),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"en_US", 	"Disable all mods currently listed below."),
		("LOC_FF16_ENABLEALL_QUESTION", 	"en_US", 	"Enable all currently listed mods?"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"en_US", 	"Disable all currently listed mods?"),	
		("LOC_FF16_MULTISELECT_TITLE", 		"en_US", 	"Multi Selection Mode"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"en_US", 	"More than one mod has been selected."),	
		("LOC_FF16_MULTISELECT_DESC", 		"en_US", 	"Number of mods currently selected: "),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"en_US", 	"Selected Mods Depend On"),	
		("LOC_FF16_MULTISELECT_TOOLTIP", 	"en_US", 	"Your current mod selection has missing dependencies. Add the missing mods to your selection or deselect the dependant mods."),	
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "en_US", 	"Ignoring Compatibility Warning"),
		("LOC_FF16_OPEN_WORKSHOP",			"en_US",	"Open this mod's Steam Workshop page."),
		("LOC_FF16_OPEN_CHANGELOG",			"en_US",	"Open this mod's changelog."),
		("LOC_FF16_MODS_SUBSCRIBED",		"en_US",	"Workshop Subscribed?"),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"en_US",	"Last Updated: No Subscription Found"),
		("LOC_FF16_MODID",					"en_US",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"en_US",	"Locally Installed"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"en_US",	"Non-Workshop Mod"),
				
--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"en_US", 	"12"),
		("LOC_FF16_MODSCREEN_TIP_1",		"en_US", 	"Tip: Right click a mod to instantly enable/disable it."),
		("LOC_FF16_MODSCREEN_TIP_2",		"en_US", 	"Tip: You can also sort by Author or Mod Dependency."),
		("LOC_FF16_MODSCREEN_TIP_3",		"en_US", 	"Tip: Uncheck the 'Gameplay' filter to only show mods you can apply to your existing save games!"),
		("LOC_FF16_MODSCREEN_TIP_4",		"en_US", 	"Tip: Click on a mod to bring up its details panel. Click again to hide it."),
		("LOC_FF16_MODSCREEN_TIP_5",		"en_US", 	"Tip: Mod conflicts? Try disabling similar mods one by one to find out which one is causing the issue."),
		("LOC_FF16_MODSCREEN_TIP_6",		"en_US", 	"Tip: If Gandhi asks for any of your Uranium, say no."),
		("LOC_FF16_MODSCREEN_TIP_7",		"en_US", 	"Tip: Mods that affect save games are automatically loaded or de-loaded when you load an existing save."),
		("LOC_FF16_MODSCREEN_TIP_8",		"en_US", 	"Tip: Like a certain mod set up? Click the plus icon in the top right corner to save your current mod group."),
		("LOC_FF16_MODSCREEN_TIP_9",		"en_US", 	"Tip: Enjoying a new mod? Do the author a favour and rate it on the workshop!"),
		("LOC_FF16_MODSCREEN_TIP_10",		"en_US", 	"Happy Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"en_US", 	"Tip: Hold Shift while selecting mods to enable or disable multiple mods at once!"),
		("LOC_FF16_MODSCREEN_TIP_12",		"en_US", 	"Tip: You can define your own custom mod filters! Check out CustomFilters.xml for more information."),

-- Chinese (Simplified) --------------------------------------------------------------------------------------------------
		("LOC_FF16_SIGNATURE",  			"zh_Hans_CN",	"加强版MOD管理器 v1.7.5 by FinalFreak16"),
		("LOC_FF16_MOD_TITLE_1", 	 		"zh_Hans_CN",	"MOD"),
		("LOC_FF16_MOD_TITLE_2",  			"zh_Hans_CN",	"管理器"),
		("LOC_FF16_SORTBY_AUTHOR",  		"zh_Hans_CN",	"按作者分类"),
		("LOC_FF16_SORTBY_DEPENDENCY",  	"zh_Hans_CN", 	"按关联分类"),
		("LOC_FF16_SORTBY_LASTUPDATED",  	"zh_Hans_CN", 	"Sort By: Update Time"),
		("LOC_FF16_SORTBY_COMPATIBILITY",  	"zh_Hans_CN", 	"Sort By: Compatibility"),
		("LOC_FF16_CUSTOM_FILTER",  		"zh_Hans_CN", 	"Custom Filter:"),
		("LOC_FF16_CUSTOM_FILTER_OFF",  	"zh_Hans_CN", 	"Off"),
		("LOC_FF16_BY_AUTHOR",				"zh_Hans_CN", 	"作者："),
		("LOC_FF16_ENABLED_MODS",  			"zh_Hans_CN", 	"已启用的MOD"),
		("LOC_FF16_DISABLED_MODS",  		"zh_Hans_CN", 	"已禁用的MOD"),
		("LOC_FF16_OFFICIAL_FILTER",  		"zh_Hans_CN", 	"官方包"),
		("LOC_FF16_COMMUNITY_FILTER",  		"zh_Hans_CN", 	"社区包"),
		("LOC_FF16_AFFECTSSAVE_FILTER", 	"zh_Hans_CN", 	"影响存档"),
		("LOC_FF16_NOTAFFECTSSAVE_FILTER", 	"zh_Hans_CN", 	"不影响存档"),
		("LOC_FF16_OFFICIAL_TOOLTIP",  		"zh_Hans_CN", 	"显示官方制作的DLC。"),
		("LOC_FF16_COMMUNITY_TOOLTIP",  	"zh_Hans_CN", 	"显示社区制作的MOD。"),
		("LOC_FF16_AFFECTSSAVE_TOOLTIP", 	"zh_Hans_CN", 	"显示影响游戏存档的MOD。"),
		("LOC_FF16_NOTAFFECTSSAVE_TOOLTIP", "zh_Hans_CN", 	"显示不影响游戏存档的MOD。"),
		("LOC_FF16_MODS_SEARCH_DESCRIPTION","zh_Hans_CN", 	"依照标题、描述或者作者来搜索MOD。"),
		("LOC_FF16_ENABLEALL_TOOLTIP", 		"zh_Hans_CN", 	"启用列表中的所有MOD。"),
		("LOC_FF16_DISABLEALL_TOOLTIP", 	"zh_Hans_CN", 	"禁用列表中的所有MOD。"),
		("LOC_FF16_ENABLEALL_QUESTION", 	"zh_Hans_CN", 	"启用列表中的所有MOD？"),
		("LOC_FF16_DISABLEALL_QUESTION", 	"zh_Hans_CN", 	"禁用列表中的所有MOD？"),
		("LOC_FF16_MULTISELECT_TITLE", 		"zh_Hans_CN", 	"多选模式"),	
		("LOC_FF16_MULTISELECT_TEASER", 	"zh_Hans_CN", 	"已经选择了一个以上的MOD。"),	
		("LOC_FF16_MULTISELECT_DESC", 		"zh_Hans_CN", 	"目前已选中的MOD数量："),	
		("LOC_FF16_MULTISELECT_DEPEND", 	"zh_Hans_CN", 	"选中的MOD依赖于："),	
		("LOC_FF16_MULTISELECT_TOOLTIP",	"zh_Hans_CN", 	"您当前选择的MOD缺少依赖项。将缺少的MOD添加到您的选择中，或者取消选择需要依赖的MOD。"),
		("LOC_FF16_COMPAT_IGNORED_TOOLTIP", "zh_Hans_CN", 	"Ignoring Compatibility Warning"),
		("LOC_FF16_OPEN_WORKSHOP",			"zh_Hans_CN",	"Open this mod's Steam Workshop page."),
		("LOC_FF16_OPEN_CHANGELOG",			"zh_Hans_CN",	"Open this mod's changelog."),
		("LOC_FF16_LAST_UPDATED_OFFLINE",	"zh_Hans_CN",	"Last Updated: No Subscription Found"),
		("LOC_FF16_MODID",					"zh_Hans_CN",	"ID"),
		("LOC_FF16_LOCALINSTALL",			"zh_Hans_CN",	"Locally Installed"),
		("LOC_FF16_LOCALINSTALL_TOOLTIP",	"zh_Hans_CN",	"Non-Workshop Mod"),
		
--------------------------------------------------------------------------------------------------------------------------
		("LOC_FF16_MODSCREEN_TIP_NUM",		"zh_Hans_CN", 	"12"),
		("LOC_FF16_MODSCREEN_TIP_1",		"zh_Hans_CN", 	"小贴士：右键一个MOD可以直接启用或者禁用它。"),
		("LOC_FF16_MODSCREEN_TIP_2",		"zh_Hans_CN", 	"小贴士：你可以按照作者或根据关联的顺序来排列。"),
		("LOC_FF16_MODSCREEN_TIP_3",		"zh_Hans_CN", 	"小贴士：不勾选“影响存档”选项，列表中就会只显示你可以用于你现有的存档的MOD！"),
		("LOC_FF16_MODSCREEN_TIP_4",		"zh_Hans_CN", 	"小贴士：点击一个MOD可以打开它的详情面板，再次点击则可以隐藏面板。"),
		("LOC_FF16_MODSCREEN_TIP_5",		"zh_Hans_CN", 	"小贴士：MOD冲突？尝试逐个禁用类似的MOD，以查明是哪个MOD导致的冲突。"),
		("LOC_FF16_MODSCREEN_TIP_6",		"zh_Hans_CN", 	"小贴士：如果甘地向你要铀，千万别给！"),
		("LOC_FF16_MODSCREEN_TIP_7",		"zh_Hans_CN", 	"小贴士：当你读取存档的时候，影响游戏存档的MOD会根据之前的使用情况自动加载或卸载。"),
		("LOC_FF16_MODSCREEN_TIP_8",		"zh_Hans_CN", 	"小贴士：喜欢当前的MOD组合吗？单击右上角的加号图标可以将当前的MOD存为一个组。"),
		("LOC_FF16_MODSCREEN_TIP_9",		"zh_Hans_CN", 	"小贴士：喜欢一个MOD？别吝啬，去创意工坊给作者点个赞吧！"),
		("LOC_FF16_MODSCREEN_TIP_10",		"zh_Hans_CN", 	"Happy Modding!"),
		("LOC_FF16_MODSCREEN_TIP_11",		"zh_Hans_CN", 	"小贴士：在选择MOD的时候，按住Shift可以同时选中多个哦。"),
		("LOC_FF16_MODSCREEN_TIP_12",		"zh_Hans_CN", 	"Tip: You can define your own custom mod filters! Check out CustomFilters.xml for more information.");

--------------------------------------------------------------------------------------------------------------------------