/*
	Strategy
	Credits: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_ASKIYA_TECHS'			),
		('LEADER_CVS_ASKIYA_CIVICS'			),
		('LEADER_CVS_ASKIYA_DISTRICTS'		),
		('LEADER_CVS_ASKIYA_BUILDINGS'		),
		('LEADER_CVS_ASKIYA_PROJECTS'		),
		('LEADER_CVS_ASKIYA_DIPLOMACY'		),
		('LEADER_CVS_ASKIYA_EXPANSION'		),
		('LEADER_CVS_ASKIYA_PSUEDOS'		),
		('LEADER_CVS_ASKIYA_YIELDS'			),
		-- XP1
		('LEADER_CVS_ASKIYA_ALLIANCES'		),
		('LEADER_CVS_ASKIYA_COMMEMORATIONS'	),
		-- XP2
		('LEADER_CVS_ASKIYA_DISCUSSIONS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								AgendaType,					System				) -- AgendaType links to a TraitType, not an AgendaType... :/
VALUES  ('LEADER_CVS_ASKIYA_TECHS',				'TRAIT_AGENDA_CVS_ASKIYA',	'Technologies'		),
		('LEADER_CVS_ASKIYA_CIVICS',			'TRAIT_AGENDA_CVS_ASKIYA',	'Civics'			),
		('LEADER_CVS_ASKIYA_DISTRICTS',			'TRAIT_AGENDA_CVS_ASKIYA',	'Districts'			),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'TRAIT_AGENDA_CVS_ASKIYA',	'Buildings'			),
		('LEADER_CVS_ASKIYA_PROJECTS',			'TRAIT_AGENDA_CVS_ASKIYA',	'Projects'			),
		('LEADER_CVS_ASKIYA_DIPLOMACY',			'TRAIT_AGENDA_CVS_ASKIYA',	'DiplomaticActions'	),
		('LEADER_CVS_ASKIYA_EXPANSION',			'TRAIT_AGENDA_CVS_ASKIYA',	'PlotEvaluations'	),
		('LEADER_CVS_ASKIYA_PSUEDOS',			'TRAIT_AGENDA_CVS_ASKIYA',	'PsuedoYields'		),
		('LEADER_CVS_ASKIYA_YIELDS',			'TRAIT_AGENDA_CVS_ASKIYA',	'Yields'			),
		-- XP1
		('LEADER_CVS_ASKIYA_ALLIANCES',			'TRAIT_AGENDA_CVS_ASKIYA',	'Alliances'			),
		('LEADER_CVS_ASKIYA_COMMEMORATIONS',	'TRAIT_AGENDA_CVS_ASKIYA',	'Commemorations'	),
		-- XP2
		('LEADER_CVS_ASKIYA_DISCUSSIONS',		'TRAIT_AGENDA_CVS_ASKIYA',	'Discussions'		);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,								Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_ASTROLOGY',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_WRITING',								1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_BRONZE_WORKING',						1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_HORSEBACK_RIDING',					1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_THE_WHEEL',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_CURRENCY',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_IRON_WORKING',						1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_MATHEMATICS',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_STIRRUPS',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_EDUCATION',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_BANKING',								1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_SCIENTIFIC_THEORY',					1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_MILITARY_SCIENCE',					1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_ECONOMICS',							1		),
		('LEADER_CVS_ASKIYA_TECHS',				'TECH_CHEMISTRY',							1		),
		-- CIVICS
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_CRAFTMANSHIP',						1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_FOREIGN_TRADE',						1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_MYSTICISM',							1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_MILITARY_TRAINING',					1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_RECORDED_HISTORY',					1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_THEOLOGY',							1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_DIVINE_RIGHT',						1		),
		('LEADER_CVS_ASKIYA_CIVICS',			'CIVIC_REFORMED_CHURCH',					1		),
		-- DISTRICTS
		('LEADER_CVS_ASKIYA_DISTRICTS',			'DISTRICT_CAMPUS',							1		),
		('LEADER_CVS_ASKIYA_DISTRICTS',			'DISTRICT_HOLY_SITE',						1		),
		('LEADER_CVS_ASKIYA_DISTRICTS',			'DISTRICT_THEATER',							1		),
		('LEADER_CVS_ASKIYA_DISTRICTS',			'DISTRICT_COMMERCIAL_HUB',					1		),
		-- BUILDINGS
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_SHRINE',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_TEMPLE',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_MARKET',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_LIBRARY',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_STABLE',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_CVS_SONGHAI_UI',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_BANK',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_STOCK_EXCHANGE',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_RESEARCH_LAB',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_MILITARY_ACADEMY',				1		),
		-- WONDERS
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_GREAT_LIBRARY',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_MAHABODHI_TEMPLE',				1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_PYRAMIDS',						1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_COLOSSUS',						1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_PETRA',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_OXFORD_UNIVERSITY',				1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_GREAT_ZIMBABWE',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_BIG_BEN',							1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_HAGIA_SOPHIA',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_MONT_ST_MICHEL',					1		),
		('LEADER_CVS_ASKIYA_BUILDINGS',			'BUILDING_STONEHENGE',						1		),
		-- DIPLOMACY
		('LEADER_CVS_ASKIYA_DIPLOMACY',			'DIPLOACTION_ALLIANCE_ECONOMIC',			1		),
		('LEADER_CVS_ASKIYA_DIPLOMACY',			'DIPLOACTION_ALLIANCE_RELIGIOUS',			1		),
		-- ALLIANCES (XP1)
		('LEADER_CVS_ASKIYA_ALLIANCES',			'ALLIANCE_ECONOMIC',						1		),
		('LEADER_CVS_ASKIYA_ALLIANCES',			'ALLIANCE_RELIGIOUS',						1		),
		-- COMMEMORATIONS (XP1)
		('LEADER_CVS_ASKIYA_COMMEMORATIONS',	'COMMEMORATION_ECONOMIC',					1		),
		('LEADER_CVS_ASKIYA_COMMEMORATIONS',	'COMMEMORATION_RELIGIOUS',					1		),
		-- XP2
		('LEADER_CVS_ASKIYA_DISCUSSIONS',		'WC_EMERGENCY_RELIGIOUS',					0		),
		('LEADER_CVS_ASKIYA_DISCUSSIONS',		'WC_RES_TRADE_TREATY',						1		);
		
INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_ASKIYA_EXPANSION',		'Specific Feature',						1,			5,		'FEATURE_FLOODPLAINS'		),
		('LEADER_CVS_ASKIYA_EXPANSION',		'Resource Class',						1,			5,		'RESOURCECLASS_STRATEGIC'	),
		('LEADER_CVS_ASKIYA_EXPANSION',		'Specific Resource',					1,			7,		'RESOURCE_IRON'				),
		-- PSUEDOS
		('LEADER_CVS_ASKIYA_PSUEDOS',		'PSEUDOYIELD_GPP_PROPHET',				1,			15,		NULL						),
		('LEADER_CVS_ASKIYA_PSUEDOS',		'PSEUDOYIELD_GPP_SCIENTIST',			1,			15,		NULL						),
		('LEADER_CVS_ASKIYA_PSUEDOS',		'PSEUDOYIELD_UNIT_RELIGIOUS',			1,			75,		NULL						),
		('LEADER_CVS_ASKIYA_PSUEDOS',		'PSEUDOYIELD_TECHNOLOGY',				1,			20,		NULL						),
		('LEADER_CVS_ASKIYA_PSUEDOS',		'PSEUDOYIELD_UNIT_TRADE',				1,			2.0,	NULL						),
		-- YIELDS
		('LEADER_CVS_ASKIYA_YIELDS',		'YIELD_FAITH',							1,			20,		NULL						),
		('LEADER_CVS_ASKIYA_YIELDS',		'YIELD_SCIENCE',						1,			20,		NULL						);