/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType									)
VALUES 	('LEADER_CVS_TIGRANES_II_TECHS'				),
		('LEADER_CVS_TIGRANES_II_CIVICS'			),
		('LEADER_CVS_TIGRANES_II_DISTRICTS'			),
		('LEADER_CVS_TIGRANES_II_BUILDINGS'			),
		('LEADER_CVS_TIGRANES_II_PROJECTS'			),
		('LEADER_CVS_TIGRANES_II_DIPLOMACY'			),
		('LEADER_CVS_TIGRANES_II_EXPANSION'			),
		('LEADER_CVS_TIGRANES_II_PSUEDOS'			),
		('LEADER_CVS_TIGRANES_II_ALLIANCES'			),
		('LEADER_CVS_TIGRANES_II_COMMEMORATIONS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,									AgendaType,						System				)
VALUES  ('LEADER_CVS_TIGRANES_II_TECHS',			'TRAIT_AGENDA_CVS_TIGRANES_II',	'Technologies'		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'TRAIT_AGENDA_CVS_TIGRANES_II',	'Civics'			),
		('LEADER_CVS_TIGRANES_II_DISTRICTS',		'TRAIT_AGENDA_CVS_TIGRANES_II',	'Districts'			),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'TRAIT_AGENDA_CVS_TIGRANES_II',	'Buildings'			),
		('LEADER_CVS_TIGRANES_II_PROJECTS',			'TRAIT_AGENDA_CVS_TIGRANES_II',	'Projects'			),
		('LEADER_CVS_TIGRANES_II_DIPLOMACY',		'TRAIT_AGENDA_CVS_TIGRANES_II',	'DiplomaticActions'	),
		('LEADER_CVS_TIGRANES_II_EXPANSION',		'TRAIT_AGENDA_CVS_TIGRANES_II',	'PlotEvaluations'	),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',			'TRAIT_AGENDA_CVS_TIGRANES_II',	'PsuedoYields'		),
		('LEADER_CVS_TIGRANES_II_ALLIANCES',		'TRAIT_AGENDA_CVS_TIGRANES_II',	'Alliances'			),
		('LEADER_CVS_TIGRANES_II_COMMEMORATIONS',	'TRAIT_AGENDA_CVS_TIGRANES_II',	'Commemorations'	);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,									Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_ASTROLOGY',							1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_BRONZE_WORKING',						1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_HORSEBACK_RIDING',					1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_THE_WHEEL',							1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_IRON_WORKING',						1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_CONSTRUCTION',						1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_MASONRY',								1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_STIRRUPS',							1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_ENGINEERING',							1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_MILITARY_ENGINEERING',				1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_METAL_CASTING',						1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_MILITARY_SCIENCE',					1		),
		('LEADER_CVS_TIGRANES_II_TECHS',			'TECH_APPRENTICESHIP',						1		),
		-- CIVICS
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_MYSTICISM',							1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_CRAFTSMANSHIP',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_MILITARY_TRADITION',					1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_STATE_WORKFORCE',					1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_MILITARY_TRAINING',					1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_FEUDALISM',							1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_MERCENARIES',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_NATIONALISM',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_SCORCHED_EARTH',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_MOBILIZATION',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_TOTALITARIANISM',					1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_CLASS_STRUGGLE',						1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_RAPID_DEPLOYMENT',					1		),
		('LEADER_CVS_TIGRANES_II_CIVICS',			'CIVIC_GLOBALIZATION',						1		),
		-- DISTRICTS
		('LEADER_CVS_TIGRANES_II_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1		),
		('LEADER_CVS_TIGRANES_II_DISTRICTS',		'DISTRICT_CVS_ARMENIA_UI',					1		),
		('LEADER_CVS_TIGRANES_II_DISTRICTS',		'DISTRICT_INDUSTRIAL_ZONE',					1		),
		-- BUILDINGS
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_SHRINE',							1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_TEMPLE',							1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_WALLS',							1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_CASTLE',							1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_STAR_FORT',						1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_STABLE',							1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_ARMORY',							1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_MILITARY_ACADEMY',				1		),
		-- WONDERS
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_STONEHENGE',						1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_MAHABODHI_TEMPLE',				1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_HAGIA_SOPHIA',					1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_MONT_ST_MICHEL',					1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_POTALA_PALACE',					1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_CRISTO_REDENTOR',					1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_ANGKOR_WAT',						1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_CASA_DE_CONTRATACION',			1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_KOTOKU_IN',						1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_TERRACOTTA_ARMY',					1		),
		('LEADER_CVS_TIGRANES_II_BUILDINGS',		'BUILDING_JEBEL_BARKAL',					1		),
		-- DIPLOMACY
		('LEADER_CVS_TIGRANES_II_DIPLOMACY',		'DIPLOACTION_DECLARE_JOINT_WAR',			1		),
		-- ALLIANCES
		('LEADER_CVS_TIGRANES_II_ALLIANCES',		'ALLIANCE_MILITARY',						1		),
		('LEADER_CVS_TIGRANES_II_ALLIANCES',		'ALLIANCE_RELIGIOUS',						1		),
		-- COMMEMORATIONS
		('LEADER_CVS_TIGRANES_II_COMMEMORATIONS',	'COMMEMORATION_MILITARY',					1		),
		('LEADER_CVS_TIGRANES_II_COMMEMORATIONS',	'COMMEMORATION_RELIGIOUS',					1		);
		
INSERT INTO AiFavoredItems
		(ListType,								Item,									Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_TIGRANES_II_EXPANSION',	'Resource Class',						1,			5,		'RESOURCECLASS_STRATEGIC'	),
		('LEADER_CVS_TIGRANES_II_EXPANSION',	'Specific Resource',					1,			7,		'RESOURCE_STONE'			),
		-- PSUEDOS
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_GPP_PROPHET',				1,			30,		NULL						),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_GPP_GENERAL',				1,			50,		NULL						),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_GREATWORK_RELIC',			1,			15,		NULL						),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_GREATWORK_RELIGIOUS',		1,			15,		NULL						),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_IMPROVEMENT',				1,			5,		NULL						),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_UNIT_COMBAT',				1,			25,		NULL						),
		('LEADER_CVS_TIGRANES_II_PSUEDOS',		'PSEUDOYIELD_FAITH',					1,			25,		NULL						);