/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_ANACAONA_TECHS'		),
		('LEADER_CVS_ANACAONA_CIVICS'		),
		('LEADER_CVS_ANACAONA_DISTRICTS'	),
		('LEADER_CVS_ANACAONA_BUILDINGS'	),
		('LEADER_CVS_ANACAONA_PROJECTS'		),
		('LEADER_CVS_ANACAONA_DIPLOMACY'	),
		('LEADER_CVS_ANACAONA_EXPANSION'	),
		('LEADER_CVS_ANACAONA_PSUEDOS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							AgendaType,						System				)
VALUES  ('LEADER_CVS_ANACAONA_TECHS',		'TRAIT_AGENDA_CVS_ANACAONA',	'Technologies'		),
		('LEADER_CVS_ANACAONA_CIVICS',		'TRAIT_AGENDA_CVS_ANACAONA',	'Civics'			),
		('LEADER_CVS_ANACAONA_DISTRICTS',	'TRAIT_AGENDA_CVS_ANACAONA',	'Districts'			),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'TRAIT_AGENDA_CVS_ANACAONA',	'Buildings'			),
		('LEADER_CVS_ANACAONA_PROJECTS',	'TRAIT_AGENDA_CVS_ANACAONA',	'Projects'			),
		('LEADER_CVS_ANACAONA_DIPLOMACY',	'TRAIT_AGENDA_CVS_ANACAONA',	'DiplomaticActions'	),
		('LEADER_CVS_ANACAONA_EXPANSION',	'TRAIT_AGENDA_CVS_ANACAONA',	'PlotEvaluations'	),
		('LEADER_CVS_ANACAONA_PSUEDOS',		'TRAIT_AGENDA_CVS_ANACAONA',	'PsuedoYields'		);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_ANACAONA_TECHS',		'TECH_ASTROLOGY',							1		),
		('LEADER_CVS_ANACAONA_TECHS',		'TECH_PRINTING',							1		),
		('LEADER_CVS_ANACAONA_TECHS',		'TECH_RADIO',								1		),
		-- CIVICS
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_CRAFTMANSHIP',						1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_GAMES_RECREATION',					1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_MEDIEVAL_FAIRES',					1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_CULTURAL_HERITAGE',					1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_OPERA_BALLET',						1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_MASS_MEDIA',							1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_PROFESSIONAL_SPORTS',				1		),
		('LEADER_CVS_ANACAONA_CIVICS',		'CIVIC_NATURAL_HISTORY',					1		),
		-- DISTRICTS
		('LEADER_CVS_ANACAONA_DISTRICTS',	'DISTRICT_CVS_TAINO_UI',					1		),
		('LEADER_CVS_ANACAONA_DISTRICTS',	'DISTRICT_HOLY_SITE',						1		),
		-- BUILDINGS
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_SHRINE',							1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_AMPHITHEATER',					1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_MUSEUM_ART',						1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_MUSEUM_ARTIFACT',					1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_BROADCAST_CENTER',				1		),
		-- WONDERS
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_BOLSHOI_THEATER',					1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_BROADWAY',						1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_COLOSSEUM',						1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_CRISTO_REDENTOR',					1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_ESTADIO_DO_MARACANA',				1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_HERMITAGE',						1		),
		('LEADER_CVS_ANACAONA_BUILDINGS',	'BUILDING_SYDNEY_OPERA_HOUSE',				1		),
		-- PROJECTS
		('LEADER_CVS_ANACAONA_PROJECTS',	'PROJECT_CVS_TAINO_UP',						1		),
		-- DIPLOMACY
		('LEADER_CVS_ANACAONA_DIPLOMACY',	'DIPLOACTION_GRANT_INFLUENCE_TOKEN',		1		),
		('LEADER_CVS_ANACAONA_DIPLOMACY',	'DIPLOACTION_DECLARE_SURPRISE_WAR',			0		),
		('LEADER_CVS_ANACAONA_DIPLOMACY',	'DIPLOACTION_DECLARE_FORMAL_WAR',			0		),
		('LEADER_CVS_ANACAONA_DIPLOMACY',	'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		0		);
		
INSERT INTO AiFavoredItems
		(ListType,							Item,										Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_ANACAONA_EXPANSION',	'Specific Feature',							1,			3,		'FEATURE_CRATER_LAKE'		),
		('LEADER_CVS_ANACAONA_EXPANSION',	'Specific Feature',							1,			3,		'FEATURE_DEAD_SEA'			),
		('LEADER_CVS_ANACAONA_EXPANSION',	'Specific Feature',							1,			3,		'FEATURE_CLIFFS_DOVER'		),
		('LEADER_CVS_ANACAONA_EXPANSION',	'Specific Feature',							1,			3,		'FEATURE_PIOPIOTAHI'		),
		('LEADER_CVS_ANACAONA_EXPANSION',	'Resource Class',							1,			5,		'RESOURCECLASS_BONUS'		),
		('LEADER_CVS_ANACAONA_EXPANSION',	'Resource Class',							1,			5,		'RESOURCECLASS_LUXURY'		),
		-- PSUEDOS
		('LEADER_CVS_ANACAONA_PSUEDOS',		'PSEUDOYIELD_GPP_PROPHET',					1,			15,		NULL						),
		('LEADER_CVS_ANACAONA_PSUEDOS',		'PSEUDOYIELD_GPP_WRITER',					1,			15,		NULL						),
		('LEADER_CVS_ANACAONA_PSUEDOS',		'PSEUDOYIELD_GPP_ARTIST',					1,			15,		NULL						),
		('LEADER_CVS_ANACAONA_PSUEDOS',		'PSEUDOYIELD_GPP_MUSICIAN',					1,			15,		NULL						),
		('LEADER_CVS_ANACAONA_PSUEDOS',		'PSEUDOYIELD_INFLUENCE',					1,			25,		NULL						),
		('LEADER_CVS_ANACAONA_PSUEDOS',		'PSEUDOYIELD_DIPLOMATIC_BONUS',				1,			25,		NULL						);
