/*
	Civilization
	Credits: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
		(Type,						Kind				)
VALUES	('CIVILIZATION_CVS_AKKAD',	'KIND_CIVILIZATION'	);
		
-----------------------------------------------
-- Civilizations
-----------------------------------------------

INSERT INTO	Civilizations
		(CivilizationType,			Name,								Description,								Adjective,								StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_CVS_AKKAD',	'LOC_CIVILIZATION_CVS_AKKAD_NAME',	'LOC_CIVILIZATION_CVS_AKKAD_DESCRIPTION',	'LOC_CIVILIZATION_CVS_AKKAD_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_MEDIT' 	);
		
-----------------------------------------------
-- CityNames
-----------------------------------------------

-- Will update this later

INSERT INTO	CityNames
		(CivilizationType,			CityName	)						
VALUES	('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_AKKAD'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_KISH'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_ERIDU'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_BAD_TIBIRA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_URUK'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_NIPPUR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_UR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SUSA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_HAMOUKAR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_DILBAT'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_KISURRA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_ASSUR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_LAGASH'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_NINEVEH'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_ESHNUNNA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_ARBELA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_GASUR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_NAGAR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_ADAB'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_ARRAPKHA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_KAHAT'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_SHUBAT_ENLIL'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_ANSHAN'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_MARI'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_SHADUPPUM'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_UMMA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_AKSHAK'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_NEREBTUM'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_NABADA'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_MASHKAN_SHAPIR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_URKESH'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_URUM'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_MARAD'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_CHAGAR_BAZAR'),
		('CIVILIZATION_CVS_AKKAD', 'LOC_CITY_NAME_SC_ARBID');
		
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------

INSERT INTO	CivilizationCitizenNames
		(CivilizationType,				CitizenName,						Female	)
VALUES	('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_1',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_2',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_3',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_4',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_5',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_6',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_7',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_8',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_9',		0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_MALE_10',	0 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_1',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_2',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_3',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_4',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_5',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_6',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_7',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_8',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_9',	1 		),
		('CIVILIZATION_CVS_AKKAD',		'LOC_CITIZEN_CVS_AKKAD_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------

INSERT INTO	CivilizationInfo
		(CivilizationType,			Header,						Caption,								SortIndex	)
VALUES	('CIVILIZATION_CVS_AKKAD',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_CVS_AKKAD_LOCATION',		10			),
		('CIVILIZATION_CVS_AKKAD',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_CVS_AKKAD_SIZE',			20			),
		('CIVILIZATION_CVS_AKKAD',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_CVS_AKKAD_POPULATION',		30			),
		('CIVILIZATION_CVS_AKKAD',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_CVS_AKKAD_CAPITAL',		40			);
		
-----------------------------------------------
-- Start Bias
-----------------------------------------------

INSERT INTO	StartBiasFeatures
		(CivilizationType,			FeatureType,		 	Tier	)
VALUES	('CIVILIZATION_CVS_AKKAD',	'FEATURE_FLOODPLAINS',	3		);