/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType						)
VALUES 	('LEADER_CVS_KUDARAT_TECHS'		),
		('LEADER_CVS_KUDARAT_CIVICS'	),
		('LEADER_CVS_KUDARAT_DISTRICTS'	),
		('LEADER_CVS_KUDARAT_BUILDINGS'	),
		('LEADER_CVS_KUDARAT_PROJECTS'	),
		('LEADER_CVS_KUDARAT_DIPLOMACY'	),
		('LEADER_CVS_KUDARAT_UNITS'		),
		('LEADER_CVS_KUDARAT_TACTICS'	),
		('LEADER_CVS_KUDARAT_EXPANSION'	),
		('LEADER_CVS_KUDARAT_PSUEDOS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							AgendaType,				System				)
VALUES  ('LEADER_CVS_KUDARAT_TECHS',		'AGENDA_CVS_KUDARAT',	'Technologies'		),
		('LEADER_CVS_KUDARAT_CIVICS',		'AGENDA_CVS_KUDARAT',	'Civics'			),
		('LEADER_CVS_KUDARAT_DISTRICTS',	'AGENDA_CVS_KUDARAT',	'Districts'			),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'AGENDA_CVS_KUDARAT',	'Buildings'			),
		('LEADER_CVS_KUDARAT_PROJECTS',		'AGENDA_CVS_KUDARAT',	'Projects'			),
		('LEADER_CVS_KUDARAT_UNITS',		'AGENDA_CVS_KUDARAT',	'Units'				),
		('LEADER_CVS_KUDARAT_TACTICS',		'AGENDA_CVS_KUDARAT',	'Tactics'			),
		('LEADER_CVS_KUDARAT_DIPLOMACY',	'AGENDA_CVS_KUDARAT',	'DiplomaticActions'	),
		('LEADER_CVS_KUDARAT_EXPANSION',	'AGENDA_CVS_KUDARAT',	'PlotEvaluations'	),
		('LEADER_CVS_KUDARAT_PSUEDOS',		'AGENDA_CVS_KUDARAT',	'PsuedoYields'		);

-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_SHIPBUILDING',					1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_CELESTIAL_NAVIGATION',			1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_CARTOGRAPHY',						1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_SQUARE_RIGGING',					1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_ECONOMICS',						1		),
		('LEADER_CVS_KUDARAT_TECHS',		'TECH_ASTROLOGY',						1		), -- LEADER SPECIFIC
		-- CIVICS
		('LEADER_CVS_KUDARAT_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_KUDARAT_CIVICS',		'CIVIC_EXPLORATION',					1		),
		('LEADER_CVS_KUDARAT_CIVICS',		'CIVIC_MYSTICISM',						1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_CIVICS',		'CIVIC_THEOLOGY',						1		), -- LEADER SPECIFIC
		-- DISTRICTS
		('LEADER_CVS_KUDARAT_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_KUDARAT_DISTRICTS',	'DISTRICT_HARBOR',						1		),
		('LEADER_CVS_KUDARAT_DISTRICTS',	'DISTRICT_HOLY_SITE',					1		), -- LEADER SPECIFIC
		-- BUILDINGS
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_CVS_PHILIPPINES_UI',			1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_BANK',						1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_LIGHTHOUSE',					1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_SHIPYARD',					1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_SEAPORT',						1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_SHRINE',						1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_TEMPLE',						1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_WALLS',						1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_CASTLE',						1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_STAR_FORT',					1		), -- LEADER SPECIFIC
		-- WONDERS
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_COLOSSUS',					1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_EIFFEL_TOWER',				1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_GREAT_LIGHTHOUSE',			1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_VENETIAN_ARSENAL',			1		),
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_STONEHENGE',					1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_HAGIA_SOPHIA',				1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_MAHABODHI_TEMPLE',			1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_MONT_ST_MICHEL',				1		), -- LEADER SPECIFIC
		('LEADER_CVS_KUDARAT_BUILDINGS',	'BUILDING_ORACLE',						1		), -- LEADER SPECIFIC
		-- PROJECTS
		-- TACTICS
		-- DIPLOMACY
		('LEADER_CVS_KUDARAT_DIPLOMACY',	'DIPLOACTION_PROPOSE_TRADE',			1		);

INSERT INTO AiFavoredItems
		(ListType,							Item,								Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_KUDARAT_EXPANSION',	'Coastal',							1,			15,		NULL					),
		('LEADER_CVS_KUDARAT_EXPANSION',	'Resource Class',					1,			5,		'RESOURCECLASS_BONUS'	),
		('LEADER_CVS_KUDARAT_EXPANSION',	'Resource Class',					1,			5,		'RESOURCECLASS_LUXURY'	),
		('LEADER_CVS_KUDARAT_EXPANSION',	'New Resources',					1,			15,		NULL					),
		('LEADER_CVS_KUDARAT_EXPANSION',	'Specific Feature',					1,			5,		'FEATURE_CLIFFS_DOVER'	),
		('LEADER_CVS_KUDARAT_EXPANSION',	'Specific Feature',					1,			5,		'FEATURE_PIOPIOTAHI'	),
		-- PSUEDOS
		('LEADER_CVS_KUDARAT_PSUEDOS',		'PSEUDOYIELD_UNIT_TRADE',			1,			5,		NULL					),
		('LEADER_CVS_KUDARAT_PSUEDOS',		'PSEUDOYIELD_GPP_MERCHANT',			1,			30,		NULL					),
		('LEADER_CVS_KUDARAT_PSUEDOS',		'PSEUDOYIELD_GPP_ADMIRAL',			1,			30,		NULL					),
		('LEADER_CVS_KUDARAT_PSUEDOS',		'PSEUDOYIELD_GPP_PROPHET',			1,			50,		NULL					),
		('LEADER_CVS_KUDARAT_PSUEDOS',		'PSEUDOYIELD_UNIT_NAVAL_COMBAT',	1,			30,		NULL					),
		('LEADER_CVS_KUDARAT_PSUEDOS',		'PSEUDOYIELD_UNIT_RELIGIOUS',		1,			30,		NULL					);