/*
	Strategy
	Credits: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType						)
VALUES 	('LEADER_CVS_ESCHER_TECHS'		),
		('LEADER_CVS_ESCHER_CIVICS'		),
		('LEADER_CVS_ESCHER_DISTRICTS'	),
		('LEADER_CVS_ESCHER_BUILDINGS'	),
		('LEADER_CVS_ESCHER_PROJECTS'	),
		('LEADER_CVS_ESCHER_DIPLOMACY'	),
		('LEADER_CVS_ESCHER_EXPANSION'	),
		('LEADER_CVS_ESCHER_PSUEDOS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,						LeaderType,					System				)
VALUES  ('LEADER_CVS_ESCHER_TECHS',		'TRAIT_LEADER_CVS_ESCHER',	'Technologies'		),
		('LEADER_CVS_ESCHER_CIVICS',	'TRAIT_LEADER_CVS_ESCHER',	'Civics'			),
		('LEADER_CVS_ESCHER_DISTRICTS',	'TRAIT_LEADER_CVS_ESCHER',	'Districts'			),
		('LEADER_CVS_ESCHER_BUILDINGS',	'TRAIT_LEADER_CVS_ESCHER',	'Buildings'			),
		('LEADER_CVS_ESCHER_PROJECTS',	'TRAIT_LEADER_CVS_ESCHER',	'Projects'			),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'TRAIT_LEADER_CVS_ESCHER',	'DiplomaticActions'	),
		('LEADER_CVS_ESCHER_EXPANSION',	'TRAIT_LEADER_CVS_ESCHER',	'PlotEvaluations'	),
		('LEADER_CVS_ESCHER_PSUEDOS',	'TRAIT_LEADER_CVS_ESCHER',	'PsuedoYields'		);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,						Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_ESCHER_TECHS',		'TECH_CURRENCY',							1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_MATHEMATICS',							1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_CONSTRUCTION',						1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_APPRENTICESHIP',						1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_ENGINEERING',							1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_BANKING',								1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_INDUSTRIALIZATION',					1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_MACHINERY',							1		),
		('LEADER_CVS_ESCHER_TECHS',		'TECH_ECONOMICS',							1		),
		-- CIVICS
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_MERCENARIES',						1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_DIPLOMATIC_SERVICE',					1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_CRAFTMANSHIP',						1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_FOREIGN_TRADE',						1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_STATE_WORKFORCE',					1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_POLITICAL_PHILOSOPHY',				1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_ESCHER_CIVICS',	'CIVIC_CIVIL_ENGINEERING',					1		),
		-- DISTRICTS
		('LEADER_CVS_ESCHER_DISTRICTS',	'DISTRICT_GOVERNMENT',						1		),
		('LEADER_CVS_ESCHER_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',					1		),
		('LEADER_CVS_ESCHER_DISTRICTS',	'DISTRICT_INDUSTRIAL_ZONE',					1		),
		-- BUILDINGS
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_MARKET',							1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_CVS_SWITZERLAND_UI',				1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',					1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_WORKSHOP',						1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_FACTORY',							1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_POWER_PLANT',						1		),
		-- WONDERS
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_KILWA_KISIWANI',					1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_APADANA',							1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_COLOSSUS',						1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_PETRA',							1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',					1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_BIG_BEN',							1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_RUHR_VALLEY',						1		),
		('LEADER_CVS_ESCHER_BUILDINGS',	'BUILDING_CASA_DE_CONTRATACION',			1		),
		-- DIPLOMACY
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_COLONIAL_WAR',			0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_FORMAL_WAR',			0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_GOLDEN_AGE_WAR',		0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_HOLY_WAR',				0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_IDEOLOGICAL_WAR',		0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_LIBERATION_WAR',		0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_RECONQUEST_WAR',		0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_SURPRISE_WAR',			0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_TERRITORIAL_WAR',		0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DECLARE_WAR_OF_RETRIBUTION',	0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DEMAND_TRIBUTE',				0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_DENOUNCE',						0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_JOINT_WAR',					0		),
		('LEADER_CVS_ESCHER_DIPLOMACY',	'DIPLOACTION_USE_NUCLEAR_WEAPON',			0		);	
		
INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_ESCHER_EXPANSION',		'Specific Feature',						1,			5,		'FEATURE_FLOODPLAINS'		),
		('LEADER_CVS_ESCHER_EXPANSION',		'Specific Feature',						1,			3,		'FEATURE_MATTERHORN'		),
		('LEADER_CVS_ESCHER_EXPANSION',		'Specific Feature',						1,			3,		'FEATURE_UBSUNUR_HOLLOW'	),
		('LEADER_CVS_ESCHER_EXPANSION',		'Specific Feature',						1,			3,		'FEATURE_ULURU'				),
		('LEADER_CVS_ESCHER_EXPANSION',		'Specific Feature',						1,			3,		'FEATURE_EVEREST'			),
		-- PSUEDOS
		('LEADER_CVS_ESCHER_PSUEDOS',		'PSEUDOYIELD_GPP_MERCHANT',				1,			15,		NULL						),
		('LEADER_CVS_ESCHER_PSUEDOS',		'PSEUDOYIELD_GPP_ENGINEER',				1,			15,		NULL						),
		('LEADER_CVS_ESCHER_PSUEDOS',		'PSEUDOYIELD_UNIT_TRADE',				1,			2.0,	NULL						),
		('LEADER_CVS_ESCHER_PSUEDOS',		'PSEUDOYIELD_INFLUENCE',				1,			10,		NULL						),
		('LEADER_CVS_ESCHER_PSUEDOS',		'PSEUDOYIELD_GOVERNOR',					1,			5,		NULL						),
		('LEADER_CVS_ESCHER_PSUEDOS',		'PSEUDOYIELD_DIPLOMATIC_BONUS',			1,			50,		NULL						);
