--- Players

INSERT INTO Players
			(CivilizationType, 		LeaderType, 		CivilizationName,				CivilizationIcon, 						LeaderName, 					LeaderIcon, 				CivilizationAbilityName,					CivilizationAbilityDescription,						CivilizationAbilityIcon,				LeaderAbilityName,									LeaderAbilityDescription, 								LeaderAbilityIcon, 			Portrait,					PortraitBackground)
VALUES		('CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'LOC_CIVILIZATION_CVS_PHILIPPINES_NAME',	'ICON_CIVILIZATION_CVS_PHILIPPINES',	'LOC_LEADER_CIVITAS_CORY_NAME',	'ICON_LEADER_CIVITAS_CORY',	'LOC_TRAIT_CIVILIZATION_CVS_PHILIPPINES_UA_NAME',	'LOC_TRAIT_CIVILIZATION_CVS_PHILIPPINES_UA_DESCRIPTION',	'ICON_CIVILIZATION_CVS_PHILIPPINES',	'LOC_TRAIT_LEADER_CIVITAS_CORY_INA_ING_DEMOKRASYA_NAME',	'LOC_TRAIT_LEADER_CIVITAS_CORY_INA_ING_DEMOKRASYA_DESCRIPTION',	'ICON_LEADER_CIVITAS_CORY',	'LEADER_CIVITAS_CORY_NEUTRAL', 'LEADER_GORGO_BACKGROUND');

--- Player Items

INSERT INTO PlayerItems
			(CivilizationType,		LeaderType,			Type,					Name,							Description,							Icon,						SortIndex)
VALUES		('CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'UNIT_CVS_PHILIPPINES_UU',	'LOC_UNIT_CVS_PHILIPPINES_UU_NAME',	'LOC_UNIT_CVS_PHILIPPINES_UU_DESCRIPTION',	'ICON_UNIT_CVS_PHILIPPINES_UU',	10),
			('CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'BUILDING_CVS_PHILIPPINES_UI',		'LOC_BUILDING_CVS_PHILIPPINES_UI_NAME',	'LOC_BUILDING_CVS_PHILIPPINES_UI_DESCRIPTION',		'ICON_BUILDING_CVS_PHILIPPINES_UI',	20);

--- Players

INSERT INTO Players
			(Domain,						CivilizationType, 		LeaderType, 		CivilizationName,				CivilizationIcon, 						LeaderName, 					LeaderIcon, 				CivilizationAbilityName,					CivilizationAbilityDescription,						CivilizationAbilityIcon,				LeaderAbilityName,									LeaderAbilityDescription, 								LeaderAbilityIcon, 			Portrait,					PortraitBackground)
VALUES		('Players:Expansion1_Players',	'CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'LOC_CIVILIZATION_CVS_PHILIPPINES_NAME',	'ICON_CIVILIZATION_CVS_PHILIPPINES',	'LOC_LEADER_CIVITAS_CORY_NAME',	'ICON_LEADER_CIVITAS_CORY',	'LOC_TRAIT_CIVILIZATION_CVS_PHILIPPINES_UA_NAME',	'LOC_TRAIT_CIVILIZATION_CVS_PHILIPPINES_UA_DESCRIPTION',	'ICON_CIVILIZATION_CVS_PHILIPPINES',	'LOC_TRAIT_LEADER_CIVITAS_CORY_INA_ING_DEMOKRASYA_NAME',	'LOC_TRAIT_LEADER_CIVITAS_CORY_INA_ING_DEMOKRASYA_DESCRIPTION',	'ICON_LEADER_CIVITAS_CORY',	'LEADER_CIVITAS_CORY_NEUTRAL', 'LEADER_GORGO_BACKGROUND');

--- Player Items

INSERT INTO PlayerItems
			(Domain,						CivilizationType,		LeaderType,			Type,					Name,							Description,							Icon,						SortIndex)
VALUES		('Players:Expansion1_Players',	'CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'UNIT_CVS_PHILIPPINES_UU',	'LOC_UNIT_CVS_PHILIPPINES_UU_NAME',	'LOC_UNIT_CVS_PHILIPPINES_UU_DESCRIPTION',	'ICON_UNIT_CVS_PHILIPPINES_UU',	10),
			('Players:Expansion1_Players',	'CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'BUILDING_CVS_PHILIPPINES_UI',		'LOC_BUILDING_CVS_PHILIPPINES_UI_NAME',	'LOC_BUILDING_CVS_PHILIPPINES_UI_DESCRIPTION',		'ICON_BUILDING_CVS_PHILIPPINES_UI',	20);


--- Players

INSERT INTO Players
			(Domain,						CivilizationType, 		LeaderType, 		CivilizationName,				CivilizationIcon, 						LeaderName, 					LeaderIcon, 				CivilizationAbilityName,					CivilizationAbilityDescription,						CivilizationAbilityIcon,				LeaderAbilityName,									LeaderAbilityDescription, 								LeaderAbilityIcon, 			Portrait,					PortraitBackground)
VALUES		('Players:Expansion2_Players',	'CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'LOC_CIVILIZATION_CVS_PHILIPPINES_NAME',	'ICON_CIVILIZATION_CVS_PHILIPPINES',	'LOC_LEADER_CIVITAS_CORY_NAME',	'ICON_LEADER_CIVITAS_CORY',	'LOC_TRAIT_CIVILIZATION_CVS_PHILIPPINES_UA_NAME',	'LOC_TRAIT_CIVILIZATION_CVS_PHILIPPINES_UA_DESCRIPTION',	'ICON_CIVILIZATION_CVS_PHILIPPINES',	'LOC_TRAIT_LEADER_CIVITAS_CORY_INA_ING_DEMOKRASYA_NAME',	'LOC_TRAIT_LEADER_CIVITAS_CORY_INA_ING_DEMOKRASYA_DESCRIPTION',	'ICON_LEADER_CIVITAS_CORY',	'LEADER_CIVITAS_CORY_NEUTRAL', 'LEADER_GORGO_BACKGROUND');

--- Player Items

INSERT INTO PlayerItems
			(Domain,						CivilizationType,		LeaderType,			Type,					Name,							Description,							Icon,						SortIndex)
VALUES		('Players:Expansion2_Players',	'CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'UNIT_CVS_PHILIPPINES_UU',	'LOC_UNIT_CVS_PHILIPPINES_UU_NAME',	'LOC_UNIT_CVS_PHILIPPINES_UU_DESCRIPTION',	'ICON_UNIT_CVS_PHILIPPINES_UU',	10),
			('Players:Expansion2_Players',	'CIVILIZATION_CVS_PHILIPPINES',	'LEADER_CIVITAS_CORY',	'BUILDING_CVS_PHILIPPINES_UI',		'LOC_BUILDING_CVS_PHILIPPINES_UI_NAME',	'LOC_BUILDING_CVS_PHILIPPINES_UI_DESCRIPTION',		'ICON_BUILDING_CVS_PHILIPPINES_UI',	20);