/*
	Strategy
	Authors: SeelingCat, Sailor Cat
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType						)
VALUES 	('LEADER_CVS_DIHYA_TECHS'		),
		('LEADER_CVS_DIHYA_CIVICS'		),
		('LEADER_CVS_DIHYA_DISTRICTS'	),
		('LEADER_CVS_DIHYA_BUILDINGS'	),
		('LEADER_CVS_DIHYA_PROJECTS'	),
		('LEADER_CVS_DIHYA_DIPLOMACY'	),
		('LEADER_CVS_DIHYA_TACTICS'		),
		('LEADER_CVS_DIHYA_EXPANSION'	),
		('LEADER_CVS_DIHYA_PSUEDOS'		),
		('LEADER_CVS_DIHYA_YIELDS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							AgendaType,					System				)
VALUES  ('LEADER_CVS_DIHYA_TECHS',			'TRAIT_AGENDA_CVS_DIHYA',	'Technologies'		),
		('LEADER_CVS_DIHYA_CIVICS',			'TRAIT_AGENDA_CVS_DIHYA',	'Civics'			),
		('LEADER_CVS_DIHYA_DISTRICTS',		'TRAIT_AGENDA_CVS_DIHYA',	'Districts'			),
		('LEADER_CVS_DIHYA_BUILDINGS',		'TRAIT_AGENDA_CVS_DIHYA',	'Buildings'			),
		('LEADER_CVS_DIHYA_PROJECTS',		'TRAIT_AGENDA_CVS_DIHYA',	'Projects'			),
		('LEADER_CVS_DIHYA_DIPLOMACY',		'TRAIT_AGENDA_CVS_DIHYA',	'DiplomaticActions'	),
		('LEADER_CVS_DIHYA_TACTICS',		'TRAIT_AGENDA_CVS_DIHYA',	'Tactics'			),
		('LEADER_CVS_DIHYA_EXPANSION',		'TRAIT_AGENDA_CVS_DIHYA',	'PlotEvaluations'	),
		('LEADER_CVS_DIHYA_PSUEDOS',		'TRAIT_AGENDA_CVS_DIHYA',	'PsuedoYields'		),
		('LEADER_CVS_DIHYA_YIELDS',			'TRAIT_AGENDA_CVS_DIHYA',	'Yields'			);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,						Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_DIHYA_TECHS',		'TECH_IRRIGATION',						1		),
		('LEADER_CVS_DIHYA_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_DIHYA_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_DIHYA_TECHS',		'TECH_ECONOMICS',						1		),
		-- CIVICS
		('LEADER_CVS_DIHYA_CIVICS',		'CIVIC_MILITARY_TRAINING',				1		),
		('LEADER_CVS_DIHYA_CIVICS',		'CIVIC_GAMES_RECREATION',				1		),
		('LEADER_CVS_DIHYA_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_DIHYA_CIVICS',		'CIVIC_MERCANTILISM',					1		),
		('LEADER_CVS_DIHYA_CIVICS',		'CIVIC_NATURAL_HISTORY',				1		),
		('LEADER_CVS_DIHYA_CIVICS',		'CIVIC_PROFESSIONAL_SPORTS',			1		),
		-- DISTRICTS
		('LEADER_CVS_DIHYA_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_DIHYA_DISTRICTS',	'DISTRICT_ENTERTAINMENT_COMPLEX',		1		),
		-- BUILDINGS
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_MARKET',						1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_BANK',						1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_ARENA',						1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_ZOO',							1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_STADIUM',						1		),
		-- WONDERS
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_PETRA',						1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_COLOSSEUM',					1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_COLOSSUS',					1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_ESTADIO_DO_MARACANA',			1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_GOLDEN_GATE_BRIDGE',			1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_HANGING_GARDENS',				1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_MACHU_PICCHU',				1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_PYRAMIDS',					1		),
		('LEADER_CVS_DIHYA_BUILDINGS',	'BUILDING_UNIVERSITY_SANKORE',			1		);

INSERT INTO AiFavoredItems
		(ListType,						Item,							Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_DIHYA_EXPANSION',	'Specific Feature',				1,			10,		'FEATURE_OASIS'			),
		('LEADER_CVS_DIHYA_EXPANSION',	'Specific Feature',				1,			5,		'FEATURE_FLODOPLAINS'	),
		-- PSUEDOS
		('LEADER_CVS_DIHYA_PSUEDOS',	'PSEUDOYIELD_DIPLOMATIC_BONUS',	1,			10,		NULL					),
		('LEADER_CVS_DIHYA_PSUEDOS',	'PSEUDOYIELD_GPP_MERCHANT',		1,			50,		NULL					),
		('LEADER_CVS_DIHYA_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',		1,			50,		NULL					),
		('LEADER_CVS_DIHYA_PSUEDOS',	'PSEUDOYIELD_HAPPINESS',		1,			50,		NULL					),
		-- YIELDS
		('LEADER_CVS_DIHYA_YIELDS',		'YIELD_GOLD',					1,			50,		NULL					);

