/*
	Strategy
	Credits: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_ROLLO_TECHS'			),
		('LEADER_CVS_ROLLO_CIVICS'			),
		('LEADER_CVS_ROLLO_DISTRICTS'		),
		('LEADER_CVS_ROLLO_BUILDINGS'		),
		('LEADER_CVS_ROLLO_PROJECTS'		),
		('LEADER_CVS_ROLLO_DIPLOMACY'		),
		('LEADER_CVS_ROLLO_TACTICS'			),
		('LEADER_CVS_ROLLO_EXPANSION'		),
		('LEADER_CVS_ROLLO_PSUEDOS'			),
		('LEADER_CVS_ROLLO_YIELDS'			),
		('LEADER_CVS_ROLLO_ALLIANCES'		),
		('LEADER_CVS_ROLLO_COMMEMORATIONS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							AgendaType,					System				)
VALUES  ('LEADER_CVS_ROLLO_TECHS',			'TRAIT_AGENDA_CVS_ROLLO',	'Technologies'		),
		('LEADER_CVS_ROLLO_CIVICS',			'TRAIT_AGENDA_CVS_ROLLO',	'Civics'			),
		('LEADER_CVS_ROLLO_DISTRICTS',		'TRAIT_AGENDA_CVS_ROLLO',	'Districts'			),
		('LEADER_CVS_ROLLO_BUILDINGS',		'TRAIT_AGENDA_CVS_ROLLO',	'Buildings'			),
		('LEADER_CVS_ROLLO_PROJECTS',		'TRAIT_AGENDA_CVS_ROLLO',	'Projects'			),
		('LEADER_CVS_ROLLO_DIPLOMACY',		'TRAIT_AGENDA_CVS_ROLLO',	'DiplomaticActions'	),
		('LEADER_CVS_ROLLO_TACTICS',		'TRAIT_AGENDA_CVS_ROLLO',	'Tactics'			),
		('LEADER_CVS_ROLLO_EXPANSION',		'TRAIT_AGENDA_CVS_ROLLO',	'PlotEvaluations'	),
		('LEADER_CVS_ROLLO_PSUEDOS',		'TRAIT_AGENDA_CVS_ROLLO',	'PsuedoYields'		),
		('LEADER_CVS_ROLLO_YIELDS',			'TRAIT_AGENDA_CVS_ROLLO',	'Yields'			),
		('LEADER_CVS_ROLLO_ALLIANCES',		'TRAIT_AGENDA_CVS_ROLLO',	'Alliances'			),
		('LEADER_CVS_ROLLO_COMMEMORATIONS',	'TRAIT_AGENDA_CVS_ROLLO',	'Commemorations'	);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_ROLLO_TECHS',			'TECH_BRONZE_WORKING',						1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_HORSEBACK_RIDING',					1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_THE_WHEEL',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_CURRENCY',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_IRON_WORKING',						1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_MATHEMATICS',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_CONSTRUCTION',						1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_STIRRUPS',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_ENGINEERING',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_MILITARY_ENGINEERING',				1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_BANKING',								1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_METAL_CASTING',						1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_MILITARY_SCIENCE',					1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_ECONOMICS',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_SAILING',								1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_CELESTIAL_NAVIGATION',				1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_SHIPBUILDING',						1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_CARTOGRAPHY',							1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_MASS_PRODUCTION',						1		),
		('LEADER_CVS_ROLLO_TECHS',			'TECH_SQUARE_RIGGING',						1		),
		-- CIVICS
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_CRAFTMANSHIP',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_FOREIGN_TRADE',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_MILITARY_TRAINING',					1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_MILITARY_TRADITION',					1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_FEUDALISM',							1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_NATIONALISM',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_DIVINE_RIGHT',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_DEFENSIVE_TACTICS',					1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_NAVAL_TRADITION',					1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_EXPLORATION',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_MERCANTILISM',						1		),
		('LEADER_CVS_ROLLO_CIVICS',			'CIVIC_COLONIALISM',						1		),
		-- DISTRICTS
		('LEADER_CVS_ROLLO_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1		),
		('LEADER_CVS_ROLLO_DISTRICTS',		'DISTRICT_COMMERCIAL_HUB',					1		),
		('LEADER_CVS_ROLLO_DISTRICTS',		'DISTRICT_HARBOR',							1		),
		-- BUILDINGS
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_MARKET',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_BARRACKS',						1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_STABLE',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_BANK',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_ARMORY',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_STOCK_EXCHANGE',					1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_MILITARY_ACADEMY',				1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_LIGHTHOUSE',						1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_DRYDOCK',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_SEAPORT',							1		),
		-- WONDERS
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_TERRACOTTA_ARMY',					1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_JEBEL_BARKAL',					1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_COLOSSUS',						1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_PETRA',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_GREAT_ZIMBABWE',					1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_BIG_BEN',							1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_GREAT_LIGHTHOUSE',				1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_VENETIAN_ARSENAL',				1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_STATUE_LIBERTY',					1		),
		('LEADER_CVS_ROLLO_BUILDINGS',		'BUILDING_HALICARNASSUS_MAUSOLEUM',			1		),
		-- ALLIANCES
		('LEADER_CVS_ROLLO_ALLIANCES',		'ALLIANCE_MILITARY',						1		),
		('LEADER_CVS_ROLLO_ALLIANCES',		'ALLIANCE_ECONOMIC',						1		),
		-- COMMEMORATIONS
		('LEADER_CVS_ROLLO_COMMEMORATIONS',	'COMMEMORATION_EXPLORATION',				1		),
		('LEADER_CVS_ROLLO_COMMEMORATIONS',	'COMMEMORATION_MILITARY',					1		),
		('LEADER_CVS_ROLLO_COMMEMORATIONS',	'COMMEMORATION_ECONOMIC',					1		),
		-- DIPLOMACY
		('LEADER_CVS_ROLLO_DIPLOMACY',		'DIPLOACTION_ALLIANCE_MILITARY',			1		),
		-- TACTICS
		('LEADER_CVS_ROLLO_TACTICS',		'Pillage Improvement',						1		),
		('LEADER_CVS_ROLLO_TACTICS',		'Pillage Districts',						1		);
		
INSERT INTO AiFavoredItems
		(ListType,						Item,								Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_ROLLO_EXPANSION',	'Resource Class',					1,			5,		'RESOURCECLASS_STRATEGIC'	),
		('LEADER_CVS_ROLLO_EXPANSION',	'Foreign Continent',				1,			120,	NULL						),
		('LEADER_CVS_ROLLO_EXPANSION',	'Coastal',							1,			30,		NULL						),
		-- PSUEDOS
		('LEADER_CVS_ROLLO_PSUEDOS',	'PSEUDOYIELD_GPP_ADMIRAL',			1,			15,		NULL						),
		('LEADER_CVS_ROLLO_PSUEDOS',	'PSEUDOYIELD_IMPROVEMENT',			1,			5,		NULL						),
		('LEADER_CVS_ROLLO_PSUEDOS',	'PSEUDOYIELD_UNIT_NAVAL_COMBAT',	1,			20,		NULL						);

