/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_VLAD_III_TECHS'		),
		('LEADER_CVS_VLAD_III_CIVICS'		),
		('LEADER_CVS_VLAD_III_DISCUSSIONS'	),
		('LEADER_CVS_VLAD_III_DISTRICTS'	),
		('LEADER_CVS_VLAD_III_BUILDINGS'	),
		('LEADER_CVS_VLAD_III_PROJECTS'		),
		('LEADER_CVS_VLAD_III_DIPLOMACY'	),
		('LEADER_CVS_VLAD_III_TACTICS'		),
		('LEADER_CVS_VLAD_III_EXPANSION'	),
		('LEADER_CVS_VLAD_III_PSUEDOS'		),
		('LEADER_CVS_VLAD_III_YIELDS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							LeaderType,						System				)
VALUES  ('LEADER_CVS_VLAD_III_TECHS',		'TRAIT_LEADER_CVS_VLAD_III',	'Technologies'		),
		('LEADER_CVS_VLAD_III_CIVICS',		'TRAIT_LEADER_CVS_VLAD_III',	'Civics'			),
		('LEADER_CVS_VLAD_III_DISCUSSIONS',	'TRAIT_LEADER_CVS_VLAD_III',	'Discussions'		),
		('LEADER_CVS_VLAD_III_DISTRICTS',	'TRAIT_LEADER_CVS_VLAD_III',	'Districts'			),
		('LEADER_CVS_VLAD_III_BUILDINGS',	'TRAIT_LEADER_CVS_VLAD_III',	'Buildings'			),
		('LEADER_CVS_VLAD_III_PROJECTS',	'TRAIT_LEADER_CVS_VLAD_III',	'Projects'			),
		('LEADER_CVS_VLAD_III_DIPLOMACY',	'TRAIT_LEADER_CVS_VLAD_III',	'DiplomaticActions'	),
		('LEADER_CVS_VLAD_III_TACTICS',		'TRAIT_LEADER_CVS_VLAD_III',	'Tactics'			),
		('LEADER_CVS_VLAD_III_EXPANSION',	'TRAIT_LEADER_CVS_VLAD_III',	'PlotEvaluations'	),
		('LEADER_CVS_VLAD_III_PSUEDOS',		'TRAIT_LEADER_CVS_VLAD_III',	'PsuedoYields'		),
		('LEADER_CVS_VLAD_III_YIELDS',		'TRAIT_LEADER_CVS_VLAD_III',	'Yields'			);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,								Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_MACHINERY',							1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_BRONZE_WORKING',						1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_MASONRY',								1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_CASTLES',								1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_MILITARY_ENGINEERING',				1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_SIEGE_TACTICS',						1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_INDUSTRIALIZATION',					1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_REPLACEABLE_PARTS',					1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_FLIGHT',								1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_STEEL',								1		),
		('LEADER_CVS_VLAD_III_TECHS',			'TECH_PLASTICS',							1		), -- Vanatori Tech
		-- CIVICS
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_MEDIEVAL_FAIRES',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_MILITARY_TRADITION',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_MILITARY_TRAINING',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_NATIONALISM',						1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_DEFENSIVE_TACTICS',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_MERCENARIES',						1		), -- Calarasi Civic
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_DIPLOMATIC_SERVICE',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_MERCANTILISM',						1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_CONSERVATION',						1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_MASS_MEDIA',							1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_SUFFRAGE',							1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_CLASS_STRUGGLE',						1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_TOTALITARIANISM',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_RAPID_DEPLOYMENT',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_CULTURAL_HERITAGE',					1		),
		('LEADER_CVS_VLAD_III_CIVICS',			'CIVIC_CIVIL_ENGINEERING',					1		),
		-- DISTRICTS
		('LEADER_CVS_VLAD_III_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1		),
		-- BUILDINGS
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_ARMORY',							1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_CVS_ROMANIA_UI',					1		), -- Unique
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_MILITARY_ACADEMY',				1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_WALLS',							1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_CASTLE',							1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_STAR_FORT',						1		),
		-- WONDERS
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_FORBIDDEN_CITY',					1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_RUHR_VALLEY',						1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_TAJ_MAHAL',						1		),
		('LEADER_CVS_VLAD_III_BUILDINGS',		'BUILDING_TERRACOTTA_ARMY',					1		),
		-- DIPLOMACY
		('LEADER_CVS_VLAD_III_DIPLOMACY',		'DIPLOACTION_THIRD_PARTY_WAR',				1		),
		('LEADER_CVS_VLAD_III_DIPLOMACY',		'DIPLOACTION_JOINT_WAR',					1		),
		('LEADER_CVS_VLAD_III_DIPLOMACY',		'DIPLOACTION_LIBERATE_CITY',				0		),
		('LEADER_CVS_VLAD_III_DIPLOMACY',		'DIPLOACTION_DECLARE_LIBERATION_WAR',		0		),
		('LEADER_CVS_VLAD_III_DIPLOMACY',		'DIPLOACTION_DECLARE_TERRITORIAL_WAR',		1		),
		('LEADER_CVS_VLAD_III_DIPLOMACY',		'DIPLOACTION_OPEN_BORDERS',					0		),
		-- DISCUSSIONS
		('LEADER_CVS_VLAD_III_DISCUSSIONS',		'WC_EMERGENCY_MILITARY',					1		),
		('LEADER_CVS_VLAD_III_DISCUSSIONS',		'WC_EMERGENCY_CITY_STATE',					1		),
		('LEADER_CVS_VLAD_III_DISCUSSIONS',		'WC_EMERGENCY_RELIGIOUS',					1		),
		('LEADER_CVS_VLAD_III_DISCUSSIONS',		'WC_EMERGENCY_NUCLEAR',						1		),
		('LEADER_CVS_VLAD_III_DISCUSSIONS',		'WC_EMERGENCY_BACKSTAB',					1		),
		-- TACTICS
		('LEADER_CVS_VLAD_III_TACTICS',			'Pillage Improvement',						1		),
		('LEADER_CVS_VLAD_III_TACTICS',			'Pillage District',							1		);
		

INSERT INTO AiFavoredItems
		(ListType,							Item,							Favored,	Value,	StringVal	)
VALUES  -- PSUEDOS
		('LEADER_CVS_VLAD_III_PSUEDOS',		'PSEUDOYIELD_DIPLOMATIC_BONUS',	1,			-100,	NULL		),
		('LEADER_CVS_VLAD_III_PSUEDOS',		'PSEUDOYIELD_GPP_GENERAL',		1,			15,		NULL		),
		('LEADER_CVS_VLAD_III_PSUEDOS',		'PSEUDOYIELD_UNIT_COMBAT',		1,			20,		NULL		);

