/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType								)
VALUES 	('LEADER_CVS_SONNI_ALI_TECHS'			),
		('LEADER_CVS_SONNI_ALI_CIVICS'			),
		('LEADER_CVS_SONNI_ALI_DISTRICTS'		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS'		),
		('LEADER_CVS_SONNI_ALI_PROJECTS'		),
		('LEADER_CVS_SONNI_ALI_DIPLOMACY'		),
		('LEADER_CVS_SONNI_ALI_EXPANSION'		),
		('LEADER_CVS_SONNI_ALI_PSUEDOS'			),
		('LEADER_CVS_SONNI_ALI_YIELDS'			),
		-- XP1
		('LEADER_CVS_SONNI_ALI_ALLIANCES'		),
		('LEADER_CVS_SONNI_ALI_COMMEMORATIONS'	),
		-- XP2
		('LEADER_CVS_SONNI_ALI_DISCUSSIONS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								AgendaType,						System				) -- AgendaType links to a TraitType, not an AgendaType... :/
VALUES  ('LEADER_CVS_SONNI_ALI_TECHS',			'TRAIT_AGENDA_CVS_SONNI_ALI',	'Technologies'		),
		('LEADER_CVS_SONNI_ALI_CIVICS',			'TRAIT_AGENDA_CVS_SONNI_ALI',	'Civics'			),
		('LEADER_CVS_SONNI_ALI_DISTRICTS',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'Districts'			),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'Buildings'			),
		('LEADER_CVS_SONNI_ALI_PROJECTS',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'Projects'			),
		('LEADER_CVS_SONNI_ALI_DIPLOMACY',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'DiplomaticActions'	),
		('LEADER_CVS_SONNI_ALI_EXPANSION',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'PlotEvaluations'	),
		('LEADER_CVS_SONNI_ALI_PSUEDOS',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'PsuedoYields'		),
		('LEADER_CVS_SONNI_ALI_YIELDS',			'TRAIT_AGENDA_CVS_SONNI_ALI',	'Yields'			),
		-- XP1
		('LEADER_CVS_SONNI_ALI_ALLIANCES',		'TRAIT_AGENDA_CVS_SONNI_ALI',	'Alliances'			),
		('LEADER_CVS_SONNI_ALI_COMMEMORATIONS',	'TRAIT_AGENDA_CVS_SONNI_ALI',	'Commemorations'	),
		-- XP2
		('LEADER_CVS_SONNI_ALI_DISCUSSIONS',	'TRAIT_AGENDA_CVS_SONNI_ALI',	'Discussions'		);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,								Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_CURRENCY',							1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_MATHEMATICS',							1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_BANKING',								1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_ECONOMICS',							1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_BRONZE_WORKING',						1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_IRON_WORKING',						1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_MILITARY_SCIENCE',					1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_MILITARY_TACTICS',					1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_STIRRUPS',							1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_WRITING',								1		),
		('LEADER_CVS_SONNI_ALI_TECHS',			'TECH_EDUCATION',							1		),
		-- CIVICS
		('LEADER_CVS_SONNI_ALI_CIVICS',			'CIVIC_MILITARY_TRAINING',					1		),
		('LEADER_CVS_SONNI_ALI_CIVICS',			'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_SONNI_ALI_CIVICS',			'CIVIC_FOREIGN_TRADE',						1		),
		('LEADER_CVS_SONNI_ALI_CIVICS',			'CIVIC_DRAMA_POETRY',						1		),
		('LEADER_CVS_SONNI_ALI_CIVICS',			'CIVIC_FEUDALISM',							1		),
		('LEADER_CVS_SONNI_ALI_CIVICS',			'CIVIC_NATIONALISM',						1		),
		-- DISTRICTS
		('LEADER_CVS_SONNI_ALI_DISTRICTS',		'DISTRICT_CAMPUS',							1		),
		('LEADER_CVS_SONNI_ALI_DISTRICTS',		'DISTRICT_THEATER',							1		),
		('LEADER_CVS_SONNI_ALI_DISTRICTS',		'DISTRICT_COMMERCIAL_HUB',					1		),
		('LEADER_CVS_SONNI_ALI_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1		),
		-- BUILDINGS
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_MARKET',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_BANK',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_STOCK_EXCHANGE',					1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_STABLE',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_ARMORY',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_MILITARY_ACADEMY',				1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_LIBRARY',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_CVS_SONGHAI_UI',					1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_RESEARCH_LAB',					1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_AMPHITHEATER',					1		),
		-- WONDERS
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_PETRA',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_GREAT_ZIMBABWE',					1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_BIG_BEN',							1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_TERRACOTTA_ARMY',					1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_GREAT_LIBRARY',					1		),
		('LEADER_CVS_SONNI_ALI_BUILDINGS',		'BUILDING_OXFORD_UNIVERSITY',				1		),
		-- DIPLOMACY
		('LEADER_CVS_SONNI_ALI_DIPLOMACY',		'DIPLOACTION_ALLIANCE_ECONOMIC',			1		),
		('LEADER_CVS_SONNI_ALI_DIPLOMACY',		'DIPLOACTION_ALLIANCE_MILITARY',			1		),
		-- ALLIANCES (XP1)
		('LEADER_CVS_SONNI_ALI_ALLIANCES',		'ALLIANCE_ECONOMIC',						1		),
		('LEADER_CVS_SONNI_ALI_ALLIANCES',		'ALLIANCE_MILITARY',						1		),
		-- COMMEMORATIONS (XP1)
		('LEADER_CVS_SONNI_ALI_COMMEMORATIONS',	'COMMEMORATION_ECONOMIC',					1		),
		('LEADER_CVS_SONNI_ALI_COMMEMORATIONS',	'COMMEMORATION_MILITARY',					1		),
		-- XP2
		('LEADER_CVS_SONNI_ALI_DISCUSSIONS',	'WC_EMERGENCY_MILITARY',					0		),
		('LEADER_CVS_SONNI_ALI_DISCUSSIONS',	'WC_EMERGENCY_NUCLEAR',						0		);
		
INSERT INTO AiFavoredItems
		(ListType,							Item,								Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_SONNI_ALI_EXPANSION',	'Resource Class',					1,			7,		'RESOURCECLASS_STRATEGIC'	),
		('LEADER_CVS_SONNI_ALI_EXPANSION',	'Specific Feature',					1,			10,		'FEATURE_FLOODPLAINS'		),
		-- PSUEDOS
		('LEADER_CVS_SONNI_ALI_PSUEDOS',	'PSEUDOYIELD_GPP_MERCHANT',			1,			15,		NULL						),
		('LEADER_CVS_SONNI_ALI_PSUEDOS',	'PSEUDOYIELD_GPP_GENERAL',			1,			30,		NULL						),
		('LEADER_CVS_SONNI_ALI_PSUEDOS',	'PSEUDOYIELD_UNIT_COMBAT',			1,			50,		NULL						),
		('LEADER_CVS_SONNI_ALI_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',			1,			2.0,	NULL						),
		-- YIELDS
		('LEADER_CVS_SONNI_ALI_YIELDS',		'YIELD_GOLD',						1,			20,		NULL						),
		('LEADER_CVS_SONNI_ALI_YIELDS',		'YIELD_SCIENCE',					1,			20,		NULL						);