/*
	Mod Support RwF
	Credits: Chrisy15
*/

-----------------------------------------------
-- JFD'S RULE WITH FAITH
-----------------------------------------------

CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 	 			default null,
	LeaderTitle						text				default null,
	PolicyType  					text 		 		default null);

CREATE TABLE IF NOT EXISTS 
	Leader_Titles (
	LeaderType  			text 		 		DEFAULT NULL,
	GovernmentType			text 	 			DEFAULT NULL,
	LeaderTitle				text				DEFAULT NULL,
	PolicyType  			text 		 		DEFAULT NULL,
	UseFeminine				BOOLEAN				DEFAULT 0,
	TitleIsFullName			BOOLEAN				DEFAULT 0);
	
INSERT INTO Civilization_Titles
		(CivilizationType, 			GovernmentType, 							PolicyType,				LeaderTitle)
VALUES	('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_AKKAD'),					--Chiefdom	-- Abgal
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_AKKAD'),						--Horde	-- Udul
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_AKKAD'),						--Polis -- En
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_AKKAD'),					--Autocracy -- Ensi
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_AKKAD'),					--Oligarchy -- Nam
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_AKKAD'),			--Classical Democracy -- Dikud
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_AKKAD'),				--Feudal Monarchy -- Sarru
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_AKKAD'),			--Merchant Republic -- Damgargal
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_AKKAD'),		--Theocracy -- Ezi
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD'),					--Absolute Monarchy -- Lugal
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD'),					--Constitutional Monarchy -- Lugal
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_AKKAD'),					--Noble Republic -- Nam
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_AKKAD'),			--Liberal Democracy -- Paqidu
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_AKKAD'),			--People's Republic -- Ummia
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_AKKAD'),		--Military Guardianship -- Sakkanak
		('CIVILIZATION_CVS_AKKAD',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD'),					--Empire -- Lugal
		
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_AKKAD_FEMININE'),					--Chiefdom	-- Amagal
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_AKKAD_FEMININE'),						--Horde	-- Udul
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_AKKAD_FEMININE'),						--Polis -- En
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_AKKAD_FEMININE'),					--Autocracy -- Ensi
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_AKKAD_FEMININE'),					--Oligarchy -- Nin
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_AKKAD_FEMININE'),		--Classical Democracy -- Dikud
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_AKKAD_FEMININE'),			--Feudal Monarchy -- Sarratu
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_AKKAD_FEMININE'),			--Merchant Republic -- Damgargal
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_AKKAD_FEMININE'),		--Theocracy -- Lukur
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD_FEMININE'),					--Absolute Monarchy -- Eres
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD_FEMININE'),					--Constitutional Monarchy -- Eres
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_AKKAD_FEMININE'),					--Noble Republic -- Nin
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_AKKAD_FEMININE'),			--Liberal Democracy -- Paqidu
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_AKKAD_FEMININE'),			--People's Republic -- Ummia
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_AKKAD_FEMININE'),		--Military Guardianship -- Sakkanak
		('CIVILIZATION_CVS_AKKAD',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD_FEMININE');					--Empire -- Eres
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_AKKAD' AND GovernmentType IS NOT null AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_AKKAD' AND PolicyType IS NOT null AND PolicyType NOT IN (SELECT PolicyType FROM Policies);				

-- And then in case the update hasn't come out yet:

INSERT INTO Leader_Titles
				(LeaderType, 					GovernmentType, 							PolicyType,				LeaderTitle																	)
SELECT DISTINCT	'LEADER_CVS_SARGON',			GovernmentType, 							PolicyType,				LeaderTitle
FROM Civilization_Titles WHERE LeaderTitle NOT LIKE "%FEMININE" AND CivilizationType = 'CIVILIZATION_CVS_AKKAD';

