--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- SIAM
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_SIAM_NAME",
		"Siam"	),
		("LOC_CIVILIZATION_SUK_SIAM_DESCRIPTION",
		"Siamese Empire"	),
		("LOC_CIVILIZATION_SUK_SIAM_ADJECTIVE",
		"Siamese"	),
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_SRI_AYUTTHAYA_NAME",
		"Sri Ayutthaya"	),
		("LOC_TRAIT_CIVILIZATION_SUK_SRI_AYUTTHAYA_DESCRIPTION",
		"Cities founded next to a River gain +2 [ICON_Housing] Housing, +1 [ICON_Amenities] Amenity. Specialty Districts next to a River provide +1 [ICON_Food] Food. Receive an additional [ICON_Envoy] Envoy from Civics that provide [ICON_Envoy] Envoys."),
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------
		("LOC_CITY_NAME_SIAM_KRUNG_THEP",
		"Krung Thep"),
		("LOC_CITY_NAME_SIAM_AYUTTHAYA",
		"Ayutthaya"),
		("LOC_CITY_NAME_SIAM_SUKHOTHAI",
		"Sukhothai"),
		("LOC_CITY_NAME_SIAM_PHITSANULOK",
		"Phitsanulok"),
		("LOC_CITY_NAME_SIAM_CHIANG_MAI",
		"Chiang Mai"),
		("LOC_CITY_NAME_SIAM_NAKHON_SI_THAMMARAT",
		"Nakhon Si Thammarat"),
		("LOC_CITY_NAME_SIAM_LAMPANG",
		"Lampang"),
		("LOC_CITY_NAME_SIAM_KAMPHAENG_PHET",
		"Kamphaeng Phet"),
		("LOC_CITY_NAME_SIAM_RATCHABURI",
		"Ratchaburi"),
		("LOC_CITY_NAME_SIAM_LOPBURI",
		"Lopburi"),
		("LOC_CITY_NAME_SIAM_CHIANG_RAI",
		"Chiang Rai"),
		("LOC_CITY_NAME_SIAM_NAKHON_RATCHASIMA",
		"Nakhon Ratchasima"),
		("LOC_CITY_NAME_SIAM_NAKHON_SAWAN",
		"Nakhon Sawan"),
		("LOC_CITY_NAME_SIAM_NONTHABURI",
		"Nonthaburi"),
		("LOC_CITY_NAME_SIAM_UBON_RATCHATHANI",
		"Ubon Ratchathani"),
		("LOC_CITY_NAME_SIAM_UDON_THANI",
		"Udon Thani"),
		("LOC_CITY_NAME_SIAM_NAKHON_PATHOM",
		"Nakhon Pathom"),
		("LOC_CITY_NAME_SIAM_KANCHANABURI",
		"Kanchanaburi"),
		("LOC_CITY_NAME_SIAM_KHON_KAEN",
		"Khon Kaen"),
		("LOC_CITY_NAME_SIAM_SURIN",
		"Surin"),
		("LOC_CITY_NAME_SIAM_PHIMAI",
		"Phimai"),
		("LOC_CITY_NAME_SIAM_PHETCHABURI",
		"Phetchaburi"),
		("LOC_CITY_NAME_SIAM_SI_SATCHANALAI",
		"Si Satchanalai"),
		("LOC_CITY_NAME_SIAM_NAN",
		"Nan"),
		("LOC_CITY_NAME_SIAM_BURIRAM",
		"Buriram"),
		("LOC_CITY_NAME_SIAM_NONG_BUA_LAMPHU",
		"Nong Bua Lamphu"),
		("LOC_CITY_NAME_SIAM_CHAIYAPHUM",
		"Chaiyaphum"),
		("LOC_CITY_NAME_SIAM_HAT_YAI",
		"Hat Yai"),
		("LOC_CITY_NAME_SIAM_PAK_KRET",
		"Pak Kret"),
		("LOC_CITY_NAME_SIAM_PATTAYA",
		"Pattaya"),
		("LOC_CITY_NAME_SIAM_SONGKHLA",
		"Songkhla"),
		("LOC_CITY_NAME_SIAM_SURAT_THANI",
		"Surat Thani"),
		("LOC_CITY_NAME_SIAM_YALA",
		"Yala"),
		("LOC_CITY_NAME_SIAM_PHUKET",
		"Phuket"),
		("LOC_CITY_NAME_SIAM_SAMUT_PRAKAN",
		"Samut Prakan"),
		("LOC_CITY_NAME_SIAM_TRANG",
		"Trang"),
		("LOC_CITY_NAME_SIAM_SAMUI",
		"Samui"),
		("LOC_CITY_NAME_SIAM_SAMUT_SAKHON",
		"Samut Sakhon"),
		("LOC_CITY_NAME_SIAM_RAYONG",
		"Rayong"),
		("LOC_CITY_NAME_SIAM_MAE_SOT",
		"Mae Sot"),
		("LOC_CITY_NAME_SIAM_OM_NOI",
		"Om Noi"),
		("LOC_CITY_NAME_SIAM_SAKON_NAKHON",
		"Sakon Nakhon"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_SIAM_MALE_1",
		"Yut"),
		("LOC_CITIZEN_SUK_SIAM_MALE_2",
		"Daeng"),
		("LOC_CITIZEN_SUK_SIAM_MALE_3",
		"Singh"),
		("LOC_CITIZEN_SUK_SIAM_MALE_4",
		"Siri"),
		("LOC_CITIZEN_SUK_SIAM_MALE_5",
		"Somboon"),
		("LOC_CITIZEN_SUK_SIAM_MALE_6",
		"Ram"),
		("LOC_CITIZEN_SUK_SIAM_MALE_7",
		"Tri"),
		("LOC_CITIZEN_SUK_SIAM_MALE_8",
		"Thong"),
		("LOC_CITIZEN_SUK_SIAM_MALE_9",
		"Poom"),
		("LOC_CITIZEN_SUK_SIAM_MALE_10",
		"Naret"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_1",
		"Suda"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_2",
		"Bua"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_3",
		"Naree"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_4",
		"Manee"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_5",
		"Mali"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_6",
		"Rung"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_7",
		"Wanee"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_8",
		"Pim"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_9",
		"Somjit"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_10",
		"Rudee"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_1",
		"Abhisit"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_2",
		"Sukrit"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_3",
		"Kasidis"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_4",
		"Thanakon"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_5",
		"Chanapoom"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_6",
		"Tammatat"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_7",
		"Wisarute"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_8",
		"Kriangsak"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_9",
		"Narongchai"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_10",
		"Tanasak"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_1",
		"Anchaleephorn"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_2",
		"Paradee"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_3",
		"Phanthip"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_4",
		"Chanya"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_5",
		"Suphamart"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_6",
		"Arisa"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_7",
		"Jitsupa"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_8",
		"Nattira"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_9",
		"Chatnapa"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_10",
		"Athitaya"),
--------------------------------------------------------------------
-- Named Places
--------------------------------------------------------------------
		("LOC_NAMED_RIVER_CHAO_PHRAYA_NAME",				"Chao Phraya River"),
		("LOC_NAMED_RIVER_PING_NAME",						"Ping River"),
		("LOC_NAMED_RIVER_NAN_NAME",						"Nan River"),
		("LOC_NAMED_RIVER_WANG_NAME",						"Wang River"),
		("LOC_NAMED_RIVER_YOM_NAME",						"Yom River"),
		("LOC_NAMED_RIVER_PA_SAK_NAME",						"Pa Sak River"),
		("LOC_NAMED_RIVER_MUN_NAME",						"Mun River"),
		("LOC_NAMED_MOUNTAIN_DAEN_LAO_NAME",				"Daen Lao Range"),
		("LOC_NAMED_MOUNTAIN_LUANG_PRABANG_NAME",			"Luang Prabang Range"),
		("LOC_NAMED_MOUNTAIN_THANON_THONG_CHAI_NAME",		"Thanon Thong Chai Range"),
		("LOC_NAMED_MOUNTAIN_PHI_PAN_NAM_NAME",				"Phi Pan Nam Range"),
		("LOC_NAMED_MOUNTAIN_PETCHABUN_NAME",				"Petchabun Mountains"),
		("LOC_NAMED_MOUNTAIN_SANKHAMPHAENG_NAME",			"Sankhamphaeng Range"),
		("LOC_NAMED_MOUNTAIN_BANTHAT_NAME",					"Banthat Range"),
		("LOC_NAMED_MOUNTAIN_SANKALAKHIRI_NAME",			"Sankalakhiri Range"),
		("LOC_NAMED_MOUNTAIN_TENASSERIM_NAME",				"Tenasserim Range"),
		("LOC_NAMED_VOLCANO_DOI_PHA_KHOK_HIN_FUU_NAME",		"Doi Pha Khok Hin Fuu"),

		("LOC_NAMED_LAKE_BUENG_BORAPHET_NAME",		"Bueng Boraphet"),
		("LOC_NAMED_LAKE_SONGKHLA_NAME",			"Songkhla Lake"),
		("LOC_NAMED_LAKE_PHAYAO_NAME",				"Phayao Lake"),
		("LOC_NAMED_LAKE_NONG_HAN_NAME",			"Nong Han"),
		("LOC_NAMED_SEA_KRUNG_THEP_BAY_NAME",		"Krung Thep Bay"),
		("LOC_NAMED_SEA_PHANG_NGA_BAY_NAME",		"Phang Nga Bay"),
		("LOC_NAMED_SEA_PRACHUAP_BAY_NAME",			"Prachuap Bay"),
		("LOC_NAMED_SEA_SATTAHIP_BAY_NAME",			"Sattahip Bay"),
		("LOC_NAMED_SEA_BANDON_BAY_NAME",			"Bandon Bay"),
		("LOC_NAMED_SEA_MANAO_BAY_NAME",			"Manao Bay"),
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_SIAM_LOCATION",
		"Asia"),
		("LOC_CIVINFO_SUK_SIAM_SIZE",
		"Est. 198 thousand square miles (513.1 thousand square km)"),
		("LOC_CIVINFO_SUK_SIAM_POPULATION",
		"67.9 million (2015 est.)"),
		("LOC_CIVINFO_SUK_SIAM_CAPITAL",
		"Various (Sukhothai, Phitsanulok, Ayutthaya, Lopburi, Thonburi, and currently Krung Thep/Bangkok)"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_1",
		"Located in Southeast Asia between Burma (a.k.a. Myanmar), Laos, Cambodia and Malaysia, Siam - now Thailand - has a long and storied history. A beautiful and mysterious land of dark forests and ancient mountains, Siam has seen occupation and revolution, flood and famine, and the rise and fall of empires."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_2",
		"The earliest known settlers of Siam spoke Mon-Khmer languages. There were several different groups on the southeast Asia peninsula. One, the Mon, were known to have accepted Buddhism as far back as the sixth century AD. Another group, the Khmer, were primarily located in Cambodia, their capital at Angkor (home of Angkor Wat); in the 12th century they possessed an empire stretching over half of modern Thailand. The Khmer tended to follow Hinduism rather than Buddhism."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_3",
		"Around 1,000 AD the area saw an influx of Tai-speaking people called the ""Tai."" Modern historians generally believe that the Tai originated in northern Vietnam. In a few centuries the Tai had spread across much of Southeast Asia, as far west as northeastern India and as far south as the Malay Peninsula. By the 13th century the Tai were numerous enough to threaten the Mon and Khmer primacy in Siam."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_4",
		"In the mid-thirteenth century a Tai ruler successfully revolted against the Khmer Empire, founding the Sukhothai kingdom. It remained a small, unimportant power until the ascension of its third ruler, Ramkhamhaeng, in 1279. In twenty short years this extraordinary leader would transform the small kingdom of Sukhothai into a major regional power."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_5",
		"During his reign Ramkhamhaeng expanded his kingdom's dominance west into Burma, east into Laos, and south down the Malay Peninsula. The king was a shrewd diplomat as well as a warlord; many territories joined his confederation voluntarily. Towards the end of his rule Ramkhamhaeng had a stone inscribed detailing his triumphs. It portrays a wealthy, contented kingdom ruled by a loving and benevolent monarch. Ramkhamhaeng died in 1298."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_6",
		"Sukhothai would last a century past its greatest leader's death before being consumed by Ayutthaya, a new Tai power rising in the south."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_7",
		"The kingdom of Ayutthaya was founded by Ramathibodi I in 1351 on the Chao Phraya River Basin, a fertile plain just north of modern Bangkok. The kingdom was formed on the remains of an earlier kingdom, Lavo. In 1352 King Ramathibodi attacked the Khmer, driving them east out of Siam. By 1387 Ayutthaya was strong enough to attack north, conquering Sukhothai. And in 1431 the kingdom attacked the Khmer once more, this time capturing and sacking the capital city of Angkor after a seven-month siege."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_8",
		"By all accounts the city of Ayutthaya was beautiful and wealthy. It was traversed by a series of north-south canals which brought water to all sections of the city. The remains of magnificent palaces and temples can be seen in the city today. The Tai of Ayutthaya were the first people in the area to be called ""Siamese"", and this of course eventually became the name of the entire country."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_9",
		"From the Khmer, the Ayutthayans adopted the belief in the divinity of the king. The king was above all people. None could gaze upon his face, except for members of the royal family. In addition to the king's increased religious/ceremonial power, King Trailok (1448-1488) reorganized the state to concentrate political power in the hands of the monarchy as well."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_10",
		"Socially, the Ayutthayans lived under a rigid caste system that assigned a numerical value to each person according to his or her rank. A slave was worth five units (called ""sakdi na""), a freeman 25 or so, and the heir to the throne perhaps 100,000 units. (The king himself was probably worth a gazillion - or even more!) Both Buddhism and Hinduism were followed in the country."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_11",
		"Having dealt with Sukhothai to the north and Khmer to the southeast, the greatest threat to Ayutthaya lay in Burma, to the west. In 1569 Ayutthaya was overrun and conquered by Burma. It regained its independence at the end of the 16th century. Burmese troops once again sacked the city in 1767. This time they deported the royal family, burned the city to the ground, and destroyed all of the Ayutthayan works of art and historical records. The Kingdom never recovered from this attack. However a new Siamese kingdom would rapidly rise to power in Ayutthaya's ashes."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_12",
		"In 1767 (the same year that saw the final destruction of Ayutthaya), a Tai leader named ""Taksin"" founded a new capital city at Thon Buri, some forty miles downstream from Ayutthaya (near present-day Bangkok). Built on the eastern side of the Chao Phraya River, the city was easier to defend from Burmese forces; located closer to the open sea, the city was ideally suited to accommodate international trade as well. In fact Taksin encouraged Chinese merchants to establish businesses in Thon Buri, and tax revenue from this trade was used to rebuild the Siamese economy, devastated from the recent Burmese attack."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_13",
		"Taking advantage of his country's wealth, Taksin constructed a powerful army and began expanding its territory. After retaking the territory that had belonged to Sukhothai and Ayutthaya, Taksin's troops conquered additional territory in Laos, and pushed the Burmese forces out of traditional Tai lands to the north. In 1782 Taksin began showing signs of serious mental illness and was overthrown and killed. He was succeeded by a general named ""Chao Phraya Chakri"" (he later changed his name to Rama I). The Chakri dynasty has remained in power in Thailand until today."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_14",
		"Shortly after assuming the throne, the new king moved his capital to Bangkok, a small village across the Chao Phraya River. Bangkok quickly grew into a bustling trading city, largely due to the many Chinese who immigrated to the metropolis."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_15",
		"King Rama I and his successors continued to expand Siamese power into Laos and south down the Malay Peninsula. They also continued to clash with Burma, who remained a perennial menace until that country in turn was menaced by Great Britain (approaching from India)."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_16",
		"King Rama I was also a great patron of Siamese culture, religion and the law. He rebuilt Siamese temples and palaces, and he greatly updated the Siamese legal system. His successor, Rama III (ruled 1809-24) was a patron of the arts, and no mean poet himself."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_17",
		"Perhaps the greatest triumph of Siamese diplomacy was that it avoided occupation by Western powers, unlike every other country in Southeast Asia. In 1826 Siam signed a treaty with Great Britain, and in 1855 this was expanded to allow the British unrestricted - and untaxed! - trade in Siamese ports. The British also secured the right to set up separate law courts to try cases involving British subjects. This was a humiliating loss of sovereignty and income for Siam, but it kept Britain from invading and occupying the country, and Siam soon signed similar treaties with other European powers and the United States."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_18",
		"King Rama IV (ruled 1851 - 1868) was a keen student of the West. In some ways King Rama IV was rather enlightened for that place and time. A former Buddhist monk before assuming the throne, he sought to reform Buddhism in the country, which he believed had become corrupt and filled with superstition. He also began to remake the Siamese monarchy, removing from it the more onerous trappings of godhood. Although he remained largely an absolute ruler, at least his subjects were allowed to look directly at him."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_19",
		"King Rama IV's son, Rama V, reigned from 1868 to 1910. He continued his father's practice of granting concessions to the West to maintain Siam's independence, losing large chunks of Laotian and Cambodian territory to the French and various bits of Malaysia to the British. He further reformed the monarchy and the government in general, including abolishing slavery, introducing a modern school system, constructing railways and telegraph systems, and establishing a new law court and judiciary."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_20",
		"King Rama V's two successors, the aptly-named Rama VI (ruled 1910-1925) and Rama VII (ruled 1925-1935), continued the modernization of Siam. In 1917 Rama VI opened the first university in Thailand. In that year he also entered World War I on the side of the Allies. He was able after the war to convince the victors to give up their special concessions in Siam, regaining for the first time in seventy-five years full independence for his country. However, Rama VI's reforms and wars were extremely expensive and necessitated reductions in government spending which caused deep resentment from the people. The discontent continued into his successor's reign, and it was exacerbated by the Great Depression."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_21",
		"In 1932 a group of students under a lawyer named ""Pridi Phanomyong"" and supported by the Siamese military staged a bloodless coup, compelling the king to agree to rule under a constitution and to accept the formation of a National Assembly. In 1933 members of the royal family attempted unsuccessfully to stage a counter-coup, and King Rama VII was forced to leave the country, abdicating in 1935. A regency council was appointed to act until the very young Prince Ananda Mahidol came of age."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_22",
		"In truth, however, the military was now running the country. In 1938 a field marshal (and one of the co-conspirators of the '32 coup that toppled Rama VII) became military dictator. Dictator Phibun Songkhram changed the name of the country to Thailand, encouraged Thai nationalism as well as anti-Chinese and pro-Japanese sentiment. In 1940, following the conquest of France by Germany, he invaded and captured French territory in Laos and Cambodia."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_23",
		"Late in 1941, following the attack on Pearl Harbor, Japanese troops marched into Thailand and requested right of passage through the country to facilitate their attack on Singapore, which was held by Great Britain. The Thai forces put up minimal symbolic resistance and then were ordered to lay down their arms. In 1942 Thailand signed an Alliance with Japan and declared war on Britain and the US. Resistance groups formed in the country and overseas, attacking the Japanese and the collaborating Thai government. In July 1944 Phibun was forced to resign, and the dictatorship collapsed following Japan's surrender in 1945."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_24",
		"Thailand got off relatively lightly following World War II. It had to return the territories it had snarfed up from the French, but generally it suffered no other penalties. It did suffer from a great deal of internal strife, however. In 1946 the king was found dead of a gunshot wound. The current leader of the government was blamed for the king's death and forced into exile, the proto-fascist Dictator Phibun Songkhram returning to power."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_25",
		"In the Cold War years the United States funneled huge sums of money into Thailand, most of which was taken by the military and the dictatorship. A majority of the country's industry was owned by the dictator and his cronies, and in 1957 the military staged another coup, placing yet another field marshal, Sarit Thanarat, in charge."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_26",
		"Thanarat ruled for five years. While maintaining total control over the government and military, he implemented economic reforms that spread the wealth among the growing Thai middle class, earning a good deal of popular support for doing so. The US gave him even more money, which he used to support the military, but also to improve the Thai infrastructure. Thanarat also gave support to the monarchy, which by then had no political power, but which once again became a powerful symbol of Thai nationalism. A popular leader during his life, after his death Thanarat's popularity waned a good deal when it was discovered how much of Thailand's money he had stolen and hidden away."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_27",
		"Thanarat's successors continued to receive huge amounts of American money, and in return they supported the American adventure in Vietnam. By the end of the 1960s more than 10,000 Thai troops were serving in Vietnam, and thousands of American soldiers were stationed in Thailand, which provided an important base for the US Air Force. Popular discontent for the war and the government grew, and in 1973 a student-led revolt drove the current leaders into exile."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_28",
		"Thailand enjoyed a brief period of parliamentary democracy, but in 1976 the military staged yet another coup, this time with the support of the monarchy. This in turn drove many disaffected Thais into the jungles, swelling the ranks of the insurgent Communist Party of Thailand. In 1980 the military ousted the right-wing government they had just installed and replaced it with a dictator with more democratic leanings. For the next eight years the military shared power with parliament, mediated by the king, and in 1988 an elected Prime Minister was put in power… for three years, when he was toppled by the military."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_29",
		"In 1992 the military ""junta"" held elections, which one of its own members won, much to nobody's surprise. The public were dissatisfied with this outcome, staging massive protests, which were put down with bloody force. Eventually the king intervened, the current dictator resigned and a more democratic government was put into place. This lasted for eight years, until in 2006, increasing public dissatisfaction and government excesses led to… another military coup."),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_CIVILIZATION_SUK_SIAM_DESCRIPTION_JFD_CIVILIZATION",
		"Siamese Civilization"),
--========================================================================================================================
-- Chang Suek
--========================================================================================================================
		("LOC_UNIT_SUK_SIAM_CHANGSUEK_NAME",
		"Chang Suek"	),
		("LOC_UNIT_SUK_SIAM_CHANGSUEK_DESCRIPTION",
		"Siamese unique Medieval era unit that replaces the Knight. Stronger, but slower and more expensive than the Knight. Adjacent units gain double experience from battles."),
		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_SIAM_CHANGSUEK_CHAPTER_HISTORY_PARA_1",
		"In Southeast Asia elephants continued to be employed in warfare far into the Middle Ages. In Siam, particularly, Chang Suek, or war elephants were highly prized. Three people would be stationed on each war elephant, one riding on the neck to do battle, one in the middle to pass weapons such as halberds, spears and javelins to the first and one person at the back to control the elephant. Even Siamese leaders would fight in battle on war elephants, indeed, King Ramkhamhaeng, King Naresuan and the consort of King Maha Chakkraphat, Sri Suriyothai have all fought atop Chang Suek."),
--========================================================================================================================
-- Floating Market
--========================================================================================================================
		("LOC_DISTRICT_SUK_FLOATINGMARKET_NAME",
		"Floating Market"	),
		("LOC_DISTRICT_SUK_FLOATINGMARKET_DESCRIPTION",
		"A district unique to Siam for finance and trade. Replaces the Commercial Hub district.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture, +1 [ICON_Gold] Gold from Luxury Resources worked by this City. +1 [ICON_TradeRoute] Trade Route capacity, if this city does not yet have a Harbor district.[NEWLINE][NEWLINE] Cannot be built on Hills."),
		("LOC_DISTRICT_SUK_FLOATINGMARKET_EXPANSION_1_DESCRIPTION",
		"A district unique to Siam for finance and trade. Replaces the Commercial Hub district.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture, +1 [ICON_Gold] Gold from Luxury Resources worked by this City. Cannot be built on Hills."),
		("LOC_DISTRICT_SUK_FLOATINGMARKET_EXPANSION_2_DESCRIPTION",
		"A district unique to Siam for finance and trade. Replaces the Commercial Hub district.[NEWLINE][NEWLINE]+1 [ICON_Gold] Gold from Luxury Resources. An additional +1 [ICON_Culture] Culture from Luxury Resources if this district is adjacent to a River, and another +1 [ICON_Gold] Gold if built on Floodplains.[NEWLINE][NEWLINE]Cannot be built on Hills."),
		("LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_SUK_FLOATINGMARKET_CHAPTER_HISTORY_PARA_1",
		"In the past the areas adjacent to the rivers were the first to be populated. Thus most communities of Thailand were built at the sides of rivers. The waterways served as means of transportation and the center of economic activity as well. Boats were mainly used for both local and regional trade, bringing goods from those that produced to those that could barter and trade. Such heavy reliance on boats in riverside communities, especially in the Chao Phraya River Basin, helped increase the number of floating markets and allowed them to serve as hubs for the communities in Central Thailand for centuries."),
--========================================================================================================================
-- RAMKHAMHAENG
--========================================================================================================================
		("LOC_LEADER_SUK_RAMKHAMHAENG_NAME",
		"Ramkhamhaeng"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_NAME",
		"The Thai Alphabet"	),
		("LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_DESCRIPTION",
		"Receive [ICON_Gold] Gold when a [ICON_TechBoosted] Eureka or [ICON_CivicBoosted] Inspiration is triggered."),
		("LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_EUREKA",
		"+{1} [ICON_Gold] Gold from triggering the [ICON_TechBoosted] Eureka for {2}"),
		("LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_INSPIRATION",
		"+{1} [ICON_Gold] Gold from triggering the [ICON_CivicBoosted] Inspiration for {2}"),
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_FATHER_GOVERNS_CHILDREN_NAME",
		"Father Governs Children"	),
		("LOC_AGENDA_SUK_FATHER_GOVERNS_CHILDREN_DESCRIPTION",
		"Likes civilizations with who have cultured and happy citizens. Is upset by civilizations that do not attend to their citizens' happiness"	),

		("LOC_DIPLO_KUDO_LEADER_SUK_RAMKHAMHAENG_REASON_ANY",
		"(You have cultured and happy citizens.)"	),
		("LOC_DIPLO_MODIFIER_SUK_FATHER_GOVERNS_CHILDREN_HAPPY",
		"Ramkhamhaeng is pleased you have cultured and happy citizens"	),

		("LOC_DIPLO_WARNING_LEADER_SUK_RAMKHAMHAENG_REASON_ANY",
		"(Your empire is unhappy.)"	),
		("LOC_DIPLO_MODIFIER_SUK_FATHER_GOVERNS_CHILDREN_UNHAPPY",
		"Ramkhamhaeng is concerned that your people are unhappy"	),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SUK_SIAM",
		"Chao"),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_SUK_SIAM",
		"Phraya"),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_SUK_SIAM",
		"Khun"),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_SUK_SIAM",
		"Chao Phraya"),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SUK_SIAM",
		"Chao Phukrong"),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_SIAM",
		"Phra Mahakrasat"),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SUK_SIAM",
		"Chao Phupitak"),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_SUK_SIAM",
		"Lekhatikarn"),
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_SUK_SIAM",
		"Prathanathipbodi"),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_SUK_SIAM",
		"Chom Phon"),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SUK_SIAM",
		"Chakkraphat"),

		-- Ramkhamhaeng gets a special case
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_RAMKHAMHAENG",
		"Pho Khun"),
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_RAMKHAMHAENG",
		"The people of Siam await your command, King Ramkhamhaeng. Cultivate your relationships with the states around you and allow trade to flow, then surely the best they have to offer will come to you. Rule them and your people like a father governs his children, and through their loyalty, Siam will flourish."  	),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Perhaps next time."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Wonderful."),
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Siam always seeks worthy friends. Can I consider you a friend to Siam?"),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"I don't believe this is the right time for us to make such a declaration."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"I gladly accept, on behalf of my people."),
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Since diplomacy has failed, I have no choice but to declare war."),
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"We are a peaceful nation, but do not think we will shy away from battle!"),
		("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Siam may fall today, but we have suffered defeats before, and we will ascend again."),
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Siam may fall today, but we have suffered defeats before, and we will ascend again."),
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"A trade delegation should arrive shortly with some fine Sangkhalok ceramic ware. I've thrown in a few sweets for you in the jars. Enjoy!"),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"I cannot accept."),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Your delegation has been gratefully received. They are resting in the lakeside Sala enjoying the lotus blossoms as we speak."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"I have never seen such ignominious behavior. How can you think yourself fit to rule a nation? (Denounces You)"),
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"The wellbeing of my people belies your false words."),
		("LOC_DIPLO_FIRST_MEET_LEADER_SUK_RAMKHAMHAENG_ANY",
		"My father was named Sri Indraditya, my mother was named Nang Sueng, and I am King Ramkhamhaeng. On behalf of all the people of Sukhothai, I bid you welcome to my kingdom."),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_RAMKHAMHAENG_ANY",
		"We have a city nearby. Perhaps you'd be interested in joining me in some restful meditation? Then afterwards, I can show you around."),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_RAMKHAMHAENG_ANY",
		"I gladly accept."),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Sukhothai is a fine city, with temples and gardens abound. What of your capital?"),
		("LOC_DIPLO_GREETING_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Hello."),
		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_RAMKHAMHAENG_ANY",
		"A ruler ought to be like a father to his people. Do not forget the duty you owe to those you rule."),
		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Fish in the water, rice in the fields. I'm pleased to see you care for your people's happiness and well-being."),
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Would you like to form an alliance?"),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"{LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY}"),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"{LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY}"),
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_RAMKHAMHAENG_ANY",
		"My people welcome the end of this pointless conflict."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_RAMKHAMHAENG_ANY",
		"No. I cannot accept."),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"For the sake of our peoples, I beg you to end this war."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Siam is always open for the weary traveler. Your people are welcome."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_RAMKHAMHAENG_ANY",
		"For the safety of my people, I must unfortunately deny your request. I do hope you can understand."),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_RAMKHAMHAENG_ANY",
		"I beg you to allow my people access to your fine nation."),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_RAMKHAMHAENG_ANY",
		"Your troops are suspiciously close to my borders. Should I be worried?"),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_RAMKHAMHAENG_QUOTE",
		"In the water there is fish and in the fields there is rice."  	),

		("LOC_PEDIA_LEADERS_PAGE_SUK_RAMKHAMHAENG_TITLE",
		"Pho Khun Ramkhamhaeng"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_RAMKHAMHAENG_SUBTITLE",
		"Rama the Bold"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_CAPSULE_BODY",
		"As in history, Siam is a center of diplomacy and commerce. Under Ramkhamhaeng, Siam's strong economic base combined with its City-State tributaries will allow Siam to pursue any victory."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_DETAILED_BODY",
		"Siam is an unrivaled diplomat, gaining an additional Envoy when completing any Civic that already provides them. The City-State friends they gain will provide useful yield boosts to Siam's districts. To help aid with this, place districts next to a river to gain extra [ICON_Amenities] Amenities to aid with expansion. Siam's Floating Markets will incentivise grabbing Luxury Resources as well, providing [ICON_Culture] Culture and [ICON_Gold] Gold when working them, so keep that in mind when founding your cities. Ramkhamhaeng augments this already very versatile mix of abilities, by providing more [ICON_Gold] Gold for pursuing [ICON_TechBoosted] Eurekas and [ICON_CivicBoosted] Inspirations. Essentially, build up a strong economic and diplomatic base, then leverage it for victory."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_HISTORY_PARA_1",
		"In 1278, a prince named “Ramkhamhaeng” inherited the small and unimportant kingdom of Sukhothai. In twenty years, employing a brilliant combination of military genius and shrewd diplomacy, he expanded his country's borders and influence to cover much of Southeast Asia."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_HISTORY_PARA_2",
		"Not much is known about Ramkhamhaeng's early life. His parents were King Sri Indraditya and Queen Sueang. He had two sisters and two older brothers, one of whom died early and the other, Ban Mueang, became king on their father's death. Ramkhamhaeng was said to have studied under the poet wise-man Sukathanta. At 19 he served under his father during the latter's attack on the city of Sukhothai, which was held by the Khmer. The success of this attack greatly expanded the king's power, essentially establishing Sukhothai as an independent kingdom. Because of his heroic actions during the battle the prince was given the title ""Phra Ram Khamhaeng,"" or Rama the Bold. Upon the death of his father in 1257, his brother, the new king Ban Mueang, put Ramkhamhaeng in charge of the city of Si Satchanalai. Ban Mueang died twenty years later, and Ramkhamhaeng ascended to the throne."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_HISTORY_PARA_3",
		"During his reign Ramkhamhaeng expanded his kingdom's dominance west into Burma, east into Laos, and south down the Malay Peninsula. The king was a shrewd diplomat as well as a warlord; many territories joined his confederation voluntarily. Ramkhamhaeng did not seek to dominate Southeast Asia, rather he promoted trade and diplomatic alliances with surrounding kingdoms."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_HISTORY_PARA_4",
		"Regarded as a benevolent and wise ruler, one of his major achievements was the compilation of a system of writing and a new Thai alphabet which he adapted from the various forms of Khmer script that were previously used. The alphabet King Ramkhamhaeng the Great devised in 1283 is essentially the same as that which is used today in Thailand and he is sometimes referred to as the ‘Father of the Thai language’. He has also been credited as the most important figure in establishing Theravada Buddhism in Thailand although the extent of his role is disputed by some historians."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_HISTORY_PARA_5",
		"Ramkhamhaeng died in 1298. His extended empire, held together by his personal magnetism and brilliant international diplomacy, did not long survive his death, and the furthest provinces soon broke away. Sukhothai itself survived another century before it fell."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_RAMKHAMHAENG_CHAPTER_HISTORY_PARA_6",
		"Ramkhamhaeng is viewed today as a great leader and the first to rule over a united Siam (later Thailand). It should be remembered however that almost all that we know about him comes from the stone inscription that he himself created. If he did have any major flaws, would he have carved them into the living rock for all of history to see? (Would any of today's world leaders do so?) Still, there is plenty of independent evidence to show that he successfully created a great empire and his people prospered during his reign. And that's a record that any leader could be proud of.");
--------------------------------------------------------------------
--------------------------------------------------------------------