/*
	Civilization
	Credits: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
		(Type,							Kind				)
VALUES	('CIVILIZATION_CVS_NORMANDY',	'KIND_CIVILIZATION'	);
		
-----------------------------------------------
-- Civilizations
-----------------------------------------------

INSERT INTO	Civilizations
		(CivilizationType,				Name,									Description,									Adjective,									StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_CVS_NORMANDY',	'LOC_CIVILIZATION_CVS_NORMANDY_NAME',	'LOC_CIVILIZATION_CVS_NORMANDY_DESCRIPTION',	'LOC_CIVILIZATION_CVS_NORMANDY_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_EURO' 	);

-----------------------------------------------
-- NamedRivers
-----------------------------------------------

REPLACE INTO NamedRivers
		(NamedRiverType,		Name						)
VALUES	('NAMED_RIVER_ORNE',	'LOC_NAMED_RIVER_ORNE'		),
		('NAMED_RIVER_BRESLE',	'LOC_NAMED_RIVER_BRESLE'	);

-----------------------------------------------
-- NamedRiverCivilizations
-----------------------------------------------

INSERT INTO NamedRiverCivilizations
		(CivilizationType,				NamedRiverType			)
VALUES	('CIVILIZATION_CVS_NORMANDY',	'NAMED_RIVER_SEINE'		),
		('CIVILIZATION_CVS_NORMANDY',	'NAMED_RIVER_ORNE'		),
		('CIVILIZATION_CVS_NORMANDY',	'NAMED_RIVER_BRESLE'	);
		
-----------------------------------------------
-- CityNames
-----------------------------------------------

INSERT INTO	CityNames
		(CivilizationType,			 CityName )
VALUES	('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_ROUEN'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_CAEN'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_EVREUX'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_ALENCON'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_LE_HAVRE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_CHERBOURG'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_DIEPPE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_SAINT_LO'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BAYEUX'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_AVRANCHES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_FECAMP'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_COUTANCES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BERNAY'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_ARGENTAN'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_EU'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_AUMALE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_EXMES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_GISORS'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_FALAISE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_LISIEUX'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_LOUVIERS'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_SEES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BRIONNE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_JUMIEGES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_HONFLEUR'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_ARQUES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_LILLEBONNE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_GIVERNY'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_VALOGNES'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BARFLEUR'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_VERNON'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_IVRY_LA_BATAILLE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_MONT_SAINT_MICHE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BEAUMONT'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BESSIN'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_VERNON'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_CABOURG'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_BOLBEC'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_DEAUVILLE'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_ELBEUF'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_YVETOT'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_LE_GRAND_QUEVILLY'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_MONT_SAINT_AIGNAN'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_SAINT_ETIENNE_DU_ROUVRAY'),
		('CIVILIZATION_CVS_NORMANDY', 'LOC_CITY_NAME_LE_PETIT_QUEVILLY');
					
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------

INSERT INTO	CivilizationCitizenNames
		(CivilizationType,				CitizenName,							Female	)
VALUES	('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_1',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_2',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_3',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_4',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_5',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_6',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_7',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_8',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_9',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_MALE_10',		0 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_1',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_2',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_3',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_4',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_5',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_6',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_7',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_8',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_9',	1 		),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CITIZEN_CVS_NORMANDY_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------

INSERT INTO	CivilizationInfo
		(CivilizationType,				Header,						Caption,									SortIndex	)
VALUES	('CIVILIZATION_CVS_NORMANDY',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_CVS_NORMANDY_LOCATION',		10			),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_CVS_NORMANDY_SIZE',			20			),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_CVS_NORMANDY_POPULATION',		30			),
		('CIVILIZATION_CVS_NORMANDY',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_CVS_NORMANDY_CAPITAL',			40			);
		
-----------------------------------------------
-- Start Bias
-----------------------------------------------

INSERT INTO	StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier	)
VALUES	('CIVILIZATION_CVS_NORMANDY',	'TERRAIN_COAST',		2		),
		('CIVILIZATION_CVS_NORMANDY',	'TERRAIN_GRASS_HILLS',	3		);

INSERT INTO	StartBiasResources
		(CivilizationType,				ResourceType,	Tier	)
SELECT	'CIVILIZATION_CVS_NORMANDY',	ResourceType,	5
FROM	Improvement_ValidResources
WHERE	ImprovementType IN	('IMPROVEMENT_CAMP', 'IMPROVEMENT_PASTURE');